// Neighborhood pages. The clinic is at 2550 W. Fullerton Ave, Logan Square,
// near Fullerton and Rockwell. See docs/CONTENT-RULES.md before editing.
import type { Area } from "./types";

const TRAVEL_VERIFY = "Travel time to 2550 W. Fullerton Ave: confirm with a map check at typical hours";

export const areas: Area[] = [
  {
    slug: "logan-square",
    name: "Logan Square",
    travel: "A short walk or bus ride from most of the neighborhood",
    route: "The clinic is on Fullerton between Maplewood and Rockwell, two blocks west of Western. From the California Blue Line stop, walk north on California to Fullerton and east a few blocks. The 74 Fullerton bus stops close to the door in both directions.",
    intro: [
      "Olivo Med Spa has been part of Logan Square since 2013, when Dr. Jacqueline Olivo opened a physician-led practice on Fullerton Avenue. The neighborhood has changed a great deal since then. The clinic has kept the same idea: a doctor sees you, listens, and builds a plan that fits your face, your body, and your schedule.",
      "Because it is close, many Logan Square patients use the clinic the way they would use a good dentist: a Skin Club facial every month, wrinkle relaxers a few times a year, and a series of Emsculpt Neo or laser hair reduction when the timing is right. Everything is under one roof with nine device platforms on site.",
    ],
    notes: ["Walkable from the boulevards, Palmer Square, and the Milwaukee Avenue corridor", "Street parking on Fullerton and nearby side streets", "Neighbors often book maintenance visits on the way home from work"],
    popular: ["hydrafacial", "botox-and-xeomin", "emsculpt-neo", "laser-hair-removal"],
    seo: { title: "Med Spa in Logan Square, Chicago | Olivo Med Spa", description: "Olivo Med Spa is a physician-led med spa on Fullerton Ave in Logan Square, Chicago, open since 2013. Injectables, Emsculpt Neo, lasers, and facials." },
    verify: ["Walking and bus travel times within Logan Square: confirm", "Parking note: client to confirm", "74 Fullerton bus stop proximity: confirm"],
  },
  {
    slug: "bucktown",
    name: "Bucktown",
    travel: "About 5 to 10 minutes by car",
    route: "Take Damen or Western north to Fullerton, then head west to Rockwell. The 74 Fullerton bus runs west from the Damen and Western corners straight to the clinic. From the Damen Blue Line stop, ride three stops northwest to California and walk north.",
    intro: [
      "Bucktown sits just southeast of the clinic, close enough that a treatment fits between errands on Damen and dinner on Armitage. Many patients first come in for something quick, such as a wrinkle relaxer visit or a Hydrafacial, then discover the wider menu a physician-led clinic offers.",
      "Dr. Olivo has treated Bucktown residents for more than a decade. The neighborhood tends to ask for natural-looking injectables, skin resurfacing that fits around a work calendar, and body contouring ahead of summer. Every plan begins with a consultation where candidacy and expectations are set.",
    ],
    notes: ["A short drive or one bus up Fullerton", "Popular for lunchtime injectable visits", "Emsculpt Neo series are easy to keep on a five-to-ten-day rhythm from this close"],
    popular: ["botox-and-xeomin", "hydrafacial", "emsculpt-neo", "dermal-fillers"],
    seo: { title: "Med Spa near Bucktown, Chicago | Olivo Med Spa", description: "Olivo Med Spa is a physician-led clinic minutes from Bucktown on Fullerton Ave in Logan Square, Chicago. Injectables, Emsculpt Neo, facials, and lasers." },
    verify: [TRAVEL_VERIFY, "Blue Line stop count from Damen to California: confirm"],
  },
  {
    slug: "wicker-park",
    name: "Wicker Park",
    travel: "About 10 minutes by car or 15 minutes on the Blue Line",
    route: "Follow Milwaukee Avenue northwest through the Six Corners of Logan Square, turn right on California and left on Fullerton. Or take the Blue Line from Damen or Division to California and walk north to Fullerton. By car, Damen north to Fullerton also works.",
    intro: [
      "Wicker Park and Logan Square share Milwaukee Avenue, so getting to the clinic is a straight line. Wicker Park patients tend to be well researched. They arrive knowing the difference between a hyaluronic acid filler and a collagen stimulator and want a physician to tell them which one their face actually needs.",
      "That suits the way Dr. Olivo works. Consultations are unhurried and specific. Patients from Wicker Park often come for lip and cheek filler, Opus Plasma or RF microneedling for texture, and skin memberships that keep results steady between bigger treatments.",
    ],
    notes: ["One Blue Line ride, no transfer", "Well-informed patients who want a doctor's opinion, not a menu", "Resurfacing timed around weekends is common"],
    popular: ["dermal-fillers", "opus-plasma", "exion-rf-microneedling", "hydrafacial"],
    seo: { title: "Med Spa near Wicker Park, Chicago | Olivo Med Spa", description: "Olivo Med Spa serves Wicker Park from Logan Square, one Blue Line ride up Milwaukee Ave. Physician-led injectables, Opus Plasma, and facials in Chicago." },
    verify: [TRAVEL_VERIFY],
  },
  {
    slug: "lincoln-park",
    name: "Lincoln Park",
    travel: "About 10 to 15 minutes by car along Fullerton",
    route: "Fullerton runs straight from the lake to the clinic. Drive west on Fullerton past Ashland, Damen, and Western, and the clinic is on the north side just before Rockwell. The 74 Fullerton bus covers the same route from any stop along the way.",
    intro: [
      "Lincoln Park and the clinic share one street. Fullerton Avenue starts at the lakefront and passes DePaul, the Kennedy, and Western before reaching the clinic at 2550 West. That makes Olivo Med Spa an easy alternative to downtown practices without the parking and the wait.",
      "Lincoln Park patients often come for the full range of physician-led care: wrinkle relaxers and filler, Emface for non-surgical lifting, laser resurfacing, and medical services such as hormone therapy and weight management. Dr. Olivo's family medicine background matters for the medical side of the menu.",
    ],
    notes: ["One street, no turns, from most of the neighborhood", "Parking is simpler than downtown or Clybourn", "Medical and aesthetic care in one physician-led practice"],
    popular: ["botox-and-xeomin", "emface", "co2-fractional-laser", "hormone-therapy"],
    seo: { title: "Med Spa near Lincoln Park, Chicago | Olivo Med Spa", description: "Olivo Med Spa is a physician-led med spa a drive west on Fullerton from Lincoln Park to Logan Square, Chicago. Injectables, Emface, lasers, and medical care." },
    verify: [TRAVEL_VERIFY, "North side of Fullerton: confirm building side"],
  },
  {
    slug: "avondale",
    name: "Avondale",
    travel: "About 5 minutes by car",
    route: "Head south on Kedzie or California to Fullerton, then east toward Rockwell. Milwaukee Avenue southeast to Fullerton also works. On the Blue Line, ride from Belmont two stops southeast to California and walk north on California to Fullerton.",
    intro: [
      "Avondale is directly north of the clinic, and for many residents it is the nearest physician-led med spa. The drive down California or Kedzie takes a few minutes. Patients from Avondale include long-time neighbors who have followed the practice since 2013 and newer arrivals looking for a doctor rather than a franchise.",
      "The neighborhood's mix shows in what people book: laser hair reduction memberships, tattoo removal, IPL for sun damage, and Emsella for postpartum pelvic floor strength. Spanish is spoken at the clinic, which matters to many Avondale families.",
    ],
    notes: ["Closest of the northern neighborhoods by car", "Long-standing patients from the Polish and Latino communities", "Laser and removal treatments are frequent bookings"],
    popular: ["laser-hair-removal", "tattoo-removal", "ipl-photofacial", "emsella"],
    seo: { title: "Med Spa near Avondale, Chicago | Olivo Med Spa", description: "Avondale residents reach Olivo Med Spa in a few minutes down California to Fullerton Ave in Logan Square, Chicago. Physician-led lasers and injectables." },
    verify: [TRAVEL_VERIFY, "Spanish spoken at the clinic: client to confirm", "Blue Line stop count from Belmont to California: confirm"],
  },
  {
    slug: "humboldt-park",
    name: "Humboldt Park",
    travel: "About 5 to 10 minutes by car",
    route: "Take California or Kedzie north from North Avenue or Division to Fullerton, then east on Fullerton toward Rockwell. Western north to Fullerton and a short jog west also works. The 74 Fullerton bus connects from the California and Kedzie corridors.",
    intro: [
      "Humboldt Park is a short drive south and west of the clinic, and Olivo Med Spa has served families from the neighborhood for years. Dr. Olivo trained in Peru and completed her residency at the University of Illinois. Patients often say they came for a doctor who would take the time to explain things, in English or Spanish.",
      "Treatments popular with Humboldt Park patients range from facials and peels chosen for deeper skin tones to body contouring and medical weight management. Because Dr. Olivo is a physician, the clinic can look at hormones and metabolism alongside aesthetic goals, all in one place.",
    ],
    notes: ["A straight shot up California or Kedzie", "Skin treatments selected with darker skin tones in mind", "Medical weight management and IV therapy alongside aesthetics"],
    popular: ["glp-1-weight-management", "pca-chemical-peels", "emsculpt-neo", "iv-therapy"],
    seo: { title: "Med Spa near Humboldt Park, Chicago | Olivo Med Spa", description: "Olivo Med Spa is a physician-led clinic minutes from Humboldt Park on Fullerton Ave in Logan Square, Chicago. Facials, body contouring, and weight care." },
    verify: [TRAVEL_VERIFY, "Spanish spoken at the clinic: client to confirm"],
  },
  {
    slug: "ukrainian-village",
    name: "Ukrainian Village",
    travel: "About 10 to 15 minutes by car",
    route: "Take Western or Damen north from Chicago Avenue to Fullerton, then west a few blocks to Rockwell. On transit, the Blue Line from Division to California is a short ride, followed by a walk north on California to Fullerton.",
    intro: [
      "Ukrainian Village is due south of the clinic along Western and Damen. It is a neighborhood of long-time residents and careful newcomers, and both tend to value a practice that has been in the same place under the same physician since 2013.",
      "Patients from Ukrainian Village frequently ask about subtle work: a little wrinkle relaxer, conservative filler, and skin treatments that do not announce themselves. Dr. Olivo's approach is to start light and build, which fits. Miradry for underarm sweating is another regular request from this part of the city.",
    ],
    notes: ["A straight drive north on Western or Damen", "Subtle, conservative injectables are the usual ask", "Miradry consultations often begin here"],
    popular: ["botox-and-xeomin", "revanesse-versa", "miradry", "laser-genesis"],
    seo: { title: "Med Spa near Ukrainian Village, Chicago | Olivo Med Spa", description: "Olivo Med Spa serves Ukrainian Village from Logan Square, a short drive north on Western. Physician-led injectables, skin care, and Miradry in Chicago." },
    verify: [TRAVEL_VERIFY],
  },
  {
    slug: "roscoe-village",
    name: "Roscoe Village",
    travel: "About 10 minutes by car",
    route: "Take Western south past Belmont and Diversey to Fullerton, then turn right and go two blocks west toward Rockwell. Damen south to Fullerton and west also works. The Western bus to Fullerton connects with the 74 Fullerton bus for the last stretch.",
    intro: [
      "Roscoe Village is a short drive down Western, and the clinic is the first physician-led med spa many residents find once they look west of the river. Families in the neighborhood tend to come for practical reasons: postpartum core and pelvic floor strength, laser hair reduction, and skin care that fits a busy calendar.",
      "Emsculpt Neo and Emsella are common bookings from Roscoe Village, often together. Dr. Olivo reviews history first, especially after pregnancy, and sets a schedule that works with school pickups and commutes. Skin Club memberships keep the facial side consistent.",
    ],
    notes: ["Straight south on Western, then two blocks west", "Postpartum core and pelvic floor plans are common", "Membership rhythm suits busy family calendars"],
    popular: ["emsculpt-neo", "emsella", "laser-hair-removal", "hydrafacial"],
    seo: { title: "Med Spa near Roscoe Village, Chicago | Olivo Med Spa", description: "Roscoe Village residents reach Olivo Med Spa in Logan Square by a short drive down Western. Physician-led Emsculpt Neo, Emsella, lasers, and facials." },
    verify: [TRAVEL_VERIFY],
  },
  {
    slug: "irving-park",
    name: "Irving Park",
    travel: "About 10 to 15 minutes by car or 20 minutes on the Blue Line",
    route: "Take the Kennedy Expressway southeast to the Fullerton exit and head west on Fullerton to Rockwell, or follow Milwaukee Avenue southeast to Fullerton. On transit, the Blue Line from Irving Park to California is a direct ride, then walk north on California.",
    intro: [
      "Irving Park sits up the Kennedy and Milwaukee corridor from the clinic. Both routes lead to Fullerton, and the Blue Line runs the same line without traffic. Patients from Irving Park often started with a referral from a neighbor and stayed because a physician runs the practice.",
      "Requests from Irving Park lean toward medical services and skin repair: hormone therapy, GLP-1 weight management, IPL for sun and age spots, and CO2 fractional resurfacing timed for the cooler months. Dr. Olivo handles the medical side directly and sets expectations at the consultation.",
    ],
    notes: ["Kennedy or Milwaukee by car, one Blue Line ride otherwise", "Medical services are a frequent reason to visit", "Resurfacing is often scheduled for fall and winter"],
    popular: ["hormone-therapy", "ipl-photofacial", "co2-fractional-laser", "glp-1-weight-management"],
    seo: { title: "Med Spa near Irving Park, Chicago | Olivo Med Spa", description: "Olivo Med Spa is a physician-led med spa in Logan Square, a trip from Irving Park by the Kennedy or the Blue Line. Medical and aesthetic care in Chicago." },
    verify: [TRAVEL_VERIFY, "Kennedy Fullerton exit routing: confirm"],
  },
  {
    slug: "old-town",
    name: "Old Town",
    travel: "About 15 to 20 minutes by car",
    route: "Take Armitage or North Avenue west to Western, turn north to Fullerton, and go west two blocks toward Rockwell. Alternatively, drive north to Fullerton and follow it west the entire way. The 74 Fullerton bus runs from Halsted and Clark to the clinic.",
    intro: [
      "Old Town patients usually find the clinic when they want a physician-led practice without the downtown price of parking and time. The drive west along Armitage or North is direct, and Fullerton itself runs from Old Town's northern edge straight to the door.",
      "The neighborhood tends to book full facial plans: wrinkle relaxers, filler placed for structure rather than size, Emface for lifting, and a resurfacing series for texture. Dr. Olivo builds these over several visits so the changes stay natural and the calendar stays manageable.",
    ],
    notes: ["A direct westbound drive on Armitage, North, or Fullerton", "Whole-face plans staged over several visits", "Weekday evening appointments until 7 PM are popular"],
    popular: ["dermal-fillers", "emface", "botox-and-xeomin", "exion-rf-microneedling"],
    seo: { title: "Med Spa near Old Town, Chicago | Olivo Med Spa", description: "Olivo Med Spa is a physician-led med spa in Logan Square, a direct drive west from Old Town along Armitage. Injectables, Emface, and resurfacing in Chicago." },
    verify: [TRAVEL_VERIFY, "74 Fullerton bus route from Halsted and Clark: confirm"],
  },
  {
    slug: "lakeview",
    name: "Lakeview",
    travel: "About 15 minutes by car",
    route: "Take Diversey west to Western, turn south to Fullerton, and head west two blocks toward Rockwell. Or take Ashland south to Fullerton and follow Fullerton west past Western. From southern Lakeview, the 74 Fullerton bus is a single ride.",
    intro: [
      "Lakeview is a short cross-town drive from the clinic along Diversey or Belmont, then down Western to Fullerton. Many Lakeview patients are comparing against Lincoln Park and downtown options and choose Olivo Med Spa because a doctor, not a licensee, leads the practice.",
      "Common requests from Lakeview include laser hair reduction memberships, Kybella or Exion for under the chin, Hydrafacial and DiamondGlow on a Skin Club rhythm, and body contouring before travel. Every plan starts with a consultation where candidacy and expectations are set.",
    ],
    notes: ["Diversey or Belmont west, then Western south to Fullerton", "Chin and jawline treatments are a frequent ask", "Skin Club members often pair a facial with an injectable visit"],
    popular: ["laser-hair-removal", "kybella", "diamondglow", "exion-face"],
    seo: { title: "Med Spa near Lakeview, Chicago | Olivo Med Spa", description: "Olivo Med Spa serves Lakeview from Logan Square, a cross-town drive along Diversey to Western. Physician-led lasers, Kybella, and facials in Chicago." },
    verify: [TRAVEL_VERIFY, "Physician-led versus licensee wording: client to confirm as in clinic.ts"],
  },
  {
    slug: "river-north",
    name: "River North",
    travel: "About 20 minutes by car or 25 minutes on the Blue Line",
    route: "Take the Kennedy Expressway northwest to the Fullerton exit, then west on Fullerton past Western to Rockwell. On transit, board the Blue Line at Grand or Chicago and ride northwest to California, then walk north on California to Fullerton.",
    intro: [
      "River North has plenty of aesthetic practices. Patients who make the trip to Logan Square do so for a specific reason: a physician-owned clinic with nine device platforms under one roof, consultations that are not sales pitches, and pricing that reflects a neighborhood address rather than a downtown lease.",
      "Downtown professionals from River North often book Emsculpt Neo, Emface, and Miradry, treatments that reward a clinic with the full device platform and a doctor overseeing settings. Evening hours until 7 PM on weekdays and Saturday hours make the trip workable around a downtown schedule.",
    ],
    notes: ["Kennedy to Fullerton by car, Blue Line without a transfer", "Device treatments that benefit from a full platform on site", "Evening and Saturday hours fit downtown schedules"],
    popular: ["emsculpt-neo", "emface", "miradry", "botox-and-xeomin"],
    seo: { title: "Med Spa near River North, Chicago | Olivo Med Spa", description: "Olivo Med Spa is a physician-owned med spa in Logan Square, one Blue Line ride from River North. Emsculpt Neo, Emface, Miradry, and injectables in Chicago." },
    verify: [TRAVEL_VERIFY, "Pricing comparison to downtown: client to confirm or remove"],
  },
];
