// Extra photo slots that are not tied to one service. Paths on the current site.
export const liveSlots = [
  { slot: "home", paths: ["/"] },
  { slot: "about", paths: ["/about/"] },
  { slot: "team", paths: ["/meet-our-team-olivo-medspa/"] },
  { slot: "dr-olivo", paths: ["/meet-our-team-olivo-medspa/jacqueline-olivo-md/"] },
  { slot: "michelina", paths: ["/meet-our-team-olivo-medspa/michelina-quaranta-faber/", "/michelina-quaranta-faber/"] },
  { slot: "bianca", paths: ["/bianca-esparza/"] },
  { slot: "valeria", paths: ["/valeria-mendez/"] },
  { slot: "gallery", paths: ["/gallery-intro/", "/gallery/"] },
  { slot: "body-contouring", paths: ["/body-treatments/", "/services/body-treatments/"] },
  { slot: "facial-lifting", paths: ["/emface/", "/pdo-threads/"] },
  { slot: "injectables", paths: ["/injectables-dermal-fillers/"] },
  { slot: "skin-resurfacing", paths: ["/laserlight-treatments/skin-tightening/", "/opus-plasma/"] },
  { slot: "laser-and-light", paths: ["/laser-hair-reduction/", "/ipl/"] },
  { slot: "facials-and-peels", paths: ["/facial-treatments/", "/hydrafacial/"] },
  { slot: "sweat", paths: ["/miradry/"] },
  { slot: "wellness", paths: ["/services/wellness-treatments/", "/iv-therapy/"] },
  { slot: "removals", paths: ["/tattoo-removal/", "/mole-removal/"] },
  { slot: "memberships", paths: ["/skin-club/", "/memberships/", "/sculpt-it/"] },
  { slot: "specials", paths: ["/promos/", "/promotions/current-specials/"] },
  { slot: "skincare", paths: ["/skincare-products/", "/skincare-products/zo/"] },
  { slot: "visit", paths: ["/contact/", "/location/olivo-med-spa/"] },
  { slot: "for-men", paths: ["/for-men/"] },
];
