// Extra photo slots that are not tied to one service. Paths on the current site.
export const liveSlots = [
  { slot: "home", paths: ["/"] },
  { slot: "about", paths: ["/about/"] },
  { slot: "team", paths: ["/meet-our-team-olivo-medspa/"] },
  { slot: "dr-olivo", paths: ["/meet-our-team-olivo-medspa/jacqueline-olivo-md/"] },
  { slot: "michelina", paths: ["/meet-our-team-olivo-medspa/michelina-quaranta-faber/", "/michelina-quaranta-faber/"] },
  { slot: "bianca", paths: ["/bianca-esparza/"] },
  { slot: "valeria", paths: ["/valeria-mendez/"] },
    { slot: "body-contouring", paths: ["/body-treatments/", "/emsculpt/", "/for-men/"] },
  { slot: "facial-lifting", paths: ["/services/emface/", "/services/pdo-threads/", "/services/injectables-dermal-fillers/radiesse/", "/emface/", "/pdo-threads/", "/radiesse/", "/facial-treatments/"] },
  { slot: "injectables", paths: ["/services/injectables-dermal-fillers/", "/services/injectables-dermal-fillers/kybella/", "/services/skincare-products/xeomin/", "/injectables-dermal-fillers/", "/kybella/", "/versa/", "/skincare-products/xeomin/"] },
  { slot: "skin-resurfacing", paths: ["/services/facial-treatments/opus-plasma/", "/services/laserlight-treatments/co2-laser-fractional-resurfacing/", "/services/laserlight-treatments/microneedling-rf/", "/laserlight-treatments/skin-tightening/", "/opus-plasma/", "/co2/", "/microneedling-rf/", "/erbium/"] },
  { slot: "laser-and-light", paths: ["/services/laserlight-treatments/laser-hair-removal/", "/services/laserlight-treatments/ipl-photofacial/", "/services/laserlight-treatments/erbium-laser-resurfacing/", "/laser-hair-reduction/", "/ipl/", "/lasergenesis/", "/laserlight-treatments/skin-tightening/"] },
  { slot: "facials-and-peels", paths: ["/hydrafacial/", "/services/facial-treatments/dermaplaning/", "/services/facial-treatments/red-out-facial/", "/facial-treatments/", "/hydrafacial/"] },
  { slot: "sweat", paths: ["/miradry/"] },
  { slot: "wellness", paths: ["/services/wellness-treatments/", "/hormone-replacement-therapy/", "/services/emsella/", "/services/wellness-treatments/", "/iv-therapy/"] },
  { slot: "removals", paths: ["/services/laserlight-treatments/tattoo-removal/", "/services/laserlight-treatments/mole-removal/", "/services/laserlight-treatments/spider-vein-removal/", "/tattoo-removal/", "/mole-removal/", "/vein-removal/", "/laserlight-treatments/skin-tightening/"] },
  { slot: "memberships", paths: ["/skin-club/", "/memberships/", "/sculpt-it/"] },
  { slot: "specials", paths: ["/promos/", "/promotions/current-specials/"] },
  { slot: "skincare", paths: ["/services/skincare-products/alastin/", "/services/skincare-products/zo/", "/services/skincare-products/skinbetterscience/", "/skincare-products/", "/skincare-products/zo/", "/skincare-products/alastin/", "/skincare-products/skinbetterscience/"] },
  { slot: "visit", paths: ["/contact/", "/location/olivo-med-spa/", "/about/", "/"] },
  { slot: "for-men", paths: ["/for-men/"] },
];
