// Body contouring and sweat. See docs/CONTENT-RULES.md before editing.
import type { Service } from "../types";

export const bodyServices: Service[] = [
  {
    slug: "emsculpt-neo",
    name: "Emsculpt Neo",
    category: "body-contouring",
    brand: "BTL",
    tag: "Body · No downtime",
    headline: "Builds muscle and reduces fat in the same 30-minute session, without surgery.",
    summary: "Emsculpt Neo combines radiofrequency heat with high-intensity electromagnetic muscle contractions to work on fat and muscle at once. Four sessions, no downtime, at a physician-led clinic in Logan Square.",
    intro: [
      "Emsculpt Neo is the body treatment people ask for by name. The applicator sits on the abdomen, buttocks, arms, calves, or thighs and delivers two energies in one pass: radiofrequency that warms the tissue and electromagnetic pulses that contract the muscle harder than you can voluntarily. You lie still. The device does the work.",
      "A plan is usually four sessions, spaced five to ten days apart, each about thirty minutes. Most people go back to their day immediately. Because the clinic owns the full BTL platform, Dr. Olivo can pair Emsculpt Neo with Exion for skin tightening when that is the better answer.",
      "Emsculpt Neo is not weight loss. It suits people who are already close to where they want to be and want more definition in a specific area.",
    ],
    benefits: ["Muscle and fat addressed in one session", "About thirty minutes per treatment", "No needles, anesthesia, or downtime", "Abdomen, buttocks, arms, thighs, calves", "Physician-led plan, not a menu"],
    concerns: ["stubborn-fat", "muscle-tone"],
    session: { duration: "About 30 minutes", sessions: "Four sessions, five to ten days apart", downtime: "None", feels: "Strong muscle contractions with warmth, like an intense workout you are not doing", results: "Most people notice change over the weeks after the series as muscle builds and the body clears treated fat", verify: "Session count, spacing, and timing of visible change: confirm with BTL clinical materials" },
    goodFor: ["Adults within reach of their goal weight who want definition", "People who cannot commit to more gym time", "Anyone cleared at consultation, including no metal implants in the area"],
    faqs: [
      { q: "Does Emsculpt Neo hurt?", a: "It is intense rather than painful. Contractions feel like a hard workout and the radiofrequency feels warm. Intensity is raised gradually and you are in control." },
      { q: "How many sessions do I need?", a: "A standard series is four sessions, five to ten days apart. Dr. Olivo sets the plan at your consultation and may adjust it for your area and goal.", verify: "Confirm with BTL protocol" },
      { q: "Is there any downtime?", a: "No. You can drive yourself home and go back to work. Some people feel mild muscle soreness the next day, like after training." },
      { q: "How is this different from Emsculpt?", a: "Emsculpt Neo adds radiofrequency to the original Emsculpt's muscle contractions, so it works on fat as well as muscle in the same session." },
    ],
    related: ["exion-body", "emsella", "kybella"],
    image: { slot: "emsculpt-neo", alt: "Emsculpt Neo treatment at Olivo Med Spa", fallback: "room-1" },
    live: "/emsculpt/",
    seo: { title: "Emsculpt Neo in Logan Square, Chicago | Olivo Med Spa", description: "Emsculpt Neo at Olivo Med Spa builds muscle and reduces fat in one 30-minute session, no downtime. Physician-led since 2013. Book a consultation on Fullerton Ave." },
    es: { name: "Emsculpt Neo", summary: "Desarrolla músculo y reduce grasa en la misma sesión de 30 minutos, sin cirugía." },
  },
  {
    slug: "exion-body",
    name: "Exion for body",
    category: "body-contouring",
    brand: "BTL",
    tag: "Body · Minimal downtime",
    headline: "Tightens skin on the body with radiofrequency and targeted ultrasound, no surgery.",
    summary: "Exion for body uses monopolar radiofrequency with targeted ultrasound to heat the deeper layers of skin and support collagen. A series of short sessions with minimal downtime, at a physician-led clinic in Logan Square.",
    intro: [
      "Exion for body is the skin answer in the BTL platform. Where Emsculpt Neo works on muscle and fat, Exion works on the skin over them. The applicator delivers radiofrequency and targeted ultrasound together to warm the deeper layers of skin, which supports collagen and elastin over time. Common areas are the abdomen, arms, thighs, knees, and buttocks.",
      "A plan is usually a short series of sessions, spaced a few weeks apart. Each session takes about thirty minutes depending on the area. The treatment feels like deep warmth. There is little to no downtime, and most people return to their day right after.",
      "Dr. Olivo often pairs Exion with Emsculpt Neo when someone wants both tone and tighter skin. Candidacy and expectations are set at a consultation, not from a menu.",
    ],
    benefits: ["Radiofrequency and ultrasound in one applicator", "Skin tightening on abdomen, arms, thighs, and more", "No needles or anesthesia", "Minimal downtime", "Pairs with Emsculpt Neo"],
    concerns: ["sagging-skin", "skin-texture-scars"],
    session: { duration: "About 30 minutes per area", sessions: "A series of sessions, spaced a few weeks apart", downtime: "Minimal", feels: "Deep, steady warmth over the treated area", results: "Most people notice gradual change over the months after the series as collagen builds", verify: "Session count, spacing, duration, and timing of change: confirm with BTL Exion protocol" },
    goodFor: ["Adults with mild to moderate skin laxity on the body", "People who want tighter skin after weight change or pregnancy", "Anyone cleared at consultation, where Dr. Olivo confirms candidacy"],
    faqs: [
      { q: "What does Exion feel like?", a: "Warmth that builds during the session. The applicator moves over the area and the temperature is monitored throughout. Most people describe it as comfortable." },
      { q: "How is Exion different from Emsculpt Neo?", a: "Emsculpt Neo works on muscle and fat. Exion works on skin quality and tightness. Many plans use both, and Dr. Olivo decides the order at consultation." },
      { q: "How many sessions will I need?", a: "That depends on the area and your skin. A series of several sessions is typical. Your plan is set at consultation.", verify: "Confirm session count with BTL protocol" },
      { q: "Is there downtime?", a: "Little to none. The area may look pink or feel warm for a short while afterward. You can go back to work the same day." },
    ],
    related: ["emsculpt-neo", "exion-face", "emface"],
    image: { slot: "exion-body", alt: "Exion body skin tightening treatment at Olivo Med Spa", fallback: "room-2" },
    live: "/the-best-exion-chicago-provider-spa/",
    seo: { title: "Exion Body Skin Tightening in Chicago | Olivo Med Spa", description: "Exion for body at Olivo Med Spa in Logan Square uses radiofrequency and ultrasound to tighten skin on the abdomen, arms, and thighs. Book a consultation." },
    es: { name: "Exion para el cuerpo", summary: "Reafirma la piel del cuerpo con radiofrecuencia y ultrasonido dirigido, sin cirugía." },
    verify: ["Exion body protocol, session count, and treatment areas: confirm with clinic and BTL materials", "Who performs Exion body sessions: confirm with clinic"],
  },
  {
    slug: "emsella",
    name: "Emsella",
    category: "wellness",
    brand: "BTL",
    tag: "Pelvic floor · Fully clothed",
    headline: "Strengthens the pelvic floor muscles while you sit, fully clothed, in about 28 minutes.",
    summary: "Emsella is a chair that uses electromagnetic energy to contract the pelvic floor muscles thousands of times in one session. It supports people managing urinary incontinence. You stay fully clothed. Physician-led in Logan Square.",
    intro: [
      "Emsella is a chair. You sit on it, fully clothed, and it delivers electromagnetic pulses that contract the pelvic floor muscles far more times than you could on your own. Each session lasts about 28 minutes. There is nothing to undress for and nothing internal.",
      "A weak pelvic floor is common after childbirth, with age, and after certain surgeries, and it often shows up as urinary leakage with a cough, a laugh, or a run. Emsella is used to strengthen those muscles as part of a plan for urinary incontinence support.",
      "A typical series is six sessions over about three weeks. Dr. Olivo reviews your history at a consultation and confirms whether Emsella is appropriate for you. Candidacy and expectations are set there.",
    ],
    benefits: ["Pelvic floor muscle strengthening without exercise", "Fully clothed, seated, about 28 minutes", "No downtime", "Support for urinary incontinence", "Pairs with Emfemme 360"],
    concerns: ["pelvic-floor"],
    session: { duration: "About 28 minutes", sessions: "Typically six sessions over about three weeks", downtime: "None", feels: "Tingling and strong contractions of the pelvic floor while seated", results: "Many people report change over the course of the series and in the weeks after", verify: "Session count, spacing, 28-minute length, and timing of change: confirm with BTL Emsella materials" },
    goodFor: ["Adults with urinary leakage linked to a weak pelvic floor", "Women after childbirth or during menopause", "Anyone cleared at consultation, including no metal or electronic implants in the area"],
    faqs: [
      { q: "Do I need to undress?", a: "No. You sit on the chair in your regular clothes. Nothing is inserted and nothing touches the skin directly." },
      { q: "What does it feel like?", a: "Tingling and strong pelvic floor contractions. It is not painful. Intensity is adjusted to you during the session." },
      { q: "How many sessions?", a: "A common series is six sessions, two a week for about three weeks. Dr. Olivo sets your plan at consultation.", verify: "Confirm with BTL Emsella protocol" },
      { q: "Can men use Emsella?", a: "Emsella is used for men and women with pelvic floor weakness. Candidacy is confirmed at consultation.", verify: "Confirm cleared indication wording for male patients with BTL labeling" },
    ],
    related: ["emfemme-360", "emsculpt-neo", "hormone-therapy"],
    image: { slot: "emsella", alt: "Emsella pelvic floor chair at Olivo Med Spa", fallback: "room-3" },
    live: "/services/emsella/",
    seo: { title: "Emsella Pelvic Floor Chair in Chicago | Olivo Med Spa", description: "Emsella at Olivo Med Spa in Logan Square strengthens the pelvic floor muscles while you sit, fully clothed, for 28 minutes. Support for urinary incontinence." },
    es: { name: "Emsella", summary: "Fortalece los músculos del suelo pélvico mientras está sentada y vestida, en unos 28 minutos." },
    verify: ["Urinary incontinence wording: keep to cleared indication per BTL labeling", "28-minute session and fully clothed claim: confirm with BTL materials", "Who supervises Emsella sessions: confirm with clinic"],
  },
  {
    slug: "kybella",
    name: "Kybella",
    category: "injectables",
    brand: "Allergan",
    tag: "Injectable · Under the chin",
    headline: "Injections that break down fat under the chin, so the profile sharpens without surgery.",
    summary: "Kybella is an injectable made of deoxycholic acid, a molecule that helps the body break down fat. Dr. Olivo uses it for fullness under the chin. A few short sessions, spaced about a month apart, in Logan Square.",
    intro: [
      "Fullness under the chin does not always respond to diet or exercise. Kybella is an injectable treatment for it. The active ingredient is deoxycholic acid, which occurs naturally in the body and helps break down dietary fat. Injected into the fat under the chin, it breaks down fat cells in that area, and the body clears them over the following weeks.",
      "A session takes about twenty minutes. Most people need more than one, spaced about a month apart, and the number depends on how much fullness there is to treat. Swelling afterward is expected and can last a week or more. That is part of how it works.",
      "Dr. Olivo maps the treatment area at your consultation, where candidacy and expectations are set. If loose skin is the larger issue, she may point you to a different option.",
    ],
    benefits: ["Targets fat under the chin without surgery", "About twenty minutes per session", "No incisions or general anesthesia", "Results build over a few sessions", "Physician-led assessment first"],
    concerns: ["double-chin"],
    session: { duration: "About 20 minutes", sessions: "Two to four sessions, about a month apart", downtime: "A few days", feels: "Small injections with stinging, then a warm, tight sensation as the area swells", results: "Change is usually visible after two or more sessions as the body clears treated fat", verify: "Session count, spacing, and timing of change: confirm with Kybella prescribing information" },
    goodFor: ["Adults with moderate fullness under the chin", "People who want a sharper jaw and neck line without surgery", "Anyone cleared at consultation, where skin laxity and anatomy are reviewed"],
    faqs: [
      { q: "Does Kybella hurt?", a: "You feel the injections and then a stinging or burning that settles within minutes. Numbing cream and ice help. Swelling and tenderness follow for several days." },
      { q: "How much swelling should I expect?", a: "Noticeable swelling for about a week is normal, sometimes longer after the first session. Plan around events. It fades on its own." },
      { q: "How many sessions?", a: "Most people need two to four, spaced about a month apart. The number depends on how much fullness is present.", verify: "Confirm with Kybella prescribing information" },
      { q: "What about loose skin under the chin?", a: "Kybella treats fat, not skin. If laxity is the main issue, Dr. Olivo may suggest Exion or Emface instead, or a combination." },
    ],
    related: ["exion-face", "emface", "dermal-fillers"],
    image: { slot: "kybella", alt: "Kybella injection consultation at Olivo Med Spa", fallback: "hands-1" },
    live: "/kybella/",
    seo: { title: "Kybella for Under the Chin in Chicago | Olivo Med Spa", description: "Kybella at Olivo Med Spa in Logan Square uses deoxycholic acid injections to reduce fullness under the chin without surgery. Physician-led since 2013." },
    es: { name: "Kybella", summary: "Inyecciones de ácido desoxicólico para reducir la grasa debajo del mentón sin cirugía." },
    verify: ["Who performs Kybella injections: confirm with clinic", "Session count and spacing: confirm with Kybella prescribing information"],
  },
  {
    slug: "laser-lipo",
    name: "Laser lipo",
    category: "body-contouring",
    tag: "Body · No downtime",
    headline: "Low-level laser sessions aimed at stubborn areas, with no needles and no downtime.",
    summary: "Laser lipo uses low-level laser light applied to the skin over areas like the abdomen, flanks, or thighs. Sessions are short and comfortable, and there is no recovery. A conservative option reviewed at consultation in Logan Square.",
    intro: [
      "Laser lipo is a non-invasive session in which pads or paddles emitting low-level laser light are placed over the treatment area. The light is applied to the skin for a set time. Nothing pierces the skin and there is no heat you would notice. Sessions are usually scheduled as a series.",
      "It is a gentle option. It does not remove fat the way surgery does, and it is not a substitute for weight loss. People who choose it tend to want a modest change in a specific area and value a treatment with no recovery.",
      "Dr. Olivo reviews whether laser lipo, Emsculpt Neo, or another plan fits your goal at a consultation, where candidacy and expectations are set.",
    ],
    benefits: ["Non-invasive, applied to the skin", "Short sessions, no downtime", "Comfortable, with no heat or needles", "Often paired with Emsculpt Neo", "Plan set at consultation"],
    concerns: ["stubborn-fat"],
    session: { duration: "About 20 to 40 minutes", sessions: "A series of sessions over several weeks", downtime: "None", feels: "Little to nothing; the pads rest on the skin", results: "Any change is gradual and modest, and depends on the series and your habits", verify: "Device name, session length, series count, and expected outcome: confirm with clinic" },
    goodFor: ["Adults near their goal weight with a small, specific area", "People who want a no-downtime option", "Anyone cleared at consultation"],
    faqs: [
      { q: "Is laser lipo the same as liposuction?", a: "No. Liposuction is surgery that removes fat. Laser lipo is a non-invasive light treatment applied to the skin. Expectations are different and Dr. Olivo will explain them." },
      { q: "Does it hurt?", a: "No. Most people feel little or nothing. You lie still while the pads rest on the area." },
      { q: "How many sessions?", a: "It is offered as a series. The number and schedule are set at consultation based on your area and goal.", verify: "Confirm series count and schedule with clinic" },
      { q: "Should I choose laser lipo or Emsculpt Neo?", a: "They do different things. Emsculpt Neo builds muscle and reduces fat with stronger energy. Laser lipo is gentler. Dr. Olivo recommends one or both based on your goal." },
    ],
    related: ["emsculpt-neo", "exion-body", "glp-1-weight-management"],
    image: { slot: "laser-lipo", alt: "Laser lipo body contouring session at Olivo Med Spa", fallback: "light-1" },
    live: "/laser-lipo/",
    seo: { title: "Laser Lipo in Logan Square, Chicago | Olivo Med Spa", description: "Laser lipo at Olivo Med Spa in Logan Square: non-invasive low-level laser sessions for stubborn areas, no needles and no downtime. Physician-led since 2013." },
    es: { name: "Lipo láser", summary: "Sesiones de láser de baja intensidad, no invasivas, para zonas localizadas, sin agujas ni recuperación." },
    verify: ["Device name to be confirmed by the clinic", "Session length, series count, and treatment areas: confirm with clinic", "Who performs laser lipo sessions: confirm with clinic"],
  },
  {
    slug: "miradry",
    name: "Miradry",
    category: "sweat",
    brand: "Miradry",
    tag: "Underarms · Minimal downtime",
    headline: "Lasting reduction of underarm sweat and odor, usually in one or two sessions.",
    summary: "Miradry uses controlled microwave energy to target the sweat and odor glands in the underarm. Most people need one or two sessions. A physician-led option in Logan Square for people done with heavy underarm sweating.",
    intro: [
      "Underarm sweat is a daily problem for a lot of people, and antiperspirants only go so far. Miradry takes a different approach. A handpiece delivers microwave energy to the layer of skin where sweat and odor glands sit, while cooling protects the surface. Treated glands do not grow back, which is why the reduction lasts.",
      "The underarm is numbed first. A session takes about an hour. Most people need one or two sessions, and the second, if needed, is scheduled about three months later. Swelling, soreness, and numbness in the area are normal for a few days to a few weeks.",
      "Miradry is for the underarms only. Dr. Olivo reviews your history and sweat pattern at a consultation, where candidacy and expectations are set.",
    ],
    benefits: ["Lasting reduction of underarm sweat and odor", "Usually one or two sessions", "Non-surgical, with local numbing", "No ongoing injections or prescriptions", "Back to most activity within days"],
    concerns: ["excessive-sweating"],
    session: { duration: "About 60 minutes", sessions: "One or two sessions, about three months apart", downtime: "Minimal", feels: "Pressure and suction after numbing; soreness and swelling for a few days afterward", results: "Many people notice less sweat soon after the first session, with the full effect over the following weeks", verify: "Session count, spacing, and timing of change: confirm with Miradry manufacturer materials" },
    goodFor: ["Adults bothered by underarm sweat or odor", "People who want an alternative to repeated injections", "Anyone cleared at consultation"],
    faqs: [
      { q: "How long does the reduction last?", a: "Treated sweat glands are eliminated and do not regenerate, so the reduction is lasting. Some people choose a second session to reach the level they want.", verify: "Lasting reduction and gland claim: confirm with Miradry labeling" },
      { q: "Does it hurt?", a: "The underarm is numbed with local anesthetic, so the treatment itself is tolerable. Afterward expect soreness, swelling, and some numbness for days to weeks." },
      { q: "Do I need my underarm sweat glands?", a: "The underarms hold a small share of the body's sweat glands, so the body keeps regulating temperature normally.", verify: "Sweat gland share statement: confirm with Miradry materials" },
      { q: "How soon can I go back to work?", a: "Most people return to work the next day. Plan a few days away from heavy exercise while swelling settles.", verify: "Recovery guidance: confirm with clinic aftercare protocol" },
    ],
    related: ["for-men", "emsculpt-neo", "botox-and-xeomin"],
    image: { slot: "miradry", alt: "Miradry underarm treatment at Olivo Med Spa", fallback: "steel-1" },
    live: "/miradry/",
    seo: { title: "Miradry Sweat Treatment in Chicago | Olivo Med Spa", description: "Miradry at Olivo Med Spa in Logan Square uses microwave energy for lasting reduction of underarm sweat and odor, usually in one or two sessions." },
    es: { name: "Miradry", summary: "Reducción duradera del sudor y el olor de las axilas con energía de microondas, normalmente en una o dos sesiones." },
    verify: ["'Lasting reduction' claim: confirm with Miradry manufacturer labeling", "Session count, length, and spacing: confirm with clinic protocol", "Who performs Miradry: confirm with clinic"],
  },
];
