// Facial lifting and injectables. See docs/CONTENT-RULES.md before editing.
import type { Service } from "../types";

export const faceServices: Service[] = [
  {
    slug: "emface",
    name: "Emface",
    category: "facial-lifting",
    brand: "BTL",
    tag: "Face · No downtime",
    headline: "Lifts and tones the face with synchronized radiofrequency and muscle stimulation, no needles.",
    summary: "Emface applies radiofrequency and facial muscle stimulation at the same time to work on skin and the lifting muscles beneath it. Twenty minutes, four sessions, no needles, no downtime. Physician-led in Logan Square.",
    intro: [
      "Emface is the facial treatment in the BTL family that works on muscle as well as skin. Small pads sit on the forehead and cheeks. They deliver synchronized radiofrequency, which warms the skin and supports collagen, and electrical stimulation that contracts the facial muscles that lift. Nothing pierces the skin.",
      "A session lasts about twenty minutes. A standard plan is four sessions, spaced about a week apart. You feel warmth and a fluttering pull as the muscles contract. You can put makeup on and go straight back to your day.",
      "Emface suits people who want a lifted, rested look without injectables, or who want to support the results they already have. Candidacy and expectations are set at a consultation with Dr. Olivo.",
    ],
    benefits: ["Skin and lifting muscles treated together", "Needle-free, about twenty minutes", "Four sessions, no downtime", "Forehead, cheeks, and jawline", "Pairs with injectables or Exion"],
    concerns: ["sagging-skin", "fine-lines-wrinkles"],
    session: { duration: "About 20 minutes", sessions: "Four sessions, about a week apart", downtime: "None", feels: "Warmth with a rhythmic pull as the facial muscles contract", results: "Most people notice change over the weeks after the series as collagen builds and muscle tone improves", verify: "Session count, spacing, and timing of change: confirm with BTL Emface materials" },
    goodFor: ["Adults noticing early sagging or a tired look", "People who prefer a needle-free option", "Anyone cleared at consultation, including no metal or electronic implants in the area"],
    faqs: [
      { q: "Does Emface replace Botox Cosmetic or fillers?", a: "No. It works differently, on skin quality and muscle tone. Many people combine them. Dr. Olivo will tell you what fits your face." },
      { q: "Does it hurt?", a: "No. You feel warmth and muscle contractions. Intensity is adjusted to you." },
      { q: "How many sessions?", a: "Four, about a week apart, is standard. Some people return for maintenance later.", verify: "Confirm with BTL Emface protocol" },
      { q: "Is there any downtime?", a: "None. Skin may look slightly flushed for a short time. You can apply makeup right after." },
    ],
    related: ["exion-face", "botox-and-xeomin", "pdo-threads"],
    image: { slot: "emface", alt: "Emface facial treatment at Olivo Med Spa", fallback: "skin-1" },
    live: "/services/emface/",
    seo: { title: "Emface in Logan Square, Chicago | Olivo Med Spa", description: "Emface at Olivo Med Spa in Logan Square lifts and tones the face with synchronized radiofrequency and muscle stimulation. 20 minutes, no needles, no downtime." },
    es: { name: "Emface", summary: "Tonifica y eleva el rostro con radiofrecuencia y estimulación muscular sincronizadas, sin agujas." },
    verify: ["Emface treatment areas (including jawline) and claim wording: confirm with BTL materials", "Who performs Emface sessions: confirm with clinic"],
  },
  {
    slug: "exion-face",
    name: "Exion for face",
    category: "facial-lifting",
    brand: "BTL",
    tag: "Face · Minimal downtime",
    headline: "Radiofrequency and ultrasound for firmer, smoother facial skin, with no needles.",
    summary: "Exion for face pairs monopolar radiofrequency with targeted ultrasound to heat the deeper skin and support collagen, elastin, and hydration. A short series, minimal downtime, no needles. Physician-led in Logan Square.",
    intro: [
      "Exion for face is the needle-free arm of the Exion platform. A smooth applicator glides over the face and neck, delivering radiofrequency and targeted ultrasound together. The energy warms the deeper skin, which supports collagen and elastin and encourages the skin to hold more moisture. Treatment areas include the cheeks, jawline, under the eyes, and neck.",
      "Sessions take about thirty minutes and are spaced a few weeks apart. The treatment feels like a warm massage. Skin may look pink for a short time afterward, and most people go straight back to their day.",
      "For deeper texture work, the same platform offers Exion RF microneedling. Dr. Olivo decides which is right for you at a consultation, where candidacy and expectations are set.",
    ],
    benefits: ["Radiofrequency and ultrasound, no needles", "Firmer skin on face, jawline, and neck", "About thirty minutes", "Minimal downtime", "Pairs with Emface and injectables"],
    concerns: ["sagging-skin", "fine-lines-wrinkles", "dull-tired-skin"],
    session: { duration: "About 30 minutes", sessions: "A series of sessions, spaced a few weeks apart", downtime: "Minimal", feels: "Steady warmth, like a heated facial massage", results: "Most people notice gradual firmness and glow over the months after the series", verify: "Session count, spacing, and timing of change: confirm with BTL Exion protocol" },
    goodFor: ["Adults with early laxity or dull, dehydrated skin", "People who want a needle-free step before or between injectables", "Anyone cleared at consultation"],
    faqs: [
      { q: "Is Exion the same as microneedling?", a: "This page is the needle-free Exion treatment. The platform also offers Exion RF microneedling, which uses fine needles for deeper texture. Dr. Olivo recommends one based on your skin." },
      { q: "Does it hurt?", a: "No. It feels warm. Temperature is monitored so it stays comfortable." },
      { q: "How many sessions?", a: "Several sessions, a few weeks apart, is typical. Your plan is set at consultation.", verify: "Confirm with BTL Exion protocol" },
      { q: "Can I wear makeup afterward?", a: "Yes, usually the same day. Skin may be slightly pink for a short time." },
    ],
    related: ["emface", "exion-body", "radiesse"],
    image: { slot: "exion-face", alt: "Exion face treatment at Olivo Med Spa", fallback: "skin-2" },
    live: "/services/the-best-exion-chicago-provider-spa/",
    seo: { title: "Exion Face Treatment in Chicago | Olivo Med Spa", description: "Exion for face at Olivo Med Spa in Logan Square uses radiofrequency and ultrasound to firm and smooth facial skin with no needles and minimal downtime." },
    es: { name: "Exion para el rostro", summary: "Radiofrecuencia y ultrasonido para una piel facial más firme y suave, sin agujas." },
    verify: ["Exion face protocol and treatment areas: confirm with BTL materials", "Who performs Exion face sessions: confirm with clinic"],
  },
  {
    slug: "pdo-threads",
    name: "PDO threads",
    category: "facial-lifting",
    tag: "Face · A few days",
    headline: "Absorbable threads placed under the skin to lift and support, without surgery.",
    summary: "PDO threads are fine absorbable sutures placed under the skin to lift sagging areas and stimulate collagen as they dissolve. A single visit with a few days of recovery, performed at a physician-led clinic in Logan Square.",
    intro: [
      "PDO threads are made of polydioxanone, the same material used in absorbable surgical sutures. Placed under the skin with a fine cannula, they provide immediate mechanical support to areas that have started to drop, such as the cheeks, jawline, jowls, brows, and neck. As the threads dissolve over months, the skin builds collagen along their path.",
      "The visit takes about an hour including numbing. Expect some swelling, bruising, and tightness for a few days, and a feeling of pulling for a week or two. Results are visible right away and settle in over the following weeks.",
      "Threads are one option among several. Dr. Olivo compares them with Emface, Exion, and fillers at a consultation, where candidacy and expectations are set.",
    ],
    benefits: ["Immediate lift in the treated area", "Collagen support as threads dissolve", "Single visit, no incisions", "Cheeks, jawline, brows, and neck", "Combines with fillers or Emface"],
    concerns: ["sagging-skin", "volume-loss"],
    session: { duration: "About 60 minutes including numbing", sessions: "Single session; some people repeat after a year or more", downtime: "A few days", feels: "Pressure and pulling after numbing; tenderness and tightness for several days", results: "Lift is visible right away; the collagen effect develops over the following months", verify: "Thread type, longevity, and timing of change: confirm with clinic and thread manufacturer" },
    goodFor: ["Adults with mild to moderate sagging in the lower face or brows", "People who want a lift without surgery", "Anyone cleared at consultation, where skin thickness and goals are reviewed"],
    faqs: [
      { q: "How long do PDO threads last?", a: "The threads themselves dissolve over about six months. The collagen they stimulate can keep supporting the area for longer. Timing varies by person.", verify: "Dissolution timeframe: confirm with thread manufacturer" },
      { q: "Does it hurt?", a: "The area is numbed first. You feel pressure and pulling. Tenderness afterward is managed with over-the-counter pain relief." },
      { q: "What should I avoid afterward?", a: "Wide mouth movements, sleeping on your face, facials, and heavy exercise for about two weeks. You get written aftercare.", verify: "Aftercare guidance: confirm with clinic protocol" },
      { q: "Threads or filler?", a: "Threads lift. Filler adds volume. Many faces need a bit of both, and Dr. Olivo will show you where each helps." },
    ],
    related: ["emface", "dermal-fillers", "radiesse"],
    image: { slot: "pdo-threads", alt: "PDO thread consultation at Olivo Med Spa", fallback: "hands-1" },
    live: "/services/pdo-threads/",
    seo: { title: "PDO Threads in Logan Square, Chicago | Olivo Med Spa", description: "PDO threads at Olivo Med Spa in Logan Square lift and support the cheeks, jawline, and neck with absorbable sutures, no surgery. Physician-led since 2013." },
    es: { name: "Hilos PDO", summary: "Suturas absorbibles colocadas bajo la piel para elevar y sostener el rostro, sin cirugía." },
    verify: ["Thread brand and type: confirm with clinic", "Who performs thread placement: confirm with clinic", "Treatment areas offered: confirm with clinic"],
  },
  {
    slug: "radiesse",
    name: "Radiesse",
    category: "injectables",
    brand: "Merz",
    tag: "Injectable · Volume and structure",
    headline: "A calcium hydroxylapatite filler that restores structure and stimulates collagen over time.",
    summary: "Radiesse is a filler made of calcium hydroxylapatite microspheres in a gel. It adds lift and definition to the cheeks, jawline, and hands, and encourages collagen as it settles. Physician-led injectables in Logan Square.",
    intro: [
      "Radiesse is different from hyaluronic acid fillers. Its calcium hydroxylapatite microspheres give firmer, more structural support, which suits the cheekbones, jawline, chin, and the backs of the hands. As the gel is absorbed, the microspheres remain for a time and prompt the skin to build its own collagen.",
      "A visit takes about thirty minutes. Mild swelling or bruising can follow for a few days. Results are visible right away and typically last a year or more, depending on the area and the person.",
      "Radiesse can also be diluted and used to improve skin quality across broader areas such as the neck. Dr. Olivo decides the product and technique at a consultation, where candidacy and expectations are set.",
    ],
    benefits: ["Structure for cheeks, jawline, and chin", "Also used on the backs of the hands", "Stimulates collagen as it settles", "About thirty minutes", "Results that typically last a year or more"],
    concerns: ["volume-loss", "sagging-skin"],
    session: { duration: "About 30 minutes", sessions: "Single session; touch-up as needed", downtime: "Minimal", feels: "Brief pinches with pressure; lidocaine in the product eases discomfort", results: "Visible immediately, with collagen effect building over the following months", verify: "Longevity, lidocaine formulation, and timing: confirm with Radiesse prescribing information" },
    goodFor: ["Adults with volume loss in the mid or lower face", "People who want jawline or chin definition", "Anyone cleared at consultation"],
    faqs: [
      { q: "How is Radiesse different from hyaluronic acid filler?", a: "Radiesse is firmer and more structural, and it stimulates collagen. It cannot be dissolved the way hyaluronic acid fillers can, so placement is planned carefully." },
      { q: "How long does it last?", a: "Typically a year or more, depending on the area, the amount, and how quickly your body metabolizes it.", verify: "Confirm duration wording with Radiesse prescribing information" },
      { q: "Can it be used in the lips?", a: "No. Radiesse is not used in the lips. Hyaluronic acid fillers like Revanesse Versa are the choice there." },
      { q: "Is there downtime?", a: "Minimal. Swelling and possible bruising settle over a few days. Most people return to normal activity right away." },
    ],
    related: ["dermal-fillers", "pdo-threads", "emface"],
    image: { slot: "radiesse", alt: "Radiesse filler consultation at Olivo Med Spa", fallback: "hands-1" },
    live: "/services/injectables-dermal-fillers/radiesse/",
    seo: { title: "Radiesse Filler in Logan Square, Chicago | Olivo Med Spa", description: "Radiesse at Olivo Med Spa in Logan Square adds structure to the cheeks, jawline, chin, and hands and stimulates collagen over time. Physician-led since 2013." },
    es: { name: "Radiesse", summary: "Relleno de hidroxiapatita cálcica que aporta estructura y estimula el colágeno con el tiempo." },
    verify: ["Who injects Radiesse: confirm with clinic", "Diluted Radiesse use on neck and other areas: confirm with clinic and remove if not offered", "Duration claim: confirm with Radiesse prescribing information"],
  },
  {
    slug: "botox-and-xeomin",
    name: "Botox Cosmetic and Xeomin",
    category: "injectables",
    tag: "Injectable · Lines of expression",
    headline: "Neuromodulators that soften lines of expression on the forehead, between the brows, and around the eyes.",
    summary: "Botox Cosmetic and Xeomin are neuromodulators that relax the small muscles behind frown lines, forehead lines, and crow's feet. A short visit, results in about a week, lasting three to four months. Physician-led in Logan Square.",
    intro: [
      "Lines of expression come from muscles that repeat the same movement for years. Botox Cosmetic and Xeomin work by relaxing those muscles for a few months, so the skin over them rests. The clinic carries both. They contain the same active protein; Xeomin is formulated without accessory proteins, which some people prefer.",
      "A visit takes about ten to fifteen minutes. You feel a few small pinches. Change begins within days and settles in about two weeks. Most people repeat every three to four months. Common areas are the forehead, the lines between the brows, and crow's feet. Other areas are discussed case by case.",
      "The goal is a rested version of your face, not a frozen one. Dose and placement are decided at a consultation, where candidacy and expectations are set.",
    ],
    benefits: ["Softens frown lines, forehead lines, crow's feet", "About ten to fifteen minutes", "No downtime", "Botox Cosmetic and Xeomin both available", "Natural movement is the aim"],
    concerns: ["fine-lines-wrinkles"],
    session: { duration: "About 10 to 15 minutes", sessions: "Repeat every three to four months", downtime: "None", feels: "A few small pinches", results: "Change begins within a few days and settles by about two weeks", verify: "Onset and duration: confirm with Botox Cosmetic and Xeomin prescribing information" },
    goodFor: ["Adults with lines that show at rest or with expression", "People who want a preventive, light-touch approach", "Anyone cleared at consultation, including no relevant neuromuscular conditions"],
    faqs: [
      { q: "Botox Cosmetic or Xeomin, which should I choose?", a: "Both relax the treated muscle in a similar way. Xeomin has no accessory proteins. Dr. Olivo will recommend one based on your history and preference.", verify: "Confirm product comparison wording with manufacturer materials" },
      { q: "Will I look frozen?", a: "Not if that is not the goal. Dose and placement are conservative and adjusted to your expressions." },
      { q: "How long does it last?", a: "Typically three to four months. Some people find it lasts longer with regular treatment.", verify: "Confirm duration with prescribing information" },
      { q: "Can I work out afterward?", a: "Wait until the next day for exercise, and avoid rubbing the area or lying flat for about four hours.", verify: "Aftercare guidance: confirm with clinic protocol" },
    ],
    related: ["dermal-fillers", "emface", "miradry"],
    image: { slot: "botox-and-xeomin", alt: "Neuromodulator treatment at Olivo Med Spa", fallback: "hands-1" },
    live: "/services/injectables-dermal-fillers/",
    seo: { title: "Botox Cosmetic and Xeomin in Chicago | Olivo Med Spa", description: "Botox Cosmetic and Xeomin at Olivo Med Spa in Logan Square soften frown lines, forehead lines, and crow's feet in a short visit with no downtime." },
    es: { name: "Botox Cosmetic y Xeomin", summary: "Neuromoduladores que suavizan las líneas de expresión de la frente, el entrecejo y el contorno de los ojos." },
    verify: ["Xeomin is also listed on the live site under /skincare-products/xeomin/; consolidate into this page in the 301 map", "Who injects neuromodulators: confirm with clinic", "Treatment areas offered beyond the upper face: confirm with clinic"],
  },
  {
    slug: "dermal-fillers",
    name: "Dermal fillers",
    category: "injectables",
    tag: "Injectable · Volume and contour",
    headline: "Hyaluronic acid fillers for lips, cheeks, and contour, placed with a light hand.",
    summary: "Dermal fillers restore volume and shape with hyaluronic acid, a substance the skin makes on its own. The clinic uses Revanesse Versa and Belotero for lips, cheeks, under-eye hollows, and fine lines. Physician-led in Logan Square.",
    intro: [
      "Hyaluronic acid fillers are smooth gels that add volume where the face has lost it and shape where you want more definition. The clinic carries Revanesse Versa and Belotero. Each has a different texture, so the product is matched to the area: fuller gels for cheeks and jawline, softer ones for lips and fine lines.",
      "A visit takes about thirty to forty-five minutes with numbing. Results are visible right away, with mild swelling for a few days. Depending on the product and area, results typically last six to eighteen months. Hyaluronic acid fillers can be dissolved if needed.",
      "Good filler is invisible. Dr. Olivo plans placement around your anatomy at a consultation, where candidacy and expectations are set.",
    ],
    benefits: ["Lips, cheeks, under-eyes, jawline, and fine lines", "Revanesse Versa and Belotero", "Results visible right away", "Reversible if needed", "About thirty to forty-five minutes"],
    concerns: ["volume-loss", "fine-lines-wrinkles"],
    session: { duration: "About 30 to 45 minutes", sessions: "Single session; repeat as results fade", downtime: "Minimal", feels: "Small pinches and pressure after numbing", results: "Visible immediately; swelling settles over a few days", verify: "Duration range and product-specific claims: confirm with Revanesse Versa and Belotero prescribing information" },
    goodFor: ["Adults with volume loss in the cheeks, lips, or under-eyes", "People who want contour without surgery", "Anyone cleared at consultation"],
    faqs: [
      { q: "Will it look overdone?", a: "Not with conservative amounts and careful placement. The plan is built around your face and you can add more later." },
      { q: "How long do fillers last?", a: "Six to eighteen months depending on the product, the area, and how your body metabolizes it.", verify: "Confirm duration range with prescribing information" },
      { q: "Can filler be reversed?", a: "Yes. Hyaluronic acid fillers can be dissolved with an enzyme if needed." },
      { q: "Does it hurt?", a: "Numbing cream and lidocaine in the product keep it tolerable. You feel pressure and small pinches." },
    ],
    related: ["revanesse-versa", "radiesse", "botox-and-xeomin", "pdo-threads"],
    image: { slot: "dermal-fillers", alt: "Dermal filler treatment at Olivo Med Spa", fallback: "portrait" },
    live: "/services/injectables-dermal-fillers/",
    seo: { title: "Dermal Fillers in Logan Square, Chicago | Olivo Med Spa", description: "Dermal fillers at Olivo Med Spa in Logan Square: Revanesse Versa and Belotero for lips, cheeks, under-eyes, and contour, placed by a physician-led team." },
    es: { name: "Rellenos dérmicos", summary: "Rellenos de ácido hialurónico para labios, mejillas y contorno, aplicados con mano ligera." },
    verify: ["Who injects fillers: confirm with clinic", "Product list and treatment areas: confirm with clinic", "Duration range: confirm with prescribing information"],
  },
  {
    slug: "revanesse-versa",
    name: "Revanesse Versa",
    category: "injectables",
    brand: "Prollenium",
    tag: "Injectable · Hyaluronic acid",
    headline: "A hyaluronic acid filler line chosen for smooth results and a comfortable recovery.",
    summary: "Revanesse Versa is a hyaluronic acid filler line the clinic uses for lips, cheeks, and lines around the nose and mouth. It is formulated for smooth, even results with a comfortable recovery. Physician-led injectables in Logan Square.",
    intro: [
      "Revanesse Versa is a line of hyaluronic acid fillers made with a refined manufacturing process that produces uniform, spherical particles. In practice that means a smooth gel that integrates well and a recovery many people find gentler. It is a frequent choice at the clinic for lips, nasolabial folds, and cheeks.",
      "A visit takes about thirty minutes with numbing, and results are visible immediately. Mild swelling settles over a few days. Results typically last around a year depending on the area. Like other hyaluronic acid fillers, it can be dissolved if needed.",
      "Product choice is part of the plan, not the starting point. Dr. Olivo selects Revanesse Versa or Belotero for each area at a consultation, where candidacy and expectations are set.",
    ],
    benefits: ["Hyaluronic acid filler for lips, cheeks, and folds", "Smooth gel designed to integrate evenly", "Results visible right away", "Reversible if needed", "About thirty minutes"],
    concerns: ["volume-loss", "fine-lines-wrinkles"],
    session: { duration: "About 30 minutes", sessions: "Single session; repeat as results fade", downtime: "Minimal", feels: "Small pinches and pressure after numbing", results: "Visible immediately; final look once swelling settles in a few days", verify: "Duration and swelling claims: confirm with Revanesse Versa prescribing information and manufacturer study" },
    goodFor: ["Adults who want fuller or more defined lips", "People with volume loss in the cheeks or folds around the mouth", "Anyone cleared at consultation"],
    faqs: [
      { q: "What makes Revanesse Versa different?", a: "Its particles are made uniform and spherical, which gives a smooth gel. The manufacturer reports less swelling than some comparable fillers. Dr. Olivo will explain what that means for your area.", verify: "Manufacturer swelling comparison: cite Prollenium study or remove" },
      { q: "How long does it last?", a: "Around a year for most areas, sometimes less in the lips where movement is constant.", verify: "Confirm duration with prescribing information" },
      { q: "Is it used for lips?", a: "Yes. The line includes a formulation intended for the lip area. Other products in the line suit cheeks and folds.", verify: "Confirm which Revanesse products the clinic stocks" },
      { q: "Can it be dissolved?", a: "Yes. Like all hyaluronic acid fillers, it can be reversed with an enzyme if needed." },
    ],
    related: ["dermal-fillers", "radiesse", "botox-and-xeomin"],
    image: { slot: "revanesse-versa", alt: "Revanesse Versa filler at Olivo Med Spa", fallback: "portrait" },
    live: "/services/versa/",
    seo: { title: "Revanesse Versa Filler in Chicago | Olivo Med Spa", description: "Revanesse Versa at Olivo Med Spa in Logan Square: a smooth hyaluronic acid filler for lips, cheeks, and lines around the mouth. Physician-led since 2013." },
    es: { name: "Revanesse Versa", summary: "Una línea de rellenos de ácido hialurónico para labios, mejillas y líneas alrededor de la boca." },
    verify: ["Particle uniformity and reduced swelling claims: cite Prollenium materials or remove", "Products in the line offered by the clinic: confirm", "Who injects: confirm with clinic"],
  },
];
