// Facials, peels, and add-ons. See docs/CONTENT-RULES.md before editing.
import type { Service } from "../types";

export const facialServices: Service[] = [
  {
    slug: "hydrafacial",
    name: "Hydrafacial",
    category: "facials-and-peels",
    brand: "Hydrafacial",
    tag: "Face · No downtime",
    headline: "Cleanse, extract, and hydrate in one 30 to 45 minute visit. Skin looks fresh the same day.",
    summary: "Hydrafacial uses a vortex tip to cleanse, exfoliate, extract, and infuse serums in a single pass. About 30 to 45 minutes, no downtime, at Olivo Med Spa in Logan Square.",
    intro: [
      "Hydrafacial runs a spiral tip across the skin that exfoliates, loosens debris in the pores, vacuums it out, and delivers hydrating serums, all in one motion. There is no manual squeezing and no peeling afterward. It is the facial people book before an event because the skin looks clear and hydrated when they leave.",
      "A standard session is about thirty to forty-five minutes. Boosters can be added for brightening, firming, or calming, and it works as a monthly maintenance treatment between stronger procedures. Which boosters, how often, and whether Hydrafacial or Diamondglow suits your skin better are set at your consultation.",
    ],
    benefits: ["Cleanse, exfoliate, extract, hydrate", "About 30 to 45 minutes", "No downtime, no peeling", "Boosters for specific concerns", "Monthly maintenance option"],
    concerns: ["dull-tired-skin", "acne-breakouts", "skin-texture-scars"],
    session: { duration: "About 30 to 45 minutes", sessions: "Single session, monthly for maintenance", downtime: "None", feels: "Cool suction moving across the skin", results: "Clearer, more hydrated skin the same day", verify: "Booster menu and session length: clinic to confirm" },
    goodFor: ["Adults who want visible freshness before an event", "People with congested pores or dull skin", "Anyone cleared at consultation, including most skin types"],
    faqs: [
      { q: "Is Hydrafacial good for acne-prone skin?", a: "Often, yes. The extraction step clears congestion without squeezing, and a clarifying booster can be added. Active inflamed breakouts are assessed first and may be worked around." },
      { q: "How often should I get one?", a: "Monthly is the common rhythm for maintenance. Before an event, book it two to three days ahead so any pinkness has settled." },
      { q: "Can I add it to another treatment?", a: "Yes. It pairs well with dermaplaning, a Hydrojelly mask, or a light peel. It is also a good maintenance step between laser or plasma sessions once the skin has healed." },
    ],
    related: ["diamondglow", "glass-skin-facial", "hydrojelly-mask"],
    image: { slot: "hydrafacial", alt: "Hydrafacial treatment at Olivo Med Spa", fallback: "room-3" },
    live: "/hydrafacial/",
    seo: { title: "Hydrafacial in Logan Square, Chicago | Olivo Med Spa", description: "Hydrafacial at Olivo Med Spa in Logan Square, Chicago. Cleanse, extract, and hydrate in one 30 to 45 minute visit with no downtime. Physician-led since 2013." },
    es: { name: "Hydrafacial", summary: "Limpia, extrae e hidrata en una sola visita de 30 a 45 minutos, sin tiempo de recuperación." },
    verify: ["Hydrafacial booster options offered: clinic to confirm", "Who performs facials (aesthetician or nurse): clinic to confirm"],
  },
  {
    slug: "glass-skin-facial",
    name: "Glass skin facial",
    category: "facials-and-peels",
    tag: "Face · No downtime",
    headline: "A layered brightening and hydration facial for the smooth, reflective finish people call glass skin.",
    summary: "The Glass Skin facial layers gentle exfoliation, brightening actives, and deep hydration to leave skin smooth and luminous. No downtime, at Olivo Med Spa in Logan Square.",
    intro: [
      "Glass skin is a finish, not a product: even tone, tight pores, and a surface smooth enough to reflect light. This facial builds toward it in layers. A gentle enzyme or acid exfoliation clears dull surface cells, brightening serums address uneven tone, and a hydration step plumps the skin so light bounces evenly.",
      "It takes about an hour and there is nothing to recover from. It suits normal to dry skin well and works the week before an event. The exact protocol and product line are matched to your skin at consultation, and your provider will say if a peel or Hydrafacial would serve you better.",
    ],
    benefits: ["Brightening and hydration in layers", "Smooth, light-reflecting finish", "About an hour, no downtime", "Good before an event", "Protocol matched to your skin"],
    concerns: ["dull-tired-skin", "sun-damage-pigment", "skin-texture-scars"],
    session: { duration: "About 60 minutes", sessions: "Single session, every four to six weeks", downtime: "None", feels: "Cool, layered products with light massage", results: "A visibly brighter, more hydrated surface the same day", verify: "Glass Skin facial protocol, products, and duration: clinic to confirm" },
    goodFor: ["Adults with dull or dehydrated skin", "People preparing for photos or an event", "Anyone cleared at consultation"],
    faqs: [
      { q: "What products are used?", a: "Professional lines the clinic carries, including Alastin, ZO Skin Health, and Skinbetter Science, chosen for your skin on the day.", verify: "Confirm which lines are used in this facial" },
      { q: "Is it the same as a Hydrafacial?", a: "No. Hydrafacial is device-based and focuses on extraction and hydration. The Glass Skin facial is hands-on and layers brightening actives for tone and luminosity. Some people alternate the two." },
      { q: "How long does the glow last?", a: "The hydration and brightness are most visible for several days to a week. Repeating every four to six weeks with home care keeps it going." },
    ],
    related: ["hydrafacial", "hydrojelly-mask", "pca-chemical-peels"],
    image: { slot: "glass-skin-facial", alt: "Glass Skin facial at Olivo Med Spa", fallback: "skin-1" },
    live: "/glass-skin/",
    seo: { title: "Glass Skin Facial in Logan Square | Olivo Med Spa", description: "Glass Skin facial at Olivo Med Spa in Logan Square, Chicago. A layered brightening and hydration facial for a smooth, luminous finish with no downtime." },
    es: { name: "Facial Glass Skin", summary: "Un facial de iluminación e hidratación en capas para un acabado liso y luminoso." },
    verify: ["Glass Skin facial steps and product line: clinic to confirm"],
  },
  {
    slug: "red-out-facial",
    name: "Red Out facial",
    category: "facials-and-peels",
    tag: "Face · No downtime",
    headline: "A calming facial for skin that flushes, stings, or stays red.",
    summary: "The Red Out facial is built for redness-prone and reactive skin. Cooling, barrier-supporting steps calm the surface without acids or friction. No downtime, at Olivo Med Spa in Logan Square.",
    intro: [
      "Most facials are too much for reactive skin. The Red Out facial removes the triggers: no strong acids, no steam, no aggressive extraction. Instead it uses a gentle cleanse, cooling masks, and soothing actives that support the skin barrier. People with rosacea-type flushing or skin that stings with new products tend to leave calmer than they arrived.",
      "It runs about forty-five minutes to an hour and can be repeated monthly. For ongoing redness, Dr. Olivo may pair it with Laser Genesis or IPL. What your skin can tolerate, and whether an active flare should settle first, is confirmed at consultation before anything is booked.",
    ],
    benefits: ["No acids, steam, or harsh extraction", "Cooling and barrier-supporting steps", "About 45 to 60 minutes", "No downtime", "Pairs with Laser Genesis for lasting redness"],
    concerns: ["dull-tired-skin", "acne-breakouts"],
    session: { duration: "About 45 to 60 minutes", sessions: "Single session, monthly if desired", downtime: "None", feels: "Cool and soothing throughout", results: "Calmer, less flushed skin the same day", verify: "Red Out facial protocol and products: clinic to confirm" },
    goodFor: ["Adults with rosacea-type flushing or sensitive skin", "People whose skin reacts to most facials", "Anyone cleared at consultation, with active flares assessed first"],
    faqs: [
      { q: "Can I get this during a flare?", a: "Sometimes. The steps are chosen to calm rather than provoke, but an active flare is assessed first. If the skin is too inflamed, you may be asked to wait a week or two." },
      { q: "How long does the calming last?", a: "The surface stays calmer for days to a couple of weeks, depending on your triggers. Persistent vessels need Laser Genesis or IPL to change in a lasting way. Home care matters as much as the facial." },
      { q: "What should I avoid before and after?", a: "Skip retinoids, acids, and scrubs for a few days on either side. Avoid heat, alcohol, and hard exercise the same day. Wear sunscreen." },
    ],
    related: ["laser-genesis", "ipl-photofacial", "hydrojelly-mask"],
    image: { slot: "red-out-facial", alt: "Red Out calming facial at Olivo Med Spa", fallback: "skin-2" },
    live: "/services/facial-treatments/red-out-facial/",
    seo: { title: "Red Out Facial for Redness in Chicago | Olivo Med Spa", description: "Red Out facial at Olivo Med Spa in Logan Square, Chicago. A calming, barrier-supporting facial for redness-prone and reactive skin, with no downtime." },
    es: { name: "Facial Red Out", summary: "Un facial calmante para la piel propensa a rojeces y reactiva, sin tiempo de recuperación." },
    verify: ["Red Out facial protocol and products: clinic to confirm"],
  },
  {
    slug: "pca-chemical-peels",
    name: "PCA chemical peels",
    category: "facials-and-peels",
    brand: "PCA Skin",
    tag: "Face and body · Minimal to a few days",
    headline: "Professional PCA peels at graded strengths, from a no-peel refresh to a deeper correction.",
    summary: "PCA chemical peels at Olivo Med Spa are chosen by strength and blend for your concern: dullness, breakouts, pigment, or fine lines. Peel depth and downtime are set at consultation. Logan Square, Chicago.",
    intro: [
      "PCA Skin makes a range of professional peels, from gentle blends you can have over lunch with little visible flaking to stronger formulas that peel for several days and do more for pigment and texture. The acids differ: lactic and mandelic for sensitive or dry skin, salicylic for breakouts, TCA and retinoid blends for pigment and lines.",
      "Peels work well in a series, typically three to six, spaced two to four weeks apart, followed by home care from the clinic's lines. Which peel, at what strength, and how often is a medical decision made at your consultation based on your skin type and history.",
    ],
    benefits: ["Strengths from no-peel to several days of flaking", "Dullness, breakouts, pigment, fine lines", "Face, neck, chest, back, and hands", "Series of three to six", "Peel selected by physician-led assessment"],
    concerns: ["dull-tired-skin", "acne-breakouts", "sun-damage-pigment", "fine-lines-wrinkles"],
    session: { duration: "About 30 to 45 minutes", sessions: "Three to six, two to four weeks apart", downtime: "Minimal to a few days, depending on strength", feels: "Tingling and warmth for a few minutes", results: "Brighter skin within a week, with pigment and texture change over the series", verify: "PCA peel menu, strengths offered, and series spacing: clinic to confirm" },
    goodFor: ["Adults with dull skin, breakouts, or uneven pigment", "People who want a graded option before a laser", "Anyone cleared at consultation, with skin type, medications, and recent sun reviewed"],
    faqs: [
      { q: "Will I actually peel?", a: "It depends on the peel. Lighter blends cause little or no visible flaking. Medium-strength peels flake for three to five days. You will know which you are getting before it goes on." },
      { q: "Can peels be used on darker skin?", a: "Yes, with the right acid and strength. Some formulas suit darker skin types better than others, and the wrong one can cause pigment change. Dr. Olivo selects accordingly at consultation." },
      { q: "How do I prepare?", a: "Stop retinoids and exfoliating acids for several days before, avoid sun and waxing, and tell us about any medications. Home prep with the clinic's lines for a couple of weeks improves how evenly the peel works." },
    ],
    related: ["hydrafacial", "dermaplaning", "ipl-photofacial"],
    image: { slot: "pca-chemical-peels", alt: "PCA chemical peel at Olivo Med Spa", fallback: "hands-1" },
    live: "/services/facial-treatments/pca-peels/",
    seo: { title: "PCA Chemical Peels in Logan Square | Olivo Med Spa", description: "PCA chemical peels at Olivo Med Spa in Logan Square, Chicago. Professional peels at graded strengths for dullness, breakouts, pigment, and fine lines." },
    es: { name: "Peelings químicos PCA", summary: "Peelings profesionales en distintas intensidades para opacidad, brotes, manchas y líneas finas." },
    verify: ["PCA peel formulas stocked: clinic to confirm", "Who performs peels and at which strengths: clinic to confirm"],
  },
  {
    slug: "diamondglow",
    name: "Diamondglow",
    category: "facials-and-peels",
    brand: "Diamondglow",
    tag: "Face · No downtime",
    headline: "Diamond-tip exfoliation, extraction, and serum infusion in a single pass.",
    summary: "Diamondglow uses a diamond-tipped wand to exfoliate, extract, and infuse professional serums at the same time. About 30 to 45 minutes, no downtime, at Olivo Med Spa in Logan Square.",
    intro: [
      "Diamondglow is a three-in-one facial. A diamond-tipped wand physically exfoliates the surface while suction pulls debris from the pores and a serum is infused into the freshly cleared skin. The physical exfoliation makes it a stronger resurfacing step than Hydrafacial, which suits people with rougher texture or more congestion.",
      "Sessions take about thirty to forty-five minutes. Skin may look pink for an hour. Serums are chosen for hydration, brightening, or clarifying. Whether Diamondglow or Hydrafacial fits your skin better, and how often to repeat it, is decided at your consultation after looking at your texture and sensitivity.",
    ],
    benefits: ["Exfoliate, extract, infuse in one pass", "Diamond tip for physical resurfacing", "Serum chosen for your concern", "About 30 to 45 minutes", "No downtime"],
    concerns: ["dull-tired-skin", "skin-texture-scars", "acne-breakouts"],
    session: { duration: "About 30 to 45 minutes", sessions: "Single session, every four to six weeks", downtime: "None", feels: "A firm, gritty glide with light suction", results: "Smoother, brighter skin the same day", verify: "Diamondglow serum options and session length: clinic to confirm" },
    goodFor: ["Adults with rough texture or congested pores", "People who want more exfoliation than a Hydrafacial", "Anyone cleared at consultation, with active breakouts assessed first"],
    faqs: [
      { q: "Diamondglow or Hydrafacial?", a: "Diamondglow exfoliates more, so it suits thicker or rougher skin. Hydrafacial is gentler and more hydrating, so it suits sensitive or dry skin. Your provider recommends one at consultation." },
      { q: "Does it hurt?", a: "No. It feels like a firm, gritty glide with light suction. Skin may be pink for an hour afterward and slightly sensitive that evening." },
      { q: "How often should I book it?", a: "Every four to six weeks is typical. Before an event, allow a day or two for any pinkness to settle." },
    ],
    related: ["hydrafacial", "dermaplaning", "pca-chemical-peels"],
    image: { slot: "diamondglow", alt: "Diamondglow facial at Olivo Med Spa", fallback: "steel-1" },
    live: "/diamondglow/",
    seo: { title: "Diamondglow Facial in Logan Square | Olivo Med Spa", description: "Diamondglow at Olivo Med Spa in Logan Square, Chicago. Diamond-tip exfoliation, extraction, and serum infusion in one 30 to 45 minute facial, no downtime." },
    es: { name: "Diamondglow", summary: "Exfoliación con punta de diamante, extracción e infusión de sérum en un solo paso." },
    verify: ["Diamondglow device and serum menu: clinic to confirm"],
  },
  {
    slug: "glo2facial",
    name: "Glo2Facial by Geneo",
    category: "facials-and-peels",
    brand: "Geneo",
    tag: "Face · No downtime",
    headline: "An oxygenation facial that uses the skin's own response to bring oxygen to the surface.",
    summary: "Glo2Facial by Geneo combines a gentle exfoliating pod, oxygenation from within, and lymphatic massage with ultrasound infusion. About 45 minutes, no downtime, at Olivo Med Spa in Logan Square.",
    intro: [
      "Glo2Facial starts with an Oxypod that reacts with a gel on the skin to create a bubbling exfoliation. That reaction prompts the body to send oxygen-rich blood to the surface, which is what people mean by an oxygenation facial. A lymphatic massage step and ultrasound infusion of active ingredients follow.",
      "The whole session runs about forty-five minutes. Skin looks plump and even afterward with no downtime. Pods are chosen for hydration, brightening, or balancing. Which pod suits your skin, and whether Glo2Facial or another facial is the better fit for your concern, is confirmed at consultation.",
    ],
    benefits: ["Exfoliation, oxygenation, infusion", "Lymphatic massage included", "About 45 minutes", "No downtime", "Pods matched to your concern"],
    concerns: ["dull-tired-skin", "skin-texture-scars", "sun-damage-pigment"],
    session: { duration: "About 45 minutes", sessions: "Single session, monthly for maintenance", downtime: "None", feels: "Warm bubbling, then a relaxing massage", results: "Plumper, more even skin the same day", verify: "Glo2Facial steps and pod options: confirm with Geneo materials" },
    goodFor: ["Adults with dull or tired-looking skin", "People who want a facial that feels like a treatment and a break", "Anyone cleared at consultation"],
    faqs: [
      { q: "How is this different from an oxygen facial?", a: "Oxygen facials spray oxygen onto the skin. Glo2Facial uses a reaction on the surface to prompt the body to deliver oxygen from within, then infuses actives with ultrasound.", verify: "Mechanism wording: confirm with Geneo materials" },
      { q: "Is it suitable for sensitive skin?", a: "Often, yes. There are no strong acids and the exfoliation is gentle. Sensitivity and any active conditions are reviewed at consultation before booking." },
      { q: "How often should I have one?", a: "Monthly is typical for maintenance. A single session before an event also works well because the skin looks plump and even right away." },
    ],
    related: ["hydrafacial", "diamondglow", "glass-skin-facial"],
    image: { slot: "glo2facial", alt: "Glo2Facial by Geneo at Olivo Med Spa", fallback: "light-1" },
    live: "/glo2facial/",
    seo: { title: "Glo2Facial by Geneo in Chicago | Olivo Med Spa", description: "Glo2Facial at Olivo Med Spa in Logan Square, Chicago. An oxygenation facial with exfoliation, lymphatic massage, and infusion in 45 minutes, no downtime." },
    es: { name: "Glo2Facial de Geneo", summary: "Un facial de oxigenación con exfoliación, masaje linfático e infusión, sin tiempo de recuperación." },
    verify: ["Glo2Facial mechanism wording and pod names: confirm with Geneo materials"],
  },
  {
    slug: "dermaplaning",
    name: "Dermaplaning",
    category: "facials-and-peels",
    tag: "Face · No downtime",
    headline: "Manual exfoliation that removes dead surface cells and vellus hair in one pass.",
    summary: "Dermaplaning uses a sterile blade to lift dead skin cells and fine vellus hair from the face. Skin feels smooth, makeup sits better, and products absorb more evenly. About 30 minutes, no downtime, at Olivo Med Spa in Logan Square.",
    intro: [
      "A trained provider holds the skin taut and glides a sterile blade at a shallow angle across the face. It removes the top layer of dead cells along with vellus hair, the fine peach fuzz that catches light and foundation. There is no chemical, no heat, and no downtime. Skin looks brighter immediately.",
      "Dermaplaning takes about thirty minutes on its own and is often added before a peel or facial so actives reach the skin more evenly. It suits most skin types except active acne. Suitability is confirmed at consultation, and your provider will check for any breakouts or irritation before starting.",
    ],
    benefits: ["Dead cells and vellus hair removed together", "Immediate smoothness", "Makeup and skincare go on more evenly", "About 30 minutes", "Adds to a peel or facial"],
    concerns: ["dull-tired-skin", "skin-texture-scars", "unwanted-hair"],
    session: { duration: "About 30 minutes", sessions: "Single session, every four to six weeks", downtime: "None", feels: "A light scraping sensation, not sharp", results: "Smoother, brighter skin immediately", verify: "Dermaplaning provider credentials: clinic to confirm" },
    goodFor: ["Adults with dull skin or visible peach fuzz", "People preparing for an event or a peel", "Anyone cleared at consultation, with active acne assessed first"],
    faqs: [
      { q: "Will the hair grow back thicker?", a: "No. Vellus hair is not changed by cutting. It grows back at the same fineness on the same schedule, usually noticeable again after three to four weeks." },
      { q: "Can I do it with acne?", a: "Not over active breakouts, since the blade can spread bacteria and irritate inflamed skin. Once the skin is calm it can be done, and it can help products work better afterward." },
      { q: "How often should I book it?", a: "Every four to six weeks matches the skin's natural turnover and the regrowth of vellus hair. Many people pair it with a monthly facial." },
    ],
    related: ["pca-chemical-peels", "hydrafacial", "diamondglow"],
    image: { slot: "dermaplaning", alt: "Dermaplaning at Olivo Med Spa", fallback: "hands-1" },
    live: "/services/facial-treatments/dermaplaning/",
    seo: { title: "Dermaplaning in Logan Square, Chicago | Olivo Med Spa", description: "Dermaplaning at Olivo Med Spa in Logan Square, Chicago. Manual exfoliation that removes dead skin cells and vellus hair in about 30 minutes, with no downtime." },
    es: { name: "Dermaplaning", summary: "Exfoliación manual que elimina células muertas y vello fino del rostro en un solo paso." },
    verify: ["Who performs dermaplaning: clinic to confirm"],
  },
  {
    slug: "lash-lift-and-tint",
    name: "Lash lift and tint",
    category: "facials-and-peels",
    tag: "Eyes · No downtime",
    headline: "Curled, darkened natural lashes that last for weeks, without extensions or daily mascara.",
    summary: "A lash lift curls your natural lashes from the base and a tint darkens them. About an hour, no downtime, results for several weeks. Offered at Olivo Med Spa in Logan Square.",
    intro: [
      "A lash lift sets your natural lashes over a silicone shield with a gentle solution, so they curve up from the root and look longer without any extensions. A tint follows to darken them, which matters most for people with light or fine lashes. You leave with lashes that look like mascara, and nothing to remove at night.",
      "The appointment is about an hour with your eyes closed. Results typically last six to eight weeks, which is a natural lash cycle. Keep the lashes dry for the first day. A patch test may be recommended for the tint, and suitability is confirmed at consultation.",
    ],
    benefits: ["Natural lashes, no extensions", "Curl and color in one visit", "About an hour", "No downtime", "Typically lasts six to eight weeks"],
    concerns: ["dull-tired-skin"],
    session: { duration: "About 60 minutes", sessions: "Single session, every six to eight weeks", downtime: "None", feels: "Eyes closed, light pressure on the lids", results: "Lifted, darker lashes immediately", verify: "Lash lift products, patch test policy, and duration: clinic to confirm" },
    goodFor: ["Adults with straight or light lashes", "People who want to skip daily mascara or curlers", "Anyone cleared at consultation, with eye sensitivities reviewed"],
    faqs: [
      { q: "Does it damage the lashes?", a: "Not when it is done at the right timing and not repeated too often. Waiting the full six to eight weeks between lifts protects the lash. Overprocessing is what causes breakage." },
      { q: "Can I wear mascara after?", a: "Yes, after the first twenty-four hours. Many people find they no longer need it. Avoid waterproof formulas and oil-based removers, which loosen the lift." },
      { q: "What if I wear contacts?", a: "Remove them before the appointment and bring your case. You can put them back in once the treatment is finished." },
    ],
    related: ["dermaplaning", "hydrafacial", "botox-and-xeomin"],
    image: { slot: "lash-lift-and-tint", alt: "Lash lift and tint at Olivo Med Spa", fallback: "portrait" },
    live: "/services/lash-lift-and-tint/",
    seo: { title: "Lash Lift and Tint in Logan Square | Olivo Med Spa", description: "Lash lift and tint at Olivo Med Spa in Logan Square, Chicago. Curled, darkened natural lashes in about an hour, no extensions, results for several weeks." },
    es: { name: "Lifting y tinte de pestañas", summary: "Pestañas naturales rizadas y oscurecidas durante semanas, sin extensiones ni rímel diario." },
    verify: ["Lash lift product line and who performs it: clinic to confirm"],
  },
  {
    slug: "hydrojelly-mask",
    name: "Hydrojelly mask add-on",
    category: "facials-and-peels",
    tag: "Face · Add-on",
    headline: "A cooling, peel-off jelly mask added to any facial to seal in hydration.",
    summary: "The Hydrojelly mask is an add-on to any facial at Olivo Med Spa. Mixed fresh and applied as a cooling layer, it locks in the serums from your treatment and calms the skin. About 15 extra minutes, in Logan Square.",
    intro: [
      "Hydrojelly masks are mixed fresh from a powder and water, applied as a thick, cool layer that sets into a jelly, then peeled off in one piece. The layer holds moisture and the active serums from your facial against the skin while it sets. Formulas vary: hyaluronic for hydration, cucumber or aloe for calming, brightening blends for tone.",
      "It adds about fifteen minutes to a facial and can be booked with Hydrafacial, Diamondglow, Glo2Facial, or dermaplaning. Which formula to add is chosen with your provider on the day, based on how your skin responds to the facial, and suitability is confirmed at consultation.",
    ],
    benefits: ["Seals in serums from your facial", "Cooling and calming", "About 15 extra minutes", "Formulas for hydration, calming, or tone", "Add to most facials"],
    concerns: ["dull-tired-skin"],
    session: { duration: "About 15 minutes added to a facial", sessions: "Add-on to any facial", downtime: "None", feels: "Cold and heavy, then peels off clean", results: "Plumper, calmer skin as you leave", verify: "Hydrojelly formulas stocked: clinic to confirm" },
    goodFor: ["Anyone booking a facial who wants extra hydration", "People whose skin runs red after exfoliation", "Anyone cleared at consultation"],
    faqs: [
      { q: "Which facials can it be added to?", a: "Most of them. It is a natural finish to Hydrafacial, Diamondglow, Glo2Facial, dermaplaning, and the Glass Skin facial. Ask when you book and it is added to the appointment." },
      { q: "Can I book it on its own?", a: "It is designed as an add-on. Ask at booking whether a standalone mask appointment is available.", verify: "Standalone availability: clinic to confirm" },
      { q: "Is it suitable for sensitive skin?", a: "Usually, yes. The calming formulas are chosen for exactly that. Ingredients are reviewed with you before it goes on if you have known sensitivities." },
    ],
    related: ["hydrafacial", "diamondglow", "glo2facial", "red-out-facial"],
    image: { slot: "hydrojelly-mask", alt: "Hydrojelly mask add-on at Olivo Med Spa", fallback: "room-3" },
    live: "/services/facial-treatments/hydrojellymask/",
    seo: { title: "Hydrojelly Mask Add-On in Chicago | Olivo Med Spa", description: "Hydrojelly mask add-on at Olivo Med Spa in Logan Square, Chicago. A cooling peel-off jelly mask that seals in hydration after any facial, 15 extra minutes." },
    es: { name: "Mascarilla Hydrojelly (complemento)", summary: "Una mascarilla de gel refrescante que se añade a cualquier facial para sellar la hidratación." },
    verify: ["Hydrojelly brand and formulas: clinic to confirm", "Whether the mask can be booked standalone: clinic to confirm"],
  },
];
