// Laser, light, and removals. See docs/CONTENT-RULES.md before editing.
import type { Service } from "../types";

export const laserServices: Service[] = [
  {
    slug: "laser-hair-removal",
    name: "Laser hair removal",
    category: "laser-and-light",
    tag: "Face and body · No downtime",
    headline: "A series of sessions to reduce unwanted hair, with settings matched to your skin tone at consultation.",
    summary: "Laser hair removal at Olivo Med Spa treats face and body in a planned series. Skin tone and hair color are assessed at consultation so the right settings are used. The Laser Hair Reduction Club membership covers ongoing sessions in Logan Square.",
    intro: [
      "Laser hair removal targets pigment in the hair follicle with light energy, disabling the follicle over a series of sessions. Hair grows in cycles, so only follicles in the active phase respond at each visit. That is why a plan is a series, usually six to eight sessions spaced several weeks apart, rather than a single appointment.",
      "Skin tone and hair color determine which settings are appropriate. All skin tones are assessed at consultation. Common areas include underarms, bikini, legs, back, chest, and face. Sessions run from ten minutes for a small area to about an hour for full legs.",
      "For people who want to maintain results over time, the Laser Hair Reduction Club membership spreads sessions across the year. Terms are explained at consultation, along with a realistic estimate of how many sessions your areas will need and how to prepare the skin before each visit.",
    ],
    benefits: ["Face and body areas", "Settings matched to skin tone and hair color", "Short sessions, no downtime", "Laser Hair Reduction Club membership available", "Assessed and planned at consultation"],
    concerns: ["unwanted-hair"],
    session: { duration: "10 to 60 minutes depending on area", sessions: "A series, typically six to eight, four to eight weeks apart", downtime: "None", feels: "A quick snap of heat with each pulse, with cooling between", results: "Hair grows back finer and sparser after each session, with the fullest reduction after the series", verify: "Session count, spacing, device, and wavelengths: clinic to confirm" },
    goodFor: ["Adults tired of shaving, waxing, or ingrown hairs", "People with dark hair against lighter or darker skin, assessed at consultation", "Anyone cleared at consultation, with recent sun and medications reviewed"],
    faqs: [
      { q: "Will the hair come back?", a: "Most people see a lasting reduction after a full series. Hormones and follicles that were dormant during treatment can produce new growth over time, so occasional maintenance sessions are common. That is what the Laser Hair Reduction Club is for." },
      { q: "Does it work on darker skin?", a: "Settings differ by skin tone, and the right wavelength matters for darker skin. All skin tones are assessed at consultation and treated only when the device and settings are appropriate for you.", verify: "Device suitability for darker skin types: clinic to confirm" },
      { q: "How should I prepare?", a: "Shave the area the day before. Avoid waxing, plucking, and sun exposure for several weeks before each session, since the laser needs the follicle in place and untanned skin to work well." },
      { q: "What is the Laser Hair Reduction Club?", a: "A membership that spreads laser hair removal sessions across the year for people treating multiple areas or maintaining results. Terms are covered at consultation.", verify: "Laser Hair Reduction Club terms: to be supplied" },
    ],
    related: ["miradry", "ipl-photofacial", "exion-body"],
    image: { slot: "laser-hair-removal", alt: "Laser hair removal treatment room at Olivo Med Spa", fallback: "room-2" },
    live: "/services/laserlight-treatments/laser-hair-removal/",
    seo: { title: "Laser Hair Removal in Logan Square | Olivo Med Spa", description: "Laser hair removal at Olivo Med Spa in Logan Square, Chicago. A planned series for face and body, all skin tones assessed at consultation. Membership available." },
    es: { name: "Depilación láser", summary: "Una serie de sesiones para reducir el vello no deseado, con ajustes según tu tono de piel." },
    verify: ["Laser hair removal device and wavelengths: clinic to confirm", "Laser Hair Reduction Club terms: to be supplied", "Who performs laser hair removal: clinic to confirm"],
  },
  {
    slug: "ipl-photofacial",
    name: "IPL photofacial",
    category: "laser-and-light",
    tag: "Face · Minimal",
    headline: "Intense pulsed light for sun spots, redness, and uneven tone, with little time away from your week.",
    summary: "An IPL photofacial uses broad-spectrum light to target brown spots and visible redness so tone looks more even. A short series at Olivo Med Spa in Logan Square, planned by a physician.",
    intro: [
      "IPL is not a laser. It delivers pulses of filtered light across a range of wavelengths, and both melanin in sun spots and hemoglobin in small vessels absorb that light. Spots darken and flake off over a week or so. Redness fades as vessels close. The result is more even tone on the face, neck, chest, or hands.",
      "A typical plan is three sessions, about four weeks apart. Each visit takes twenty to thirty minutes. You may look flushed for a few hours and the spots look darker before they lift. Most people go back to their day.",
      "IPL works on pigment, so skin tone and recent sun matter. Dr. Olivo confirms whether IPL or Laser Genesis is the right tool at your consultation, checks for anything that would make treatment unwise, and sets expectations for how the spots will look in the days after each session.",
    ],
    benefits: ["Sun spots, redness, and uneven tone", "Face, neck, chest, and hands", "About twenty to thirty minutes", "Minimal downtime", "Often paired with Laser Genesis"],
    concerns: ["sun-damage-pigment", "dull-tired-skin"],
    session: { duration: "About 20 to 30 minutes", sessions: "Three sessions, about four weeks apart", downtime: "Minimal", feels: "A snap of heat with each pulse, like a rubber band", results: "Spots darken and lift within a week or two, with tone evening over the series", verify: "IPL device, session count, and spacing: clinic to confirm" },
    goodFor: ["Adults with sun spots or freckling on the face, chest, or hands", "People with diffuse redness or flushing", "Anyone cleared at consultation, with skin type and recent sun reviewed"],
    faqs: [
      { q: "IPL or Laser Genesis?", a: "IPL for distinct brown spots and visible vessels. Laser Genesis for diffuse redness, pores, and fine lines with zero downtime. Many people do both. Dr. Olivo decides the order at consultation." },
      { q: "Will the spots come back?", a: "Treated spots lift, but new sun exposure creates new ones. Daily sunscreen and a maintenance session each year are what keep tone even." },
      { q: "Can I do IPL with a tan?", a: "No. Tanned skin absorbs the light meant for the spots and raises the risk of burns and pigment change. Stay out of the sun and off self-tanner for a few weeks before each session." },
      { q: "Does it hurt?", a: "Each pulse feels like a rubber band snap with a flash of warmth. Cooling gel and a chilled tip keep it tolerable. No numbing is needed for most people." },
    ],
    related: ["laser-genesis", "hydrafacial", "pca-chemical-peels"],
    image: { slot: "ipl-photofacial", alt: "IPL photofacial at Olivo Med Spa", fallback: "skin-2" },
    live: "/services/laserlight-treatments/ipl-photofacial/",
    seo: { title: "IPL Photofacial in Logan Square | Olivo Med Spa", description: "IPL photofacial at Olivo Med Spa in Logan Square, Chicago. Intense pulsed light for sun spots, redness, and uneven tone, with minimal downtime." },
    es: { name: "Fotofacial IPL", summary: "Luz pulsada intensa para manchas solares, rojeces y tono desigual, con mínimo tiempo de recuperación." },
    verify: ["IPL device manufacturer: clinic to confirm", "Who performs IPL: clinic to confirm"],
  },
  {
    slug: "laser-genesis",
    name: "Laser Genesis",
    category: "laser-and-light",
    tag: "Face · No downtime",
    headline: "A gentle non-ablative laser for redness, pores, and fine lines. Nothing to hide afterward.",
    summary: "Laser Genesis warms the upper dermis with a non-ablative laser to reduce redness, refine pores, and soften fine lines. No downtime, so it fits a lunch hour. Offered at Olivo Med Spa in Logan Square.",
    intro: [
      "Laser Genesis passes a non-ablative laser over the skin in a steady, warming motion. It does not break the surface. The heat stimulates collagen in the upper dermis and reduces the tiny vessels that cause diffuse redness. People with rosacea-type flushing, enlarged pores, or early fine lines tend to like it because there is nothing to recover from.",
      "Sessions take about thirty minutes and feel warm rather than sharp. A series of four to six, spaced a few weeks apart, is typical, then maintenance a few times a year. It pairs well with IPL for people who have both redness and brown spots.",
      "Whether Laser Genesis alone is enough, or whether to combine it with a peel or IPL, is decided at your consultation. Dr. Olivo looks at what is driving the redness, reviews your skin type and current products, and sets a series length that fits your goals and schedule.",
    ],
    benefits: ["Redness, pores, and fine lines", "No downtime, no numbing needed", "About thirty minutes", "Comfortable enough for a lunch break", "Pairs with IPL or peels"],
    concerns: ["fine-lines-wrinkles", "skin-texture-scars", "dull-tired-skin"],
    session: { duration: "About 30 minutes", sessions: "Four to six sessions, a few weeks apart", downtime: "None", feels: "A gentle, spreading warmth", results: "Gradual change in redness and texture across the series, with the fullest change after it ends", verify: "Laser Genesis device and protocol: clinic to confirm" },
    goodFor: ["Adults with diffuse redness or rosacea-type flushing", "People who want texture change with zero downtime", "Anyone cleared at consultation, including those who cannot take time off"],
    faqs: [
      { q: "How does it feel?", a: "Like warm sunlight moving across the skin. No numbing is needed. Some people find it relaxing. Skin may be slightly pink for an hour afterward." },
      { q: "How many sessions do I need?", a: "Four to six sessions, a few weeks apart, is the usual series because the change is cumulative. Dr. Olivo sets the count at consultation and may suggest maintenance a few times a year." },
      { q: "Can I wear makeup afterward?", a: "Yes, right away. There is no broken skin and no peeling. Most people book it on a lunch break and go back to work." },
      { q: "How is this different from IPL?", a: "IPL is filtered light that targets distinct spots and vessels and leaves them darker for a week. Laser Genesis is a single-wavelength laser that warms the skin evenly for diffuse redness and texture, with no visible aftermath." },
    ],
    related: ["ipl-photofacial", "red-out-facial", "hydrafacial"],
    image: { slot: "laser-genesis", alt: "Laser Genesis treatment at Olivo Med Spa", fallback: "light-1" },
    live: "/services/injectables-dermal-fillers/lasergenesis/",
    seo: { title: "Laser Genesis in Logan Square, Chicago | Olivo Med Spa", description: "Laser Genesis at Olivo Med Spa in Logan Square, Chicago. A gentle non-ablative laser for redness, pores, and fine lines with no downtime. Book a consultation." },
    es: { name: "Laser Genesis", summary: "Un láser suave no ablativo para rojeces, poros y líneas finas, sin tiempo de recuperación." },
    verify: ["Laser Genesis device manufacturer, wavelength, and protocol: clinic to confirm", "Who performs Laser Genesis: clinic to confirm"],
  },
  {
    slug: "tattoo-removal",
    name: "Laser tattoo removal",
    category: "removals",
    tag: "Face and body · Minimal",
    headline: "Laser tattoo removal in a series of sessions spaced weeks apart, so the body can clear the ink.",
    summary: "Laser tattoo removal breaks ink into particles the body clears over time. Removal takes multiple sessions spaced several weeks apart, with the count depending on ink color, depth, and age. Physician-led at Olivo Med Spa in Logan Square.",
    intro: [
      "The laser delivers very short pulses that shatter ink particles without cutting the skin. Your immune system then carries the fragments away over the following weeks. Each session breaks down another layer, which is why sessions are spaced six to eight weeks apart and a full removal takes a series. Black ink usually responds fastest. Greens and light blues take longer.",
      "Expect frosting on the skin during treatment, then a few days of redness and sometimes blistering. Aftercare is simple and written down for you. Sessions are short, often under twenty minutes for a small piece, and the treated area is kept covered and out of the sun while it heals.",
      "How many sessions your tattoo needs, and whether full clearance or lightening for a cover-up is the goal, is set at your consultation. Dr. Olivo examines the ink colors, depth, and location, reviews your skin type, and gives you a realistic range rather than a single number.",
    ],
    benefits: ["Full removal or lightening for a cover-up", "Sessions often under twenty minutes", "Spaced six to eight weeks apart", "Black and dark inks respond most readily", "Plan set at consultation"],
    concerns: ["unwanted-tattoos"],
    session: { duration: "10 to 30 minutes depending on size", sessions: "Multiple sessions, typically six to eight weeks apart", downtime: "Minimal", feels: "Sharp snaps of heat, like a rubber band, eased by cooling and numbing", results: "Gradual fading between sessions as the body clears the ink", verify: "Tattoo removal laser type, session spacing, and ink response: clinic to confirm" },
    goodFor: ["Adults who want a tattoo gone or lightened for new work", "People who can commit to a series over many months", "Anyone cleared at consultation, with skin type and tattoo history reviewed"],
    faqs: [
      { q: "How many sessions will it take?", a: "It depends on ink color, depth, age, location, and your skin. Professional black tattoos often need fewer sessions than colorful or dense ones. Dr. Olivo gives you a realistic range at consultation." },
      { q: "Will it scar?", a: "Scarring is uncommon when aftercare is followed and sessions are properly spaced, but any skin treatment carries some risk. Scarring that already exists from the tattoo itself will remain after the ink is gone." },
      { q: "Why the long gaps between sessions?", a: "The laser only breaks the ink apart. Your body does the clearing, and that takes weeks. Treating too soon adds risk without adding benefit." },
      { q: "Can all ink colors be removed?", a: "Not all colors respond equally. Black and dark blue clear most readily. Greens, light blues, and yellows can be stubborn and may not clear fully. This is assessed at consultation." },
    ],
    related: ["mole-removal", "vein-removal", "laser-hair-removal"],
    image: { slot: "tattoo-removal", alt: "Laser tattoo removal at Olivo Med Spa", fallback: "steel-1" },
    live: "/services/laserlight-treatments/tattoo-removal/",
    seo: { title: "Laser Tattoo Removal in Chicago | Olivo Med Spa", description: "Laser tattoo removal at Olivo Med Spa in Logan Square, Chicago. A series of sessions spaced weeks apart to fade or remove ink, planned at consultation." },
    es: { name: "Eliminación de tatuajes con láser", summary: "Eliminación de tatuajes en una serie de sesiones separadas por varias semanas para que el cuerpo elimine la tinta." },
    verify: ["Tattoo removal laser make and model: clinic to confirm", "Who performs tattoo removal: clinic to confirm"],
  },
  {
    slug: "vein-removal",
    name: "Spider and facial vein removal",
    category: "removals",
    tag: "Face and legs · Minimal",
    headline: "Spider veins on the legs and small facial vessels treated with laser or injection, chosen by your physician.",
    summary: "Spider and facial vein removal at Olivo Med Spa treats small red or blue vessels on the face and legs. Dr. Olivo selects laser or sclerotherapy based on the vessel. Minimal downtime, in Logan Square.",
    intro: [
      "Small surface vessels on the nose, cheeks, and legs are common and usually harmless, but they are hard to cover. Laser energy heats the vessel so it closes and is absorbed by the body over the following weeks. For larger leg spider veins, sclerotherapy, an injection that closes the vein from inside, may be the better tool. Dr. Olivo decides which at your visit.",
      "Facial vessels often clear in one or two sessions. Leg veins usually need two to three sessions, spaced a month or more apart. Expect mild redness or small bruises for a few days. Compression may be recommended for the legs.",
      "Vein treatment starts with a physician assessment. If a vessel pattern suggests something that should be evaluated further, Dr. Olivo will say so before treating. Candidacy, the choice between laser and injection, and the number of sessions to expect are all set at that consultation.",
    ],
    benefits: ["Facial vessels and leg spider veins", "Laser or sclerotherapy, chosen per vessel", "Short sessions, minimal downtime", "Physician assessment before treatment", "Pairs with IPL for diffuse redness"],
    concerns: ["veins-and-moles"],
    session: { duration: "About 15 to 30 minutes", sessions: "One to three sessions, four to six weeks apart", downtime: "Minimal", feels: "Quick pinpricks of heat or a small injection sting", results: "Vessels fade over several weeks as the body absorbs them", verify: "Vein removal device, sclerotherapy offering, and session spacing: clinic to confirm" },
    goodFor: ["Adults with visible vessels on the nose or cheeks", "People with spider veins on the thighs, calves, or ankles", "Anyone cleared at consultation, with circulation history reviewed"],
    faqs: [
      { q: "Laser or injection?", a: "Small facial vessels are almost always treated with laser. Leg spider veins can go either way. Larger or deeper ones often respond better to sclerotherapy. Dr. Olivo chooses based on vessel size, depth, and location." },
      { q: "Will the veins come back?", a: "Treated vessels close and fade. New vessels can form over time, especially with sun, hormones, or a job on your feet. Occasional touch-up sessions are common." },
      { q: "Is there downtime?", a: "Very little. Facial treatment may leave pinkness for a day. Leg treatment can leave small bruises for a week or so, and you may be asked to wear compression and skip hard exercise for a few days." },
      { q: "Can varicose veins be treated here?", a: "No. Larger varicose veins need a vascular specialist. If that is what Dr. Olivo sees at your assessment, she will refer you rather than treat." },
    ],
    related: ["ipl-photofacial", "laser-genesis", "mole-removal"],
    image: { slot: "vein-removal", alt: "Spider vein treatment at Olivo Med Spa", fallback: "hands-1" },
    live: "/services/laserlight-treatments/spider-vein-removal/",
    seo: { title: "Spider Vein Removal in Logan Square | Olivo Med Spa", description: "Spider and facial vein removal at Olivo Med Spa in Logan Square, Chicago. Laser or sclerotherapy for small vessels on the face and legs, chosen by a physician." },
    es: { name: "Eliminación de arañas vasculares y venas faciales", summary: "Tratamiento de pequeños vasos visibles en el rostro y las piernas, con láser o escleroterapia según el caso." },
    verify: ["Confirm the clinic offers sclerotherapy in addition to laser vein treatment", "Vein laser device: clinic to confirm", "Who performs vein treatment: clinic to confirm"],
  },
  {
    slug: "mole-removal",
    name: "Mole and skin tag removal",
    category: "removals",
    tag: "Face and body · Minimal",
    headline: "Moles and skin tags removed in office after a physician evaluation. Anything suspicious goes to pathology first.",
    summary: "Mole and skin tag removal at Olivo Med Spa starts with an evaluation by Dr. Olivo. Benign lesions are removed in a short office visit. Anything suspicious is referred for pathology before any cosmetic step. Logan Square, Chicago.",
    intro: [
      "Every mole removal here begins with a physician looking at the lesion. Dr. Olivo has practiced medicine since 2007 and evaluates moles with that background. If a mole looks benign and you want it gone for comfort or appearance, it can usually be removed the same day. If anything about it raises a question, it is sent for pathology or you are referred to dermatology first.",
      "Skin tags, cherry angiomas, and small benign moles are removed with a shave technique, cautery, or radiofrequency depending on the lesion. The area is numbed first. Healing is a small scab that resolves over one to two weeks, and the mark continues to fade over the following months.",
      "Whether a lesion is a candidate for cosmetic removal is a medical decision made at your evaluation, not a menu item. Dr. Olivo also sets expectations for the mark that removal leaves, which depends on the lesion, its location, and how your skin heals.",
    ],
    benefits: ["Physician evaluation before any removal", "Suspicious lesions referred for pathology", "Skin tags, cherry angiomas, benign moles", "Numbed, quick, minimal downtime", "Face, neck, and body"],
    concerns: ["veins-and-moles"],
    session: { duration: "About 15 to 30 minutes including numbing", sessions: "Usually a single visit per lesion", downtime: "Minimal", feels: "A small pinch from the numbing, then pressure", results: "A small scab that resolves over one to two weeks, with the mark fading over months", verify: "Removal methods offered and pathology referral process: clinic to confirm" },
    goodFor: ["Adults with skin tags that catch on clothing or jewelry", "People with a benign mole they would like removed for appearance", "Anyone evaluated at consultation, with any changing or irregular lesion assessed first"],
    faqs: [
      { q: "Will it leave a scar?", a: "Any removal leaves some mark. The goal is a flat, faint one that fades. Technique, location, and your own healing all affect it. Dr. Olivo discusses expectations before removing anything." },
      { q: "What if the mole looks suspicious?", a: "Then it is not removed cosmetically. It is biopsied and sent to pathology, or you are referred to dermatology, and the results guide what happens next. That order is fixed." },
      { q: "Can several moles or skin tags be done in one visit?", a: "Usually, yes. Multiple skin tags or small benign lesions are commonly treated in the same appointment once each has been evaluated." },
      { q: "Does insurance cover this?", a: "Cosmetic removal of benign lesions is not typically covered by insurance. If a lesion needs medical evaluation or pathology, that is a separate conversation and you may be referred to dermatology." },
    ],
    related: ["vein-removal", "tattoo-removal", "ipl-photofacial"],
    image: { slot: "mole-removal", alt: "Physician evaluation before mole removal at Olivo Med Spa", fallback: "portrait" },
    live: "/services/laserlight-treatments/mole-removal/",
    seo: { title: "Mole and Skin Tag Removal in Chicago | Olivo Med Spa", description: "Mole and skin tag removal at Olivo Med Spa in Logan Square, Chicago. Physician evaluation first, suspicious lesions sent to pathology, benign ones removed." },
    es: { name: "Eliminación de lunares y acrocordones", summary: "Eliminación de lunares y acrocordones benignos tras una evaluación médica; cualquier lesión sospechosa se deriva a patología." },
    verify: ["Removal techniques used (shave, cautery, radiofrequency): clinic to confirm", "Pathology and dermatology referral process: clinic to confirm"],
  },
];
