// Skin resurfacing. See docs/CONTENT-RULES.md before editing.
import type { Service } from "../types";

export const skinServices: Service[] = [
  {
    slug: "opus-plasma",
    name: "Opus Plasma",
    category: "skin-resurfacing",
    brand: "Alma",
    tag: "Face · A few days",
    headline: "Fractional plasma resurfacing for texture, lines, and scars, with recovery measured in days.",
    summary: "Opus Plasma uses fractional plasma energy to resurface skin, with depth tuned to your texture, lines, or scars. A physician-led resurfacing option in Logan Square with shorter downtime than traditional ablative lasers.",
    intro: [
      "Opus Plasma is Alma's fractional plasma platform. The tip delivers plasma energy to the skin in a controlled grid, creating small zones of treated tissue with untouched skin between them. That pattern is what lets the skin recover quickly. Dr. Olivo sets depth and coverage for each area, so a light pass on the cheeks and a deeper pass on acne scars can happen in the same visit.",
      "Most people describe a few days of redness and a sandpaper feel as the skin turns over, then smoother texture in the weeks that follow. It sits between a peel and a CO2 laser in how much it does and how long you are down.",
      "Candidacy depends on your skin type, sun exposure, and what you want treated. Dr. Olivo confirms whether Opus Plasma, CO2, or Exion RF microneedling is the right tool at your consultation, and sets expectations for how many sessions and how much recovery your plan will involve.",
    ],
    benefits: ["Depth adjusted to texture, lines, or scars", "Fractional pattern, so recovery is quicker", "Face, neck, chest, and hands", "Single session or a short series", "Physician-set settings, not presets"],
    concerns: ["fine-lines-wrinkles", "skin-texture-scars", "sun-damage-pigment"],
    session: { duration: "About 30 to 45 minutes with numbing", sessions: "One to three sessions, about four weeks apart", downtime: "A few days", feels: "Heat and prickling under topical numbing", results: "Texture change as the skin turns over in the first weeks, with continued change over a few months", verify: "Session count, spacing, and downtime: confirm with Alma protocol and clinic experience" },
    goodFor: ["Adults with texture, fine lines, or acne scars who want a shorter recovery than CO2", "People who can protect treated skin from sun for a few weeks", "Anyone cleared at consultation, with skin type and recent isotretinoin use reviewed"],
    faqs: [
      { q: "How is Opus Plasma different from a laser?", a: "A laser delivers light. Opus Plasma delivers plasma energy from a metal tip that ionizes the air just above the skin. It resurfaces in a fractional pattern like a fractional laser, but with less heat spread into surrounding tissue, which is where the shorter recovery comes from.", verify: "Mechanism wording: confirm with Alma materials" },
      { q: "How long is the downtime?", a: "Plan on a few days of redness and rough texture, then a light flaking. Most people are comfortable in public with mineral makeup by day three or four. Deeper settings mean a few more days." },
      { q: "How many sessions do I need?", a: "One session makes a visible difference for many people. Scars and deeper lines usually do better with two or three, about four weeks apart. Dr. Olivo sets the plan at consultation." },
      { q: "Can it be combined with other treatments?", a: "Yes. It is often paired with Opus Colibri for eyelids and lip lines in the same visit, and with Botox Cosmetic or filler planned a few weeks apart." },
    ],
    related: ["co2-fractional-laser", "exion-rf-microneedling", "opus-colibri"],
    image: { slot: "opus-plasma", alt: "Opus Plasma resurfacing at Olivo Med Spa", fallback: "light-1" },
    live: "/services/facial-treatments/opus-plasma/",
    seo: { title: "Opus Plasma Resurfacing in Chicago | Olivo Med Spa", description: "Opus Plasma fractional plasma resurfacing at Olivo Med Spa in Logan Square, Chicago. Depth tuned to texture, lines, and scars. Physician-led since 2013." },
    es: { name: "Opus Plasma", summary: "Resurfacing fraccionado con plasma para textura, líneas y cicatrices, con una recuperación de pocos días." },
    verify: ["Downtime comparison with traditional ablative lasers: confirm with Alma materials", "Who performs Opus Plasma and the numbing protocol: clinic to confirm"],
  },
  {
    slug: "co2-fractional-laser",
    name: "CO2 fractional laser",
    category: "skin-resurfacing",
    tag: "Face · About a week",
    headline: "The deepest resurfacing in the clinic, for texture, scars, and lines that lighter treatments do not reach.",
    summary: "The CO2 fractional laser is the deepest resurfacing treatment at Olivo Med Spa. It treats acne scars, etched lines, and rough texture in one session, with about a week of downtime, under physician care in Logan Square.",
    intro: [
      "Fractional CO2 removes columns of skin down to a controlled depth and heats the tissue around them. The skin responds by rebuilding with new collagen. Because it works deeper than plasma or microneedling, it is the treatment Dr. Olivo reaches for when scars, etched lines, or sun-damaged texture have not responded to lighter options.",
      "Plan on about a week at home. The skin is red and weeping for the first days, then peels and settles. Most people treat once and see change over the following months as collagen remodels. A second session is sometimes planned for deep scarring.",
      "CO2 is not the right choice for everyone. Skin type, recent sun, healing history, and how much time you can take away all matter. Dr. Olivo reviews these at your consultation, sets expectations for recovery, and may recommend Opus Plasma or Erbium instead when that is the better fit.",
    ],
    benefits: ["Deepest resurfacing available at the clinic", "Acne scars, etched lines, rough texture", "Usually a single session", "Physician-led plan and written aftercare", "Pairs with Opus Plasma for lighter areas"],
    concerns: ["skin-texture-scars", "fine-lines-wrinkles", "sun-damage-pigment"],
    session: { duration: "About 45 to 60 minutes with numbing", sessions: "Usually a single session", downtime: "About a week", feels: "Intense heat under numbing, then a sunburn feel for the first days", results: "Smoother texture as the skin heals, with collagen change continuing for several months", verify: "Session length, numbing protocol, and healing timeline: clinic to confirm" },
    goodFor: ["Adults with deeper acne scars or etched lines", "People who can take about a week away from work and sun", "Anyone cleared at consultation, with skin type and healing history reviewed"],
    faqs: [
      { q: "How much downtime should I plan for?", a: "About a week. Days one to three are red, swollen, and weeping. Days four to seven are peeling. Pinkness can linger for a few weeks and is easy to cover once the skin is closed. You will leave with a written aftercare plan." },
      { q: "Does it hurt?", a: "Topical numbing is applied for a good while before treatment, and cooling air runs during it. Most people describe strong heat rather than sharp pain. The first two days afterward feel like a bad sunburn." },
      { q: "Is CO2 right for darker skin?", a: "Deeper ablative resurfacing carries more pigment risk in darker skin types. Dr. Olivo assesses skin type at consultation and may recommend Exion RF microneedling or a lighter Opus Plasma setting instead." },
      { q: "How is it different from Erbium?", a: "CO2 goes deeper and delivers more heat, which means more collagen remodeling and more downtime. Erbium removes tissue more precisely with less heat, so recovery is shorter and the change is more modest." },
    ],
    related: ["erbium-resurfacing", "opus-plasma", "exion-rf-microneedling"],
    image: { slot: "co2-fractional-laser", alt: "CO2 fractional laser treatment room at Olivo Med Spa", fallback: "steel-1" },
    live: "/services/laserlight-treatments/co2-laser-fractional-resurfacing/",
    seo: { title: "CO2 Fractional Laser in Logan Square | Olivo Med Spa", description: "CO2 fractional laser at Olivo Med Spa in Logan Square, Chicago. The clinic's deepest resurfacing for scars, lines, and texture, with about a week of downtime." },
    es: { name: "Láser fraccionado CO2", summary: "El resurfacing más profundo de la clínica para textura, cicatrices y líneas, con cerca de una semana de recuperación." },
    verify: ["CO2 device manufacturer and model: clinic to confirm", "Who performs CO2 and whether anesthesia beyond topical numbing is used: clinic to confirm"],
  },
  {
    slug: "erbium-resurfacing",
    name: "Erbium laser resurfacing",
    category: "skin-resurfacing",
    tag: "Face · A few days",
    headline: "Ablative resurfacing with a lighter touch and a shorter recovery than CO2.",
    summary: "Erbium laser resurfacing removes the outer layers of skin with less heat than CO2, so recovery is shorter. It suits fine lines, mild texture, and sun damage. Physician-led at Olivo Med Spa in Logan Square.",
    intro: [
      "Erbium lasers are absorbed by water in the skin more efficiently than CO2, so they remove tissue with less surrounding heat. That means a more precise ablation and a faster recovery, usually a few days of redness and peeling rather than a full week. It also means less collagen remodeling than CO2, which is the trade-off.",
      "Dr. Olivo turns to Erbium when the goal is smoother surface texture, fine lines around the eyes and mouth, or sun-damaged skin, and when a week of downtime is not an option. Treatment can be light or full-field depending on what you need.",
      "Whether Erbium, Opus Plasma, or CO2 is the right tool depends on your skin, your goals, and your schedule. Dr. Olivo sets that at your consultation, along with how deep to treat, how many sessions to plan, and what recovery to expect for your skin type.",
    ],
    benefits: ["Shorter recovery than CO2", "Fine lines, mild texture, sun damage", "Precise, with less heat to surrounding skin", "Depth adjusted per area", "Single session or a short series"],
    concerns: ["fine-lines-wrinkles", "skin-texture-scars", "sun-damage-pigment"],
    session: { duration: "About 30 to 45 minutes with numbing", sessions: "One session, repeated if needed", downtime: "A few days", feels: "Heat and stinging under topical numbing", results: "Smoother texture as the skin peels and settles over the first two weeks", verify: "Erbium session length, downtime, and repeat interval: clinic to confirm" },
    goodFor: ["Adults with fine lines or mild texture who want a shorter recovery", "People with sun damage on the face, neck, or hands", "Anyone cleared at consultation, with skin type reviewed"],
    faqs: [
      { q: "Erbium or CO2, which do I need?", a: "Erbium for surface texture, fine lines, and sun damage when you need to be back in a few days. CO2 for deeper scars and etched lines when you can take a week. Dr. Olivo makes the call at consultation after looking at your skin." },
      { q: "How long will I be red?", a: "Usually three to five days of redness and peeling, then pinkness that fades over a week or two and covers easily. Deeper passes take a little longer." },
      { q: "What areas can be treated?", a: "The full face is most common. The neck, chest, and hands can be treated with adjusted settings, as can smaller zones like the upper lip or under the eyes." },
      { q: "When can I wear makeup again?", a: "Once the skin has finished peeling and is fully closed, often within a few days to a week. Your written aftercare gives specific timing for your treatment depth." },
    ],
    related: ["co2-fractional-laser", "opus-plasma", "opus-colibri"],
    image: { slot: "erbium-resurfacing", alt: "Erbium laser resurfacing at Olivo Med Spa", fallback: "skin-1" },
    live: "/services/laserlight-treatments/erbium-laser-resurfacing/",
    seo: { title: "Erbium Laser Resurfacing in Chicago | Olivo Med Spa", description: "Erbium laser resurfacing at Olivo Med Spa in Logan Square, Chicago. Lighter ablative resurfacing for fine lines and texture, shorter recovery than CO2." },
    es: { name: "Resurfacing con láser Erbium", summary: "Resurfacing ablativo más ligero para líneas finas y textura, con una recuperación más corta que el CO2." },
    verify: ["Erbium device manufacturer and model: clinic to confirm", "Who performs Erbium resurfacing: clinic to confirm"],
  },
  {
    slug: "exion-rf-microneedling",
    name: "Exion RF microneedling",
    category: "skin-resurfacing",
    brand: "BTL",
    tag: "Face and body · A few days",
    headline: "Radiofrequency microneedling for texture, scars, pores, and tightening, on face and body.",
    summary: "Exion RF microneedling pairs fine needles with radiofrequency energy to treat texture, acne scars, enlarged pores, and skin laxity. Part of the BTL platform at Olivo Med Spa in Logan Square.",
    intro: [
      "Exion is BTL's radiofrequency microneedling handpiece. Insulated needles enter the skin to a set depth and deliver radiofrequency energy where collagen is made, without ablating the surface. That is why it suits people who want texture and tightening change without the peeling of a laser, and why it is used across a wider range of skin types.",
      "A typical plan is three sessions, about four weeks apart. Expect redness for a day or two and a rough feel for a few days. Because the clinic owns the full BTL platform, Dr. Olivo can pair it with Exion face or body tightening or Emface where that is the better answer.",
      "Candidacy, needle depth, and session count are set at your consultation. Dr. Olivo looks at the areas you want treated, your skin type, and any active acne or recent procedures, then decides whether Exion RF microneedling alone is the right plan or whether a resurfacing treatment should come first.",
    ],
    benefits: ["Texture, acne scars, pores, laxity in one plan", "Face, neck, chest, and body areas", "No surface ablation, so limited peeling", "Used across a wide range of skin types", "Pairs with Exion and Emface on the BTL platform"],
    concerns: ["skin-texture-scars", "sagging-skin", "fine-lines-wrinkles"],
    session: { duration: "About 45 minutes with numbing", sessions: "Three sessions, about four weeks apart", downtime: "A few days", feels: "Pressure and heat under topical numbing", results: "Texture and firmness change over the weeks after each session, with the fullest change a few months after the series", verify: "Session count, spacing, and timing: confirm with BTL clinical materials" },
    goodFor: ["Adults with acne scars, enlarged pores, or crepey skin", "People who want tightening without a laser recovery", "Anyone cleared at consultation, with skin type and active acne reviewed"],
    faqs: [
      { q: "How is RF microneedling different from regular microneedling?", a: "Standard microneedling makes tiny channels to trigger healing. RF microneedling adds radiofrequency heat through the needle tips, delivered at depth, which does more for tightening and scar remodeling in the same session." },
      { q: "Does it work on darker skin?", a: "RF microneedling delivers energy below the surface rather than to the pigment layer, so it is commonly used across skin types. Dr. Olivo confirms suitability and settings at consultation.", verify: "Skin-type range claim: confirm with BTL materials" },
      { q: "How many sessions do I need?", a: "Three is the usual series. Deeper acne scarring may call for more. Results build gradually because collagen remodels over months, so the fullest change shows well after the last session." },
      { q: "Where on the body can it be used?", a: "Face, neck, and chest are most common. It is also used on the abdomen, arms, and thighs for crepey skin or stretch marks, often alongside Exion body tightening." },
    ],
    related: ["exion-face", "exion-body", "opus-plasma", "emface"],
    image: { slot: "exion-rf-microneedling", alt: "Exion RF microneedling at Olivo Med Spa", fallback: "hands-1" },
    live: "/services/laserlight-treatments/microneedling-rf/",
    seo: { title: "Exion RF Microneedling in Chicago | Olivo Med Spa", description: "Exion RF microneedling at Olivo Med Spa in Logan Square, Chicago. Radiofrequency microneedling for texture, acne scars, pores, and tightening." },
    es: { name: "Microneedling con radiofrecuencia Exion", summary: "Microneedling con radiofrecuencia para textura, cicatrices, poros y firmeza, en rostro y cuerpo." },
    verify: ["Skin-type range and stretch mark use: confirm with BTL materials", "Who performs Exion RF microneedling: clinic to confirm"],
  },
  {
    slug: "opus-colibri",
    name: "Opus Colibri",
    category: "skin-resurfacing",
    brand: "Alma",
    tag: "Face · A few days",
    headline: "Precision plasma for small areas: eyelids, around the mouth, and other spots a full pass would miss.",
    summary: "Opus Colibri is Alma's fine-tipped plasma handpiece for small, detailed areas such as the eyelids and around the mouth. Physician-led precision resurfacing at Olivo Med Spa in Logan Square.",
    intro: [
      "Opus Colibri is the precision tip on the Opus platform. Where Opus Plasma treats the full face in a fractional grid, Colibri works point by point on the areas that need a careful hand: crepey upper and lower eyelids, lines around the mouth, and small scars. The plasma energy tightens and resurfaces a tiny zone at a time.",
      "Treatment is short, usually under thirty minutes for a single area, with topical numbing. Expect small dots or crusting for several days as the skin heals. It is often done on its own or alongside a full-face Opus Plasma session.",
      "Whether Colibri is right for your eyelids or mouth, and whether it should be combined with Botox Cosmetic or filler, is decided at your consultation. Dr. Olivo also reviews your eye history before any eyelid work and sets expectations for how the small treated points will look as they heal.",
    ],
    benefits: ["Eyelids, lip lines, and small scars", "Point-by-point precision", "Short treatment with topical numbing", "Pairs with a full-face Opus Plasma pass", "Physician-set depth for delicate skin"],
    concerns: ["fine-lines-wrinkles", "sagging-skin", "skin-texture-scars"],
    session: { duration: "About 20 to 30 minutes per area with numbing", sessions: "One to two sessions, about six weeks apart", downtime: "A few days", feels: "Sharp heat at each point under topical numbing", results: "Tightening and smoothing as the small treated zones heal over a few weeks", verify: "Colibri session count, spacing, and downtime: confirm with Alma protocol" },
    goodFor: ["Adults with crepey eyelid skin or lines around the mouth", "People who want to treat one small area rather than the full face", "Anyone cleared at consultation, with eye history reviewed for eyelid work"],
    faqs: [
      { q: "Can plasma really be used on the eyelids?", a: "Yes, with the right tip and settings. Colibri is designed for delicate areas. Dr. Olivo assesses the skin and sets depth accordingly, and the eyes are protected during treatment.", verify: "Eye protection protocol: clinic to confirm" },
      { q: "What does the healing look like?", a: "Small dark dots where each point was treated, with mild swelling around the eyes for a day or two. The dots flake off over five to seven days. Do not pick them." },
      { q: "How is it different from Opus Plasma?", a: "Same energy, different tip. Opus Plasma covers larger areas quickly in a fractional pattern. Colibri is a fine tip for spot work where precision matters more than coverage." },
      { q: "Is this a plasma pen?", a: "No. Opus Colibri is part of Alma's medical Opus platform with controlled energy delivery, used under physician oversight. Handheld plasma pens are a different category of device." },
    ],
    related: ["opus-plasma", "botox-and-xeomin", "erbium-resurfacing"],
    image: { slot: "opus-colibri", alt: "Opus Colibri precision plasma at Olivo Med Spa", fallback: "light-1" },
    live: "/services/opus-colibri/",
    seo: { title: "Opus Colibri Eyelid Plasma in Chicago | Olivo Med Spa", description: "Opus Colibri plasma at Olivo Med Spa in Logan Square, Chicago. Precision resurfacing for eyelids, lip lines, and small scars. Physician-led clinic since 2013." },
    es: { name: "Opus Colibri", summary: "Plasma de precisión para áreas pequeñas como los párpados y el contorno de la boca." },
    verify: ["Colibri indications for eyelids and perioral area: confirm with Alma materials", "Who performs Opus Colibri: clinic to confirm"],
  },
];
