// Wellness, medical programs, and the men's overview. See docs/CONTENT-RULES.md before editing.
import type { Service } from "../types";

export const wellnessServices: Service[] = [
  {
    slug: "iv-therapy",
    name: "IV therapy",
    category: "wellness",
    tag: "Wellness · About 45 minutes",
    headline: "Vitamin and hydration drips, administered by the clinical team in a quiet room.",
    summary: "IV therapy delivers fluids, vitamins, and minerals directly into the bloodstream. Drips are chosen for hydration, energy, or recovery, and administered by the clinical team at a physician-led clinic in Logan Square.",
    intro: [
      "An IV drip puts fluid and nutrients straight into the bloodstream, bypassing digestion. People book one after travel, illness, a hard week, or a long run, or as a regular part of how they look after themselves. Drips are built from a base of saline with added vitamins and minerals.",
      "A session takes about forty-five minutes to an hour. You sit in a chair, the line is placed by a clinician, and you rest. There is no downtime. The clinic offers several blends, and a consultation confirms which fits your goal and that IV therapy is appropriate for you.",
      "IV therapy is a wellness service, not a treatment for illness. Dr. Olivo reviews your history before your first drip, and candidacy and expectations are set at that visit.",
    ],
    benefits: ["Hydration and nutrients delivered directly", "About forty-five minutes, no downtime", "Several blends for different goals", "Administered by the clinical team", "Physician-reviewed before your first drip"],
    concerns: ["low-energy", "dull-tired-skin"],
    session: { duration: "About 45 to 60 minutes", sessions: "Single session; some people book monthly", downtime: "None", feels: "A small pinch when the line is placed, then a cool sensation", results: "Many people feel more hydrated the same day; effects vary by blend and person", verify: "Session length, blend list, and any effect claims: confirm with clinic" },
    goodFor: ["Adults who want hydration after travel, illness, or exertion", "People who find oral supplements hard to keep up with", "Anyone cleared at consultation, including a review of kidney and heart history"],
    faqs: [
      { q: "Who places the IV?", a: "A licensed clinician on the team. Dr. Olivo reviews your history before your first drip.", verify: "Confirm credentials of staff administering IVs" },
      { q: "Which drips do you offer?", a: "Several blends built around hydration, energy, recovery, and skin. The menu is reviewed at your visit.", verify: "Confirm blend menu with clinic" },
      { q: "Does it hurt?", a: "You feel a small pinch when the line goes in. Most people read or rest for the session." },
      { q: "How often can I come?", a: "That depends on the blend and your health. Many people book monthly. Your schedule is set with the clinical team.", verify: "Frequency guidance: confirm with clinic" },
    ],
    related: ["glp-1-weight-management", "hormone-therapy", "emsella"],
    image: { slot: "iv-therapy", alt: "IV therapy room at Olivo Med Spa", fallback: "room-2" },
    live: "/iv-therapy/",
    seo: { title: "IV Therapy in Logan Square, Chicago | Olivo Med Spa", description: "IV therapy at Olivo Med Spa in Logan Square: vitamin and hydration drips administered by the clinical team. Physician-led. About 45 minutes, no downtime." },
    es: { name: "Terapia intravenosa", summary: "Sueros de vitaminas e hidratación, administrados por el equipo clínico." },
    verify: ["Blend menu and ingredients: confirm with clinic", "Who administers IVs and physician review process: confirm with clinic", "Session length: confirm with clinic"],
  },
  {
    slug: "glp-1-weight-management",
    name: "Medical weight management with GLP-1",
    category: "wellness",
    tag: "Wellness · Physician-supervised",
    headline: "A physician-supervised weight management program built around GLP-1 medication, when it is right for you.",
    summary: "Medical weight management at Olivo Med Spa starts with a consultation and lab work. If a GLP-1 medication is appropriate, Dr. Olivo prescribes it as part of a supervised program with regular check-ins. Logan Square, Chicago.",
    intro: [
      "GLP-1 medications have changed the conversation about weight. They work by acting on appetite and how the body handles blood sugar. They are prescription medicines with real effects and real considerations, which is why the clinic offers them only inside a physician-supervised program.",
      "The program starts with a consultation and lab work. Dr. Olivo reviews your history, current medications, and goals, and decides whether a GLP-1 medication is appropriate. If it is, you begin at a starting dose with scheduled follow-ups to adjust the plan and monitor how you feel.",
      "Medication is one part of the program. Nutrition, movement, and, for some people, Emsculpt Neo for tone as weight changes, round it out. Candidacy and expectations are set at your consultation. No specific result is promised.",
    ],
    benefits: ["Physician-supervised from the first visit", "Consultation and lab work before any prescription", "Regular follow-ups and dose adjustments", "Nutrition and movement guidance included", "Pairs with Emsculpt Neo as weight changes"],
    concerns: ["stubborn-fat"],
    session: { duration: "Initial consultation about 45 minutes", sessions: "Ongoing program with scheduled follow-ups", downtime: "None", feels: "A small weekly injection, often self-administered at home after training", results: "Change happens over months and varies widely; progress is reviewed at each follow-up", verify: "Program structure, follow-up cadence, and administration details: confirm with clinic" },
    goodFor: ["Adults who have not reached their goal with diet and exercise alone", "People who want medical oversight and regular check-ins", "Anyone cleared at consultation and lab review"],
    faqs: [
      { q: "Which medication will I be prescribed?", a: "That is decided at your consultation after lab work. Several GLP-1 medications exist and Dr. Olivo chooses based on your history, if one is appropriate at all." },
      { q: "What are the side effects?", a: "Nausea, constipation, and reduced appetite are common, especially early. Dr. Olivo reviews the full list with you and adjusts dosing to manage them." },
      { q: "How long is the program?", a: "It varies. Many people stay on medication for months, with follow-ups throughout. The plan is reviewed regularly.", verify: "Program length and follow-up cadence: confirm with clinic" },
      { q: "Is this covered by insurance?", a: "Ask at your consultation. Financing available through Cherry. Terms are set by Cherry at application.", verify: "Insurance billing status: confirm with clinic" },
    ],
    related: ["emsculpt-neo", "hormone-therapy", "iv-therapy"],
    image: { slot: "glp-1-weight-management", alt: "Weight management consultation at Olivo Med Spa", fallback: "portrait" },
    live: "/glp-1/",
    seo: { title: "GLP-1 Weight Management in Chicago | Olivo Med Spa", description: "Physician-supervised weight management with GLP-1 medication at Olivo Med Spa in Logan Square, Chicago. Consultation and lab work first, follow-ups throughout." },
    es: { name: "Control de peso médico con GLP-1", summary: "Programa de control de peso supervisado por una médica, con consulta y análisis previos." },
    verify: ["Program details, medications offered, and follow-up cadence: to be confirmed by the clinic", "Whether nutrition guidance is included: confirm with clinic", "Insurance and financing wording: confirm with clinic"],
  },
  {
    slug: "hormone-therapy",
    name: "Hormone therapy",
    category: "wellness",
    tag: "Wellness · Physician-supervised",
    headline: "Physician-supervised hormone evaluation and replacement for adults, starting with lab work.",
    summary: "Hormone therapy at Olivo Med Spa begins with a consultation and blood work. Dr. Olivo reviews your symptoms and results and, when appropriate, prescribes and monitors hormone replacement. Logan Square, Chicago.",
    intro: [
      "Changes in sleep, energy, mood, weight, and libido in midlife can have many causes. Hormones are one. The clinic offers a physician-supervised evaluation: a conversation about your symptoms and history, then lab work to measure where your levels are.",
      "If the results and your symptoms point to hormone replacement, Dr. Olivo discusses the options, what they can and cannot address, and the monitoring involved. Treatment is individualized and reviewed at regular follow-ups with repeat labs.",
      "Hormone therapy is not right for everyone and it is never started without lab work and a medical review. Candidacy and expectations are set at your consultation.",
    ],
    benefits: ["Physician-led evaluation of symptoms and labs", "Lab work before any prescription", "Individualized plan", "Regular follow-ups with repeat labs", "Options and monitoring explained plainly"],
    concerns: ["low-energy"],
    session: { duration: "Initial consultation about 45 minutes", sessions: "Ongoing, with follow-ups and repeat labs", downtime: "None", feels: "A blood draw and a conversation; treatment format varies by plan", results: "Any change develops over weeks to months and is reviewed against your labs and symptoms", verify: "Consultation length, lab process, and treatment formats offered: confirm with clinic" },
    goodFor: ["Adults with midlife symptoms that may relate to hormone levels", "People who want a medical evaluation before deciding on treatment", "Anyone cleared at consultation after lab review"],
    faqs: [
      { q: "What does the first visit involve?", a: "A review of your symptoms and history, then an order for lab work. Results are discussed at a follow-up before any decision on treatment." },
      { q: "Do you treat both women and men?", a: "The evaluation is available to adults. Whether treatment is offered depends on your labs and history.", verify: "Confirm scope of patients treated with clinic" },
      { q: "What forms does treatment take?", a: "That depends on the plan Dr. Olivo recommends. Options are discussed at your follow-up along with their monitoring requirements.", verify: "Treatment formats offered (pellets, creams, injections): confirm with clinic" },
      { q: "How often are labs repeated?", a: "At intervals set by Dr. Olivo based on your plan. Monitoring is part of treatment." },
    ],
    related: ["glp-1-weight-management", "iv-therapy", "emsella"],
    image: { slot: "hormone-therapy", alt: "Hormone therapy consultation at Olivo Med Spa", fallback: "portrait" },
    live: "/hormone-replacement-therapy/",
    seo: { title: "Hormone Therapy in Logan Square, Chicago | Olivo Med Spa", description: "Physician-supervised hormone evaluation and replacement for adults at Olivo Med Spa in Logan Square, Chicago. Lab work first, regular follow-ups." },
    es: { name: "Terapia hormonal", summary: "Evaluación y reemplazo hormonal para adultos, supervisados por una médica, con análisis previos." },
    verify: ["Scope of hormone services, patients treated, and treatment formats: to be confirmed by the clinic", "Who conducts evaluations and prescribes: confirm with clinic", "All claims on this page require clinic review before launch"],
  },
  {
    slug: "emfemme-360",
    name: "Emfemme 360",
    category: "wellness",
    brand: "BTL",
    tag: "Intimate wellness · No downtime",
    headline: "A radiofrequency treatment for intimate wellness, about eight minutes, no downtime.",
    summary: "Emfemme 360 is a radiofrequency treatment for intimate wellness from BTL. Sessions are short, comfortable, and require no downtime. It is offered as part of a physician-led women's wellness plan in Logan Square.",
    intro: [
      "Emfemme 360 is part of the BTL platform at the clinic. It delivers radiofrequency energy in a controlled, 360-degree pattern to gently heat tissue as part of an intimate wellness plan. Sessions are short and comfortable, and there is no downtime.",
      "A typical plan is a short series of sessions spaced about a week apart, with each session taking around eight minutes. Many people pair Emfemme 360 with Emsella for pelvic floor strengthening. Dr. Olivo discusses whether that combination makes sense for you.",
      "This is a medical treatment, and it is discussed privately. Candidacy, what the treatment is used for, and expectations are set at a consultation with Dr. Olivo.",
    ],
    benefits: ["Radiofrequency treatment for intimate wellness", "Short sessions, about eight minutes", "No downtime", "Pairs with Emsella", "Physician-led and discussed privately"],
    concerns: ["pelvic-floor"],
    session: { duration: "About 8 minutes", sessions: "A short series, about a week apart", downtime: "None", feels: "Gentle warmth", results: "Change is typically noticed over the weeks after the series", verify: "Session length, series count, and all outcome wording: confirm with BTL Emfemme 360 cleared-indication materials" },
    goodFor: ["Adult women considering an intimate wellness plan", "People already using Emsella for pelvic floor strengthening", "Anyone cleared at consultation"],
    faqs: [
      { q: "What does the session feel like?", a: "Gentle warmth. It is short and most people describe it as comfortable." },
      { q: "Is there downtime?", a: "No. You can return to your normal day." },
      { q: "How is it different from Emsella?", a: "Emsella strengthens the pelvic floor muscles from a chair, fully clothed. Emfemme 360 is a radiofrequency treatment for intimate wellness. They are often used together." },
      { q: "How many sessions?", a: "A short series, usually about a week apart. Dr. Olivo sets your plan at consultation.", verify: "Confirm with BTL protocol" },
    ],
    related: ["emsella", "hormone-therapy", "exion-body"],
    image: { slot: "emfemme-360", alt: "Emfemme 360 treatment room at Olivo Med Spa", fallback: "room-3" },
    live: "/rejuvanate-vaginal-rejuvenation/", // legacy URL on the current site, audit-exempt
    seo: { title: "Emfemme 360 in Logan Square, Chicago | Olivo Med Spa", description: "Emfemme 360 at Olivo Med Spa in Logan Square is a radiofrequency treatment for intimate wellness. Short sessions, no downtime, physician-led. Book a consult." },
    es: { name: "Emfemme 360", summary: "Tratamiento de radiofrecuencia para el bienestar íntimo, en sesiones cortas y sin recuperación." },
    verify: ["COUNSEL MUST APPROVE ALL WORDING ON THIS PAGE before launch: use only the cleared indication and no anatomical terms in copy", "Session length, series count, and pairing with Emsella: confirm with BTL materials", "Live URL contains restricted wording; route it to this slug in the 301 map", "Who performs Emfemme 360: confirm with clinic"],
  },
  {
    slug: "for-men",
    name: "Treatments for men",
    category: "body-contouring",
    tag: "For men · Body, sweat, hair, face",
    headline: "Treatments men book most: Emsculpt Neo, Miradry, laser hair removal, Botox Cosmetic, and Hydrafacial.",
    summary: "Men book at the clinic for practical reasons. This page covers what they book most: Emsculpt Neo for muscle and fat, Miradry for underarm sweat, laser hair removal, Botox Cosmetic, and Hydrafacial, all physician-led in Logan Square.",
    intro: [
      "Men come to the clinic for practical reasons. They want a flatter midsection, to stop sweating through shirts, to lose hair on the back or neck, or to look less tired without anyone noticing why. The treatments below are the ones men book most, and each one is planned by Dr. Olivo the same way as for any patient.",
      "Emsculpt Neo builds muscle and reduces fat on the abdomen, arms, and legs in thirty-minute sessions. Miradry offers lasting reduction of underarm sweat, usually in one or two visits. Laser hair removal handles the back, shoulders, neck, and chest over a series of sessions.",
      "Botox Cosmetic softens forehead and frown lines while keeping expression. Hydrafacial clears and hydrates skin in about thirty minutes with no downtime. Candidacy and expectations for each are set at a consultation.",
    ],
    benefits: ["Emsculpt Neo for muscle and fat", "Miradry for underarm sweat", "Laser hair removal for back, neck, and chest", "Botox Cosmetic for forehead and frown lines", "Hydrafacial for clear, hydrated skin"],
    concerns: ["stubborn-fat", "excessive-sweating", "unwanted-hair"],
    session: { duration: "Varies by treatment, about 30 minutes for most", sessions: "Set per treatment at consultation", downtime: "None to minimal for the treatments listed", feels: "Depends on the treatment; each is described on its own page", results: "Timing depends on the treatment and is reviewed at consultation", verify: "Per-treatment facts live on each treatment page; confirm men's menu with clinic" },
    goodFor: ["Men who want a specific, practical result", "Men who have not been to a med spa before", "Anyone cleared at consultation"],
    faqs: [
      { q: "Is the clinic comfortable for men?", a: "Yes. Treatment rooms are private and appointments are one on one. Many patients are men.", verify: "Patient mix statement: confirm with clinic or remove" },
      { q: "Which treatment should I start with?", a: "Start with a consultation. Dr. Olivo will ask what bothers you and suggest the one or two treatments that address it." },
      { q: "Does Botox Cosmetic look natural on men?", a: "Yes, when dosed for a male face. The goal is fewer lines, not a change in expression." },
      { q: "How long does laser hair removal take?", a: "A series of sessions spaced several weeks apart. Back and shoulders take longer per session than the neck.", verify: "Laser hair removal device and session details: confirm with clinic" },
    ],
    related: ["emsculpt-neo", "miradry", "botox-and-xeomin"],
    image: { slot: "for-men", alt: "Treatment room prepared for a men's appointment at Olivo Med Spa", fallback: "room-1" },
    live: "/for-men/",
    seo: { title: "Med Spa Treatments for Men in Chicago | Olivo Med Spa", description: "Treatments for men at Olivo Med Spa in Logan Square: Emsculpt Neo, Miradry, laser hair removal, Botox Cosmetic, and Hydrafacial. Physician-led since 2013." },
    es: { name: "Tratamientos para hombres", summary: "Los tratamientos que más reservan los hombres: Emsculpt Neo, Miradry, depilación láser, Botox Cosmetic e Hydrafacial." },
    verify: ["Men's menu and which treatments to feature: confirm with clinic", "Laser hair removal device and protocol: confirm with clinic", "Patient mix statements: confirm or remove"],
  },
];
