// Spanish translations for the body and face services, merged with the
// wellness set from services-1b.ts. Keyed by the English slug. Facts mirror
// content/services/body.ts and face.ts. See docs/CONTENT-RULES.md before editing.
import type { ServiceEs } from "./types";
import { servicesEs1b } from "./services-1b";

const a: Record<string, ServiceEs> = {
  "emsculpt-neo": {
    name: "Emsculpt Neo",
    tag: "Cuerpo · Sin recuperación",
    headline: "Desarrolla músculo y reduce grasa en la misma sesión de 30 minutos, sin cirugía.",
    summary: "Emsculpt Neo combina el calor de la radiofrecuencia con contracciones musculares electromagnéticas de alta intensidad para trabajar la grasa y el músculo a la vez. Cuatro sesiones, sin recuperación, en una clínica dirigida por una médica en Logan Square.",
    intro: [
      "Emsculpt Neo es el tratamiento corporal que las personas piden por su nombre. El aplicador se coloca sobre el abdomen, los glúteos, los brazos, las pantorrillas o los muslos y emite dos energías en una sola pasada: radiofrecuencia que calienta el tejido y pulsos electromagnéticos que contraen el músculo con más fuerza de la que usted puede lograr de forma voluntaria. Usted permanece en reposo. El equipo hace el trabajo.",
      "Un plan suele constar de cuatro sesiones, con cinco a diez días de separación, de unos treinta minutos cada una. La mayoría de las personas retoma su día de inmediato. Como la clínica cuenta con la plataforma BTL completa, la Dra. Olivo puede combinar Emsculpt Neo con Exion para reafirmar la piel cuando esa es la respuesta indicada.",
      "Emsculpt Neo no es un tratamiento para bajar de peso. Está pensado para personas que ya están cerca de su objetivo y quieren más definición en una zona específica.",
    ],
    benefits: ["Músculo y grasa tratados en una sola sesión", "Unos treinta minutos por tratamiento", "Sin agujas, anestesia ni recuperación", "Abdomen, glúteos, brazos, muslos, pantorrillas", "Plan dirigido por una médica, no un menú"],
    session: { duration: "Unos 30 minutos", sessions: "Cuatro sesiones, con cinco a diez días de separación", downtime: "Ninguna", feels: "Contracciones musculares intensas con calor, como un entrenamiento exigente que usted no está haciendo", results: "La mayoría de las personas nota cambios en las semanas posteriores a la serie, a medida que el músculo se desarrolla y el cuerpo elimina la grasa tratada" },
    goodFor: ["Adultos cerca de su peso objetivo que buscan definición", "Personas que no pueden dedicar más tiempo al gimnasio", "Cualquier persona autorizada en la consulta, sin implantes metálicos en la zona"],
    faqs: [
      { q: "¿Emsculpt Neo duele?", a: "Es intenso más que doloroso. Las contracciones se sienten como un entrenamiento fuerte y la radiofrecuencia se siente como calor. La intensidad se aumenta de forma gradual y usted tiene el control." },
      { q: "¿Cuántas sesiones necesito?", a: "Una serie estándar es de cuatro sesiones, con cinco a diez días de separación. La Dra. Olivo define el plan en su consulta y puede ajustarlo según la zona y su objetivo." },
      { q: "¿Requiere tiempo de recuperación?", a: "No. Puede conducir a casa y volver al trabajo. Algunas personas sienten una leve molestia muscular al día siguiente, como después de entrenar." },
      { q: "¿En qué se diferencia de Emsculpt?", a: "Emsculpt Neo suma radiofrecuencia a las contracciones musculares del Emsculpt original, por lo que trabaja la grasa además del músculo en la misma sesión." },
    ],
    seo: { title: "Emsculpt Neo en Logan Square, Chicago | Olivo Med Spa", description: "Emsculpt Neo en Logan Square, Chicago. Desarrolla músculo y reduce grasa en una sesión de 30 minutos, sin recuperación. Dirigido por una médica." },
  },
  "exion-body": {
    name: "Exion para el cuerpo",
    tag: "Cuerpo · Recuperación mínima",
    headline: "Reafirma la piel del cuerpo con radiofrecuencia y ultrasonido dirigido, sin cirugía.",
    summary: "Exion para el cuerpo utiliza radiofrecuencia monopolar con ultrasonido dirigido para calentar las capas profundas de la piel y favorecer el colágeno. Una serie de sesiones cortas con recuperación mínima, en una clínica dirigida por una médica en Logan Square.",
    intro: [
      "Exion para el cuerpo es la respuesta para la piel dentro de la plataforma BTL. Mientras Emsculpt Neo trabaja el músculo y la grasa, Exion trabaja la piel que los cubre. El aplicador emite radiofrecuencia y ultrasonido dirigido a la vez para calentar las capas profundas de la piel, lo que favorece el colágeno y la elastina con el tiempo. Las zonas más comunes son el abdomen, los brazos, los muslos, las rodillas y los glúteos.",
      "Un plan suele ser una serie corta de sesiones, con unas semanas de separación. Cada sesión toma unos treinta minutos según la zona. El tratamiento se siente como un calor profundo. La recuperación es mínima o nula, y la mayoría de las personas retoma su día justo después.",
      "La Dra. Olivo suele combinar Exion con Emsculpt Neo cuando alguien busca tono y una piel más firme. La candidatura y las expectativas se definen en una consulta, no a partir de un menú.",
    ],
    benefits: ["Radiofrecuencia y ultrasonido en un solo aplicador", "Reafirmación de la piel en abdomen, brazos, muslos y más", "Sin agujas ni anestesia", "Recuperación mínima", "Se combina con Emsculpt Neo"],
    session: { duration: "Unos 30 minutos por zona", sessions: "Una serie de sesiones, con unas semanas de separación", downtime: "Mínima", feels: "Calor profundo y constante sobre la zona tratada", results: "La mayoría de las personas nota cambios graduales en los meses posteriores a la serie, a medida que se forma colágeno" },
    goodFor: ["Adultos con flacidez leve a moderada en la piel del cuerpo", "Personas que buscan una piel más firme tras cambios de peso o un embarazo", "Cualquier persona autorizada en la consulta, donde la Dra. Olivo confirma la candidatura"],
    faqs: [
      { q: "¿Qué se siente con Exion?", a: "Un calor que aumenta durante la sesión. El aplicador se desplaza sobre la zona y la temperatura se monitorea en todo momento. La mayoría de las personas lo describe como cómodo." },
      { q: "¿En qué se diferencia Exion de Emsculpt Neo?", a: "Emsculpt Neo trabaja el músculo y la grasa. Exion trabaja la calidad y la firmeza de la piel. Muchos planes usan ambos, y la Dra. Olivo decide el orden en la consulta." },
      { q: "¿Cuántas sesiones necesitaré?", a: "Depende de la zona y de su piel. Lo habitual es una serie de varias sesiones. Su plan se define en la consulta." },
      { q: "¿Requiere tiempo de recuperación?", a: "Mínimo o ninguno. La zona puede verse rosada o sentirse tibia por un rato después. Puede volver al trabajo el mismo día." },
    ],
    seo: { title: "Exion para reafirmar el cuerpo en Chicago | Olivo Med Spa", description: "Exion para el cuerpo en Olivo Med Spa, Logan Square: radiofrecuencia y ultrasonido para reafirmar la piel del abdomen, brazos y muslos. Reserve una consulta." },
  },
  "emsella": {
    name: "Emsella",
    tag: "Suelo pélvico · Con ropa",
    headline: "Fortalece los músculos del suelo pélvico desde una silla, con la ropa puesta, en unos 28 minutos.",
    summary: "Emsella es una silla que utiliza energía electromagnética para contraer los músculos del suelo pélvico miles de veces en una sola sesión. Es un apoyo para personas que manejan la incontinencia urinaria. Usted permanece con la ropa puesta. Dirigido por una médica en Logan Square.",
    intro: [
      "Emsella es una silla. Usted se sienta en ella, con la ropa puesta, y emite pulsos electromagnéticos que contraen los músculos del suelo pélvico muchas más veces de las que podría lograr por su cuenta. Cada sesión dura unos 28 minutos. No hay que desvestirse y no hay nada interno.",
      "Un suelo pélvico débil es común después del parto, con la edad y tras ciertas cirugías, y suele manifestarse como pérdidas de orina al toser, reír o correr. Emsella se utiliza para fortalecer esos músculos como parte de un plan de apoyo para la incontinencia urinaria.",
      "Una serie típica es de seis sesiones en unas tres semanas. La Dra. Olivo revisa su historial en una consulta y confirma si Emsella es adecuado para usted. Ahí se definen la candidatura y las expectativas.",
    ],
    benefits: ["Fortalecimiento de los músculos del suelo pélvico sin ejercicio", "Con la ropa puesta, en una silla, unos 28 minutos", "Sin recuperación", "Apoyo para la incontinencia urinaria", "Se combina con Emfemme 360"],
    session: { duration: "Unos 28 minutos", sessions: "Normalmente seis sesiones en unas tres semanas", downtime: "Ninguna", feels: "Hormigueo y contracciones intensas del suelo pélvico mientras permanece en la silla", results: "Muchas personas reportan cambios a lo largo de la serie y en las semanas posteriores" },
    goodFor: ["Adultos con pérdidas de orina relacionadas con un suelo pélvico débil", "Mujeres después del parto o durante la menopausia", "Cualquier persona autorizada en la consulta, sin implantes metálicos o electrónicos en la zona"],
    faqs: [
      { q: "¿Tengo que desvestirme?", a: "No. Se sienta en la silla con su ropa habitual. No se introduce nada y nada toca la piel directamente." },
      { q: "¿Qué se siente?", a: "Hormigueo y contracciones intensas del suelo pélvico. No es doloroso. La intensidad se ajusta a usted durante la sesión." },
      { q: "¿Cuántas sesiones?", a: "Una serie común es de seis sesiones, dos por semana durante unas tres semanas. La Dra. Olivo define su plan en la consulta." },
      { q: "¿Los hombres pueden usar Emsella?", a: "Emsella se utiliza en hombres y mujeres con debilidad del suelo pélvico. La candidatura se confirma en la consulta." },
    ],
    seo: { title: "Emsella para el suelo pélvico en Chicago | Olivo Med Spa", description: "Emsella en Olivo Med Spa, Logan Square, fortalece el suelo pélvico desde una silla, con la ropa puesta, en 28 minutos. Apoyo para la incontinencia urinaria." },
  },
  "kybella": {
    name: "Kybella",
    tag: "Inyectable · Debajo del mentón",
    headline: "Inyecciones que descomponen la grasa debajo del mentón, para definir el perfil sin cirugía.",
    summary: "Kybella es un inyectable de ácido desoxicólico, una molécula que ayuda al cuerpo a descomponer la grasa. La Dra. Olivo lo utiliza para el volumen debajo del mentón. Unas pocas sesiones cortas, con alrededor de un mes de separación, en Logan Square.",
    intro: [
      "El volumen debajo del mentón no siempre responde a la dieta o al ejercicio. Kybella es un tratamiento inyectable para tratarlo. El ingrediente activo es el ácido desoxicólico, que se encuentra de forma natural en el cuerpo y ayuda a descomponer la grasa de los alimentos. Inyectado en la grasa debajo del mentón, descompone las células de grasa de esa zona, y el cuerpo las elimina en las semanas siguientes.",
      "Una sesión toma unos veinte minutos. La mayoría de las personas necesita más de una, con alrededor de un mes de separación, y el número depende de cuánto volumen haya que tratar. La hinchazón posterior es esperada y puede durar una semana o más. Es parte de cómo funciona.",
      "La Dra. Olivo delimita la zona de tratamiento en su consulta, donde se definen la candidatura y las expectativas. Si la piel flácida es el problema principal, puede orientarle hacia otra opción.",
    ],
    benefits: ["Actúa sobre la grasa debajo del mentón sin cirugía", "Unos veinte minutos por sesión", "Sin incisiones ni anestesia general", "Los resultados se construyen a lo largo de unas pocas sesiones", "Evaluación por una médica primero"],
    session: { duration: "Unos 20 minutos", sessions: "De dos a cuatro sesiones, con alrededor de un mes de separación", downtime: "Unos días", feels: "Pequeñas inyecciones con escozor, y luego una sensación de calor y tirantez a medida que la zona se inflama", results: "El cambio suele ser visible después de dos o más sesiones, a medida que el cuerpo elimina la grasa tratada" },
    goodFor: ["Adultos con volumen moderado debajo del mentón", "Personas que buscan una línea de la mandíbula y del cuello más definida sin cirugía", "Cualquier persona autorizada en la consulta, donde se revisan la flacidez de la piel y la anatomía"],
    faqs: [
      { q: "¿Kybella duele?", a: "Siente las inyecciones y luego un escozor o ardor que se calma en minutos. La crema anestésica y el hielo ayudan. Después hay hinchazón y sensibilidad durante varios días." },
      { q: "¿Cuánta hinchazón debo esperar?", a: "Una hinchazón notoria durante alrededor de una semana es normal, a veces más tras la primera sesión. Planifique en torno a sus eventos. Desaparece por sí sola." },
      { q: "¿Cuántas sesiones?", a: "La mayoría de las personas necesita de dos a cuatro, con alrededor de un mes de separación. El número depende de cuánto volumen haya." },
      { q: "¿Y la piel flácida debajo del mentón?", a: "Kybella trata la grasa, no la piel. Si la flacidez es el problema principal, la Dra. Olivo puede sugerir Exion o Emface en su lugar, o una combinación." },
    ],
    seo: { title: "Kybella para debajo del mentón en Chicago | Olivo Med Spa", description: "Kybella en Olivo Med Spa, Logan Square: inyecciones de ácido desoxicólico para reducir el volumen debajo del mentón sin cirugía. Dirigido por una médica." },
  },
  "laser-lipo": {
    name: "Lipo láser",
    tag: "Cuerpo · Sin recuperación",
    headline: "Sesiones de láser de baja intensidad dirigidas a zonas localizadas, sin agujas y sin recuperación.",
    summary: "La lipo láser utiliza luz láser de baja intensidad aplicada sobre la piel en zonas como el abdomen, los flancos o los muslos. Las sesiones son cortas y cómodas, y no hay recuperación. Una opción conservadora que se revisa en consulta en Logan Square.",
    intro: [
      "La lipo láser es una sesión no invasiva en la que se colocan almohadillas o paletas que emiten luz láser de baja intensidad sobre la zona de tratamiento. La luz se aplica sobre la piel durante un tiempo definido. Nada perfora la piel y no hay un calor que usted note. Las sesiones suelen programarse como una serie.",
      "Es una opción suave. No elimina la grasa como lo hace la cirugía, y no sustituye la pérdida de peso. Quienes la eligen suelen buscar un cambio modesto en una zona específica y valoran un tratamiento sin recuperación.",
      "La Dra. Olivo revisa si la lipo láser, Emsculpt Neo u otro plan se ajusta a su objetivo en una consulta, donde se definen la candidatura y las expectativas.",
    ],
    benefits: ["No invasiva, aplicada sobre la piel", "Sesiones cortas, sin recuperación", "Cómoda, sin calor ni agujas", "Suele combinarse con Emsculpt Neo", "Plan definido en la consulta"],
    session: { duration: "Unos 20 a 40 minutos", sessions: "Una serie de sesiones a lo largo de varias semanas", downtime: "Ninguna", feels: "Poco o nada; las almohadillas descansan sobre la piel", results: "Cualquier cambio es gradual y modesto, y depende de la serie y de sus hábitos" },
    goodFor: ["Adultos cerca de su peso objetivo con una zona pequeña y específica", "Personas que buscan una opción sin recuperación", "Cualquier persona autorizada en la consulta"],
    faqs: [
      { q: "¿La lipo láser es lo mismo que la liposucción?", a: "No. La liposucción es una cirugía que extrae grasa. La lipo láser es un tratamiento de luz no invasivo que se aplica sobre la piel. Las expectativas son distintas y la Dra. Olivo se las explicará." },
      { q: "¿Duele?", a: "No. La mayoría de las personas siente poco o nada. Usted permanece en reposo mientras las almohadillas descansan sobre la zona." },
      { q: "¿Cuántas sesiones?", a: "Se ofrece como una serie. El número y el calendario se definen en la consulta según su zona y su objetivo." },
      { q: "¿Debo elegir lipo láser o Emsculpt Neo?", a: "Hacen cosas distintas. Emsculpt Neo desarrolla músculo y reduce grasa con una energía más fuerte. La lipo láser es más suave. La Dra. Olivo recomienda uno o ambos según su objetivo." },
    ],
    seo: { title: "Lipo láser en Logan Square, Chicago | Olivo Med Spa", description: "Lipo láser en Olivo Med Spa, Logan Square: láser de baja intensidad, no invasivo, para zonas localizadas, sin agujas ni recuperación. Dirigido por una médica." },
  },
  "miradry": {
    name: "Miradry",
    tag: "Axilas · Recuperación mínima",
    headline: "Reducción duradera del sudor y el olor de las axilas, normalmente en una o dos sesiones.",
    summary: "Miradry utiliza energía de microondas controlada para actuar sobre las glándulas de sudor y olor de la axila. La mayoría de las personas necesita una o dos sesiones. Una opción dirigida por una médica en Logan Square para quienes ya no quieren lidiar con la sudoración intensa de las axilas.",
    intro: [
      "El sudor de las axilas es un problema diario para muchas personas, y los antitranspirantes tienen un alcance limitado. Miradry adopta un enfoque distinto. Una pieza de mano emite energía de microondas hacia la capa de la piel donde se ubican las glándulas de sudor y olor, mientras un sistema de enfriamiento protege la superficie. Las glándulas tratadas no vuelven a crecer, y por eso la reducción es duradera.",
      "Primero se anestesia la axila. Una sesión toma alrededor de una hora. La mayoría de las personas necesita una o dos sesiones, y la segunda, si hace falta, se programa unos tres meses después. La hinchazón, la molestia y el entumecimiento en la zona son normales durante unos días a unas semanas.",
      "Miradry es solo para las axilas. La Dra. Olivo revisa su historial y su patrón de sudoración en una consulta, donde se definen la candidatura y las expectativas.",
    ],
    benefits: ["Reducción duradera del sudor y el olor de las axilas", "Normalmente una o dos sesiones", "No quirúrgico, con anestesia local", "Sin inyecciones ni recetas continuas", "Retorno a la mayoría de las actividades en pocos días"],
    session: { duration: "Unos 60 minutos", sessions: "Una o dos sesiones, con unos tres meses de separación", downtime: "Mínima", feels: "Presión y succión tras la anestesia; molestia e hinchazón durante unos días después", results: "Muchas personas notan menos sudor poco después de la primera sesión, con el efecto completo en las semanas siguientes" },
    goodFor: ["Adultos a quienes les incomoda el sudor o el olor de las axilas", "Personas que buscan una alternativa a las inyecciones repetidas", "Cualquier persona autorizada en la consulta"],
    faqs: [
      { q: "¿Cuánto dura la reducción?", a: "Las glándulas de sudor tratadas se eliminan y no se regeneran, por lo que la reducción es duradera. Algunas personas eligen una segunda sesión para llegar al nivel que buscan." },
      { q: "¿Duele?", a: "La axila se anestesia con anestésico local, así que el tratamiento en sí es tolerable. Después, espere molestia, hinchazón y algo de entumecimiento durante días a semanas." },
      { q: "¿Necesito las glándulas de sudor de las axilas?", a: "Las axilas contienen una pequeña parte de las glándulas de sudor del cuerpo, por lo que el cuerpo sigue regulando la temperatura con normalidad." },
      { q: "¿Qué tan pronto puedo volver al trabajo?", a: "La mayoría de las personas vuelve al trabajo al día siguiente. Planifique unos días sin ejercicio intenso mientras baja la hinchazón." },
    ],
    seo: { title: "Miradry para el sudor axilar en Chicago | Olivo Med Spa", description: "Miradry en Olivo Med Spa, Logan Square, usa energía de microondas para reducir de forma duradera el sudor y el olor de las axilas, en una o dos sesiones." },
  },
  "emface": {
    name: "Emface",
    tag: "Rostro · Sin recuperación",
    headline: "Eleva y tonifica el rostro con radiofrecuencia y estimulación muscular sincronizadas, sin agujas.",
    summary: "Emface aplica radiofrecuencia y estimulación muscular facial al mismo tiempo para trabajar la piel y los músculos elevadores que están debajo. Veinte minutos, cuatro sesiones, sin agujas, sin recuperación. Dirigido por una médica en Logan Square.",
    intro: [
      "Emface es el tratamiento facial de la familia BTL que trabaja el músculo además de la piel. Unas almohadillas pequeñas se colocan en la frente y las mejillas. Emiten radiofrecuencia sincronizada, que calienta la piel y favorece el colágeno, y estimulación eléctrica que contrae los músculos faciales encargados de elevar. Nada perfora la piel.",
      "Una sesión dura unos veinte minutos. Un plan estándar es de cuatro sesiones, con alrededor de una semana de separación. Usted siente calor y un tirón vibrante a medida que los músculos se contraen. Puede maquillarse y retomar su día de inmediato.",
      "Emface está pensado para personas que buscan un aspecto elevado y descansado sin inyectables, o que quieren mantener los resultados que ya tienen. La candidatura y las expectativas se definen en una consulta con la Dra. Olivo.",
    ],
    benefits: ["Piel y músculos elevadores tratados a la vez", "Sin agujas, unos veinte minutos", "Cuatro sesiones, sin recuperación", "Frente, mejillas y línea de la mandíbula", "Se combina con inyectables o Exion"],
    session: { duration: "Unos 20 minutos", sessions: "Cuatro sesiones, con alrededor de una semana de separación", downtime: "Ninguna", feels: "Calor con un tirón rítmico a medida que los músculos faciales se contraen", results: "La mayoría de las personas nota cambios en las semanas posteriores a la serie, a medida que se forma colágeno y mejora el tono muscular" },
    goodFor: ["Adultos que notan flacidez incipiente o un aspecto cansado", "Personas que prefieren una opción sin agujas", "Cualquier persona autorizada en la consulta, sin implantes metálicos o electrónicos en la zona"],
    faqs: [
      { q: "¿Emface reemplaza a Botox Cosmetic o a los rellenos?", a: "No. Funciona de otra manera, sobre la calidad de la piel y el tono muscular. Muchas personas los combinan. La Dra. Olivo le dirá qué se ajusta a su rostro." },
      { q: "¿Duele?", a: "No. Siente calor y contracciones musculares. La intensidad se ajusta a usted." },
      { q: "¿Cuántas sesiones?", a: "Lo estándar son cuatro, con alrededor de una semana de separación. Algunas personas vuelven después para mantenimiento." },
      { q: "¿Requiere tiempo de recuperación?", a: "Ninguno. La piel puede verse ligeramente enrojecida por un corto tiempo. Puede maquillarse justo después." },
    ],
    seo: { title: "Emface en Logan Square, Chicago | Olivo Med Spa", description: "Emface en Olivo Med Spa, Logan Square, eleva y tonifica el rostro con radiofrecuencia y estimulación muscular. 20 minutos, sin agujas, sin recuperación." },
  },
  "exion-face": {
    name: "Exion para el rostro",
    tag: "Rostro · Recuperación mínima",
    headline: "Radiofrecuencia y ultrasonido para una piel facial más firme y suave, sin agujas.",
    summary: "Exion para el rostro combina radiofrecuencia monopolar con ultrasonido dirigido para calentar la piel profunda y favorecer el colágeno, la elastina y la hidratación. Una serie corta, recuperación mínima, sin agujas. Dirigido por una médica en Logan Square.",
    intro: [
      "Exion para el rostro es la vertiente sin agujas de la plataforma Exion. Un aplicador liso se desliza sobre el rostro y el cuello, emitiendo radiofrecuencia y ultrasonido dirigido a la vez. La energía calienta la piel profunda, lo que favorece el colágeno y la elastina y ayuda a que la piel retenga más humedad. Las zonas de tratamiento incluyen las mejillas, la línea de la mandíbula, debajo de los ojos y el cuello.",
      "Las sesiones toman unos treinta minutos y se espacian unas semanas. El tratamiento se siente como un masaje tibio. La piel puede verse rosada por un corto tiempo después, y la mayoría de las personas retoma su día de inmediato.",
      "Para un trabajo de textura más profundo, la misma plataforma ofrece microneedling con radiofrecuencia Exion. La Dra. Olivo decide cuál es el adecuado para usted en una consulta, donde se definen la candidatura y las expectativas.",
    ],
    benefits: ["Radiofrecuencia y ultrasonido, sin agujas", "Piel más firme en rostro, línea de la mandíbula y cuello", "Unos treinta minutos", "Recuperación mínima", "Se combina con Emface e inyectables"],
    session: { duration: "Unos 30 minutos", sessions: "Una serie de sesiones, con unas semanas de separación", downtime: "Mínima", feels: "Calor constante, como un masaje facial tibio", results: "La mayoría de las personas nota firmeza y luminosidad de forma gradual en los meses posteriores a la serie" },
    goodFor: ["Adultos con flacidez incipiente o piel apagada y deshidratada", "Personas que buscan un paso sin agujas antes de los inyectables o entre ellos", "Cualquier persona autorizada en la consulta"],
    faqs: [
      { q: "¿Exion es lo mismo que el microneedling?", a: "Esta página trata del tratamiento Exion sin agujas. La plataforma también ofrece microneedling con radiofrecuencia Exion, que usa agujas finas para una textura más profunda. La Dra. Olivo recomienda uno según su piel." },
      { q: "¿Duele?", a: "No. Se siente tibio. La temperatura se monitorea para que se mantenga cómoda." },
      { q: "¿Cuántas sesiones?", a: "Lo habitual son varias sesiones, con unas semanas de separación. Su plan se define en la consulta." },
      { q: "¿Puedo maquillarme después?", a: "Sí, normalmente el mismo día. La piel puede estar ligeramente rosada por un corto tiempo." },
    ],
    seo: { title: "Exion para el rostro en Chicago | Olivo Med Spa", description: "Exion para el rostro en Olivo Med Spa, Logan Square: radiofrecuencia y ultrasonido para reafirmar la piel facial sin agujas y con recuperación mínima." },
  },
  "pdo-threads": {
    name: "Hilos PDO",
    tag: "Rostro · Unos días",
    headline: "Hilos absorbibles colocados bajo la piel para elevar y sostener, sin cirugía.",
    summary: "Los hilos PDO son suturas finas absorbibles que se colocan bajo la piel para elevar zonas con flacidez y estimular el colágeno a medida que se disuelven. Una sola visita con unos días de recuperación, realizada en una clínica dirigida por una médica en Logan Square.",
    intro: [
      "Los hilos PDO están hechos de polidioxanona, el mismo material que se usa en las suturas quirúrgicas absorbibles. Colocados bajo la piel con una cánula fina, brindan soporte mecánico inmediato a zonas que han empezado a descender, como las mejillas, la línea de la mandíbula, los carrillos, las cejas y el cuello. A medida que los hilos se disuelven a lo largo de meses, la piel forma colágeno a lo largo de su trayecto.",
      "La visita toma alrededor de una hora, incluida la anestesia. Espere algo de hinchazón, moretones y tirantez durante unos días, y una sensación de tirón durante una o dos semanas. Los resultados son visibles de inmediato y se asientan en las semanas siguientes.",
      "Los hilos son una opción entre varias. La Dra. Olivo los compara con Emface, Exion y los rellenos en una consulta, donde se definen la candidatura y las expectativas.",
    ],
    benefits: ["Elevación inmediata en la zona tratada", "Apoyo al colágeno a medida que los hilos se disuelven", "Una sola visita, sin incisiones", "Mejillas, línea de la mandíbula, cejas y cuello", "Se combina con rellenos o Emface"],
    session: { duration: "Unos 60 minutos, incluida la anestesia", sessions: "Una sola sesión; algunas personas repiten después de un año o más", downtime: "Unos días", feels: "Presión y tirón tras la anestesia; sensibilidad y tirantez durante varios días", results: "La elevación es visible de inmediato; el efecto del colágeno se desarrolla en los meses siguientes" },
    goodFor: ["Adultos con flacidez leve a moderada en la parte inferior del rostro o en las cejas", "Personas que buscan una elevación sin cirugía", "Cualquier persona autorizada en la consulta, donde se revisan el grosor de la piel y los objetivos"],
    faqs: [
      { q: "¿Cuánto duran los hilos PDO?", a: "Los hilos en sí se disuelven en unos seis meses. El colágeno que estimulan puede seguir sosteniendo la zona por más tiempo. El tiempo varía según la persona." },
      { q: "¿Duele?", a: "La zona se anestesia primero. Siente presión y tirón. La sensibilidad posterior se maneja con analgésicos de venta libre." },
      { q: "¿Qué debo evitar después?", a: "Movimientos amplios de la boca, dormir boca abajo, faciales y ejercicio intenso durante unas dos semanas. Recibe indicaciones de cuidado por escrito." },
      { q: "¿Hilos o relleno?", a: "Los hilos elevan. El relleno aporta volumen. Muchos rostros necesitan un poco de ambos, y la Dra. Olivo le mostrará dónde ayuda cada uno." },
    ],
    seo: { title: "Hilos PDO en Logan Square, Chicago | Olivo Med Spa", description: "Hilos PDO en Olivo Med Spa, Logan Square: elevan mejillas, línea de la mandíbula y cuello con suturas absorbibles, sin cirugía. Dirigido por una médica." },
  },
  "radiesse": {
    name: "Radiesse",
    tag: "Inyectable · Volumen y estructura",
    headline: "Un relleno de hidroxiapatita cálcica que restaura la estructura y estimula el colágeno con el tiempo.",
    summary: "Radiesse es un relleno hecho de microesferas de hidroxiapatita cálcica en un gel. Aporta elevación y definición a las mejillas, la línea de la mandíbula y las manos, y favorece el colágeno a medida que se asienta. Inyectables dirigidos por una médica en Logan Square.",
    intro: [
      "Radiesse es distinto de los rellenos de ácido hialurónico. Sus microesferas de hidroxiapatita cálcica brindan un soporte más firme y estructural, adecuado para los pómulos, la línea de la mandíbula, el mentón y el dorso de las manos. A medida que el gel se absorbe, las microesferas permanecen por un tiempo y estimulan a la piel a formar su propio colágeno.",
      "Una visita toma unos treinta minutos. Puede haber hinchazón leve o moretones durante unos días. Los resultados son visibles de inmediato y suelen durar un año o más, según la zona y la persona.",
      "Radiesse también puede diluirse y usarse para mejorar la calidad de la piel en zonas más amplias, como el cuello. La Dra. Olivo decide el producto y la técnica en una consulta, donde se definen la candidatura y las expectativas.",
    ],
    benefits: ["Estructura para mejillas, línea de la mandíbula y mentón", "También se usa en el dorso de las manos", "Estimula el colágeno a medida que se asienta", "Unos treinta minutos", "Resultados que suelen durar un año o más"],
    session: { duration: "Unos 30 minutos", sessions: "Una sola sesión; retoques según sea necesario", downtime: "Mínima", feels: "Pinchazos breves con presión; la lidocaína del producto alivia la molestia", results: "Visibles de inmediato, con un efecto de colágeno que se desarrolla en los meses siguientes" },
    goodFor: ["Adultos con pérdida de volumen en el tercio medio o inferior del rostro", "Personas que buscan definición en la línea de la mandíbula o el mentón", "Cualquier persona autorizada en la consulta"],
    faqs: [
      { q: "¿En qué se diferencia Radiesse de un relleno de ácido hialurónico?", a: "Radiesse es más firme y estructural, y estimula el colágeno. No puede disolverse como los rellenos de ácido hialurónico, por lo que su colocación se planifica con cuidado." },
      { q: "¿Cuánto dura?", a: "Normalmente un año o más, según la zona, la cantidad y la rapidez con que su cuerpo lo metaboliza." },
      { q: "¿Puede usarse en los labios?", a: "No. Radiesse no se usa en los labios. Los rellenos de ácido hialurónico como Revanesse Versa son la opción para esa zona." },
      { q: "¿Requiere tiempo de recuperación?", a: "Mínimo. La hinchazón y los posibles moretones se resuelven en unos días. La mayoría de las personas retoma su actividad normal de inmediato." },
    ],
    seo: { title: "Relleno Radiesse en Logan Square, Chicago | Olivo Med Spa", description: "Radiesse en Olivo Med Spa, Logan Square, aporta estructura a mejillas, mandíbula, mentón y manos, y estimula el colágeno. Dirigido por una médica." },
  },
  "botox-and-xeomin": {
    name: "Botox Cosmetic y Xeomin",
    tag: "Inyectable · Líneas de expresión",
    headline: "Neuromoduladores que suavizan las líneas de expresión de la frente, el entrecejo y el contorno de los ojos.",
    summary: "Botox Cosmetic y Xeomin son neuromoduladores que relajan los pequeños músculos detrás de las líneas del entrecejo, las líneas de la frente y las patas de gallo. Una visita corta, resultados en alrededor de una semana, con una duración de tres a cuatro meses. Dirigido por una médica en Logan Square.",
    intro: [
      "Las líneas de expresión provienen de músculos que repiten el mismo movimiento durante años. Botox Cosmetic y Xeomin actúan relajando esos músculos durante unos meses, para que la piel que los cubre descanse. La clínica cuenta con ambos. Contienen la misma proteína activa; Xeomin está formulado sin proteínas accesorias, lo que algunas personas prefieren.",
      "Una visita toma unos diez a quince minutos. Siente unos pocos pinchazos pequeños. El cambio comienza en cuestión de días y se asienta en unas dos semanas. La mayoría de las personas repite cada tres o cuatro meses. Las zonas comunes son la frente, las líneas del entrecejo y las patas de gallo. Otras zonas se evalúan caso por caso.",
      "El objetivo es una versión descansada de su rostro, no un rostro inexpresivo. La dosis y la colocación se deciden en una consulta, donde se definen la candidatura y las expectativas.",
    ],
    benefits: ["Suaviza las líneas del entrecejo, la frente y las patas de gallo", "Unos diez a quince minutos", "Sin recuperación", "Botox Cosmetic y Xeomin disponibles", "El objetivo es un movimiento natural"],
    session: { duration: "Unos 10 a 15 minutos", sessions: "Se repite cada tres o cuatro meses", downtime: "Ninguna", feels: "Unos pocos pinchazos pequeños", results: "El cambio comienza en unos días y se asienta en unas dos semanas" },
    goodFor: ["Adultos con líneas visibles en reposo o al gesticular", "Personas que buscan un enfoque preventivo y sutil", "Cualquier persona autorizada en la consulta, sin afecciones neuromusculares relevantes"],
    faqs: [
      { q: "¿Botox Cosmetic o Xeomin? ¿Cuál debo elegir?", a: "Ambos relajan el músculo tratado de manera similar. Xeomin no tiene proteínas accesorias. La Dra. Olivo le recomendará uno según su historial y su preferencia." },
      { q: "¿Mi rostro se verá inexpresivo?", a: "No, si ese no es el objetivo. La dosis y la colocación son conservadoras y se ajustan a sus expresiones." },
      { q: "¿Cuánto dura?", a: "Normalmente de tres a cuatro meses. Algunas personas notan que dura más con tratamientos regulares." },
      { q: "¿Puedo hacer ejercicio después?", a: "Espere hasta el día siguiente para hacer ejercicio, y evite frotar la zona o recostarse durante unas cuatro horas." },
    ],
    seo: { title: "Botox Cosmetic y Xeomin en Chicago | Olivo Med Spa", description: "Botox Cosmetic y Xeomin en Olivo Med Spa, Logan Square: suavizan líneas del entrecejo, frente y patas de gallo en una visita corta, sin recuperación." },
  },
  "dermal-fillers": {
    name: "Rellenos dérmicos",
    tag: "Inyectable · Volumen y contorno",
    headline: "Rellenos de ácido hialurónico para labios, mejillas y contorno, aplicados con mano ligera.",
    summary: "Los rellenos dérmicos restauran el volumen y la forma con ácido hialurónico, una sustancia que la piel produce por sí misma. La clínica utiliza Revanesse Versa y Belotero para labios, mejillas, ojeras hundidas y líneas finas. Dirigido por una médica en Logan Square.",
    intro: [
      "Los rellenos de ácido hialurónico son geles suaves que aportan volumen donde el rostro lo ha perdido y forma donde usted busca más definición. La clínica cuenta con Revanesse Versa y Belotero. Cada uno tiene una textura distinta, así que el producto se elige según la zona: geles más densos para mejillas y línea de la mandíbula, y más suaves para labios y líneas finas.",
      "Una visita toma unos treinta a cuarenta y cinco minutos con anestesia. Los resultados son visibles de inmediato, con hinchazón leve durante unos días. Según el producto y la zona, los resultados suelen durar de seis a dieciocho meses. Los rellenos de ácido hialurónico pueden disolverse si es necesario.",
      "Un buen relleno es invisible. La Dra. Olivo planifica la colocación según su anatomía en una consulta, donde se definen la candidatura y las expectativas.",
    ],
    benefits: ["Labios, mejillas, ojeras, línea de la mandíbula y líneas finas", "Revanesse Versa y Belotero", "Resultados visibles de inmediato", "Reversible si es necesario", "Unos treinta a cuarenta y cinco minutos"],
    session: { duration: "Unos 30 a 45 minutos", sessions: "Una sola sesión; se repite a medida que el resultado se desvanece", downtime: "Mínima", feels: "Pinchazos pequeños y presión tras la anestesia", results: "Visibles de inmediato; la hinchazón se resuelve en unos días" },
    goodFor: ["Adultos con pérdida de volumen en mejillas, labios u ojeras", "Personas que buscan contorno sin cirugía", "Cualquier persona autorizada en la consulta"],
    faqs: [
      { q: "¿Se verá exagerado?", a: "No con cantidades conservadoras y una colocación cuidadosa. El plan se construye en torno a su rostro y puede añadir más después." },
      { q: "¿Cuánto duran los rellenos?", a: "De seis a dieciocho meses según el producto, la zona y cómo lo metaboliza su cuerpo." },
      { q: "¿El relleno puede revertirse?", a: "Sí. Los rellenos de ácido hialurónico pueden disolverse con una enzima si es necesario." },
      { q: "¿Duele?", a: "La crema anestésica y la lidocaína del producto lo mantienen tolerable. Siente presión y pinchazos pequeños." },
    ],
    seo: { title: "Rellenos dérmicos en Logan Square, Chicago | Olivo Med Spa", description: "Rellenos dérmicos en Olivo Med Spa, Logan Square: Revanesse Versa y Belotero para labios, mejillas, ojeras y contorno. Dirigido por una médica." },
  },
  "revanesse-versa": {
    name: "Revanesse Versa",
    tag: "Inyectable · Ácido hialurónico",
    headline: "Una línea de rellenos de ácido hialurónico elegida por sus resultados uniformes y una recuperación cómoda.",
    summary: "Revanesse Versa es una línea de rellenos de ácido hialurónico que la clínica utiliza para labios, mejillas y líneas alrededor de la nariz y la boca. Está formulada para resultados uniformes y parejos con una recuperación cómoda. Inyectables dirigidos por una médica en Logan Square.",
    intro: [
      "Revanesse Versa es una línea de rellenos de ácido hialurónico fabricada con un proceso refinado que produce partículas uniformes y esféricas. En la práctica, eso significa un gel suave que se integra bien y una recuperación que muchas personas encuentran más llevadera. Es una elección frecuente en la clínica para labios, surcos nasolabiales y mejillas.",
      "Una visita toma unos treinta minutos con anestesia, y los resultados son visibles de inmediato. La hinchazón leve se resuelve en unos días. Los resultados suelen durar alrededor de un año según la zona. Como otros rellenos de ácido hialurónico, puede disolverse si es necesario.",
      "La elección del producto es parte del plan, no el punto de partida. La Dra. Olivo selecciona Revanesse Versa o Belotero para cada zona en una consulta, donde se definen la candidatura y las expectativas.",
    ],
    benefits: ["Relleno de ácido hialurónico para labios, mejillas y surcos", "Gel suave diseñado para integrarse de manera uniforme", "Resultados visibles de inmediato", "Reversible si es necesario", "Unos treinta minutos"],
    session: { duration: "Unos 30 minutos", sessions: "Una sola sesión; se repite a medida que el resultado se desvanece", downtime: "Mínima", feels: "Pinchazos pequeños y presión tras la anestesia", results: "Visibles de inmediato; el aspecto final se aprecia cuando la hinchazón baja en unos días" },
    goodFor: ["Adultos que buscan labios más llenos o definidos", "Personas con pérdida de volumen en las mejillas o en los surcos alrededor de la boca", "Cualquier persona autorizada en la consulta"],
    faqs: [
      { q: "¿Qué hace diferente a Revanesse Versa?", a: "Sus partículas se fabrican uniformes y esféricas, lo que da un gel suave. El fabricante reporta menos hinchazón que algunos rellenos comparables. La Dra. Olivo le explicará qué significa eso para su zona." },
      { q: "¿Cuánto dura?", a: "Alrededor de un año en la mayoría de las zonas, a veces menos en los labios, donde el movimiento es constante." },
      { q: "¿Se usa en los labios?", a: "Sí. La línea incluye una formulación pensada para la zona de los labios. Otros productos de la línea se adaptan a mejillas y surcos." },
      { q: "¿Puede disolverse?", a: "Sí. Como todos los rellenos de ácido hialurónico, puede revertirse con una enzima si es necesario." },
    ],
    seo: { title: "Relleno Revanesse Versa en Chicago | Olivo Med Spa", description: "Revanesse Versa en Olivo Med Spa, Logan Square: relleno suave de ácido hialurónico para labios, mejillas y líneas de la boca. Dirigido por una médica." },
  },
};

export const servicesEs1: Record<string, ServiceEs> = { ...a, ...servicesEs1b };
