// Spanish (Latin American) translations: skin resurfacing and laser services. Facts mirror the English sources. See docs/CONTENT-RULES.md.
import type { ServiceEs } from "./types";
import { servicesEs2b as b } from "./services-2b";

const a: Record<string, ServiceEs> = {
  "opus-plasma": {
    name: "Opus Plasma",
    tag: "Rostro · Pocos días",
    headline: "Resurfacing fraccionado con plasma para textura, líneas y cicatrices, con una recuperación que se mide en días.",
    summary: "Opus Plasma utiliza energía de plasma fraccionada para renovar la piel, con una profundidad ajustada a su textura, líneas o cicatrices. Una opción de resurfacing dirigida por una médica en Logan Square, con menos tiempo de recuperación que los láseres ablativos tradicionales.",
    intro: [
      "Opus Plasma es la plataforma de plasma fraccionado de Alma. La punta aplica energía de plasma sobre la piel en una cuadrícula controlada, creando pequeñas zonas de tejido tratado con piel intacta entre ellas. Ese patrón es lo que permite que la piel se recupere rápido. La Dra. Olivo define la profundidad y la cobertura para cada área, de modo que una pasada ligera en las mejillas y una más profunda en cicatrices de acné pueden hacerse en la misma visita.",
      "La mayoría de las personas describe unos días de enrojecimiento y una sensación áspera, como de papel de lija, mientras la piel se renueva, y después una textura más lisa en las semanas siguientes. Se ubica entre un peeling y un láser CO2 en cuanto a lo que logra y al tiempo de recuperación.",
      "La candidatura depende de su tipo de piel, su exposición al sol y lo que desea tratar. La Dra. Olivo confirma en su consulta si Opus Plasma, CO2 o el microneedling con radiofrecuencia Exion es la herramienta adecuada, y establece expectativas sobre cuántas sesiones y cuánta recuperación implicará su plan.",
    ],
    benefits: ["Profundidad ajustada a textura, líneas o cicatrices", "Patrón fraccionado, por lo que la recuperación es más rápida", "Rostro, cuello, escote y manos", "Una sola sesión o una serie corta", "Parámetros definidos por la médica, no preajustes"],
    session: { duration: "De 30 a 45 minutos aproximadamente, con anestesia tópica", sessions: "De una a tres sesiones, con unas cuatro semanas de separación", downtime: "Pocos días", feels: "Calor y picazón bajo anestesia tópica", results: "Cambio en la textura conforme la piel se renueva en las primeras semanas, con cambios continuos durante algunos meses" },
    goodFor: ["Adultos con textura irregular, líneas finas o cicatrices de acné que buscan una recuperación más corta que la del CO2", "Personas que pueden proteger del sol la piel tratada durante algunas semanas", "Cualquier persona aprobada en la consulta, tras revisar el tipo de piel y el uso reciente de isotretinoína"],
    faqs: [
      { q: "¿En qué se diferencia Opus Plasma de un láser?", a: "Un láser emite luz. Opus Plasma emite energía de plasma desde una punta metálica que ioniza el aire justo encima de la piel. Renueva la piel en un patrón fraccionado, como un láser fraccionado, pero con menor dispersión de calor hacia el tejido circundante, y de ahí viene la recuperación más corta." },
      { q: "¿Cuánto dura el tiempo de recuperación?", a: "Cuente con unos días de enrojecimiento y textura áspera, seguidos de una descamación ligera. La mayoría de las personas se siente cómoda en público con maquillaje mineral hacia el tercer o cuarto día. Los ajustes más profundos implican algunos días más." },
      { q: "¿Cuántas sesiones necesito?", a: "Una sola sesión marca una diferencia visible para muchas personas. Las cicatrices y las líneas más profundas suelen responder mejor con dos o tres, con unas cuatro semanas de separación. La Dra. Olivo define el plan en la consulta." },
      { q: "¿Se puede combinar con otros tratamientos?", a: "Sí. Con frecuencia se combina con Opus Colibri para párpados y líneas del labio en la misma visita, y con Botox Cosmetic o rellenos programados con unas semanas de diferencia." },
    ],
    seo: { title: "Resurfacing Opus Plasma en Chicago | Olivo Med Spa", description: "Opus Plasma en Olivo Med Spa, Logan Square, Chicago. Resurfacing fraccionado con plasma, con profundidad ajustada a textura, líneas y cicatrices." },
  },
  "co2-fractional-laser": {
    name: "Láser fraccionado CO2",
    tag: "Rostro · Cerca de una semana",
    headline: "El resurfacing más profundo de la clínica, para textura, cicatrices y líneas que los tratamientos más ligeros no alcanzan.",
    summary: "El láser fraccionado CO2 es el tratamiento de resurfacing más profundo de Olivo Med Spa. Trata cicatrices de acné, líneas marcadas y textura áspera en una sola sesión, con cerca de una semana de recuperación, bajo el cuidado de una médica en Logan Square.",
    intro: [
      "El CO2 fraccionado elimina columnas de piel hasta una profundidad controlada y calienta el tejido que las rodea. La piel responde reconstruyéndose con colágeno nuevo. Como actúa a mayor profundidad que el plasma o el microneedling, es el tratamiento al que recurre la Dra. Olivo cuando las cicatrices, las líneas marcadas o la textura dañada por el sol no han respondido a opciones más ligeras.",
      "Cuente con cerca de una semana en casa. La piel está roja y exuda durante los primeros días, luego se descama y se asienta. La mayoría de las personas se trata una sola vez y observa cambios durante los meses siguientes conforme el colágeno se remodela. En casos de cicatrices profundas a veces se programa una segunda sesión.",
      "El CO2 no es la opción adecuada para todas las personas. El tipo de piel, la exposición reciente al sol, el historial de cicatrización y el tiempo del que dispone para recuperarse influyen. La Dra. Olivo revisa estos factores en su consulta, establece expectativas sobre la recuperación y puede recomendar Opus Plasma o Erbium cuando esa sea la mejor opción.",
    ],
    benefits: ["El resurfacing más profundo disponible en la clínica", "Cicatrices de acné, líneas marcadas, textura áspera", "Normalmente una sola sesión", "Plan dirigido por una médica y cuidados posteriores por escrito", "Se combina con Opus Plasma en áreas más ligeras"],
    session: { duration: "De 45 a 60 minutos aproximadamente, con anestesia tópica", sessions: "Normalmente una sola sesión", downtime: "Cerca de una semana", feels: "Calor intenso bajo anestesia tópica, y luego una sensación de quemadura solar durante los primeros días", results: "Textura más lisa conforme la piel sana, con cambios en el colágeno que continúan durante varios meses" },
    goodFor: ["Adultos con cicatrices de acné profundas o líneas marcadas", "Personas que pueden tomarse cerca de una semana lejos del trabajo y del sol", "Cualquier persona aprobada en la consulta, tras revisar el tipo de piel y el historial de cicatrización"],
    faqs: [
      { q: "¿Cuánto tiempo de recuperación debo prever?", a: "Cerca de una semana. Los días uno a tres la piel está roja, inflamada y exuda. Los días cuatro a siete se descama. El tono rosado puede persistir algunas semanas y se cubre con facilidad una vez que la piel ha cerrado. Se irá con un plan de cuidados posteriores por escrito." },
      { q: "¿Duele?", a: "Se aplica anestesia tópica durante un buen rato antes del tratamiento, y durante el mismo se utiliza aire frío. La mayoría de las personas describe un calor intenso más que un dolor agudo. Los dos primeros días posteriores se sienten como una quemadura solar fuerte." },
      { q: "¿Es el CO2 adecuado para pieles más oscuras?", a: "El resurfacing ablativo más profundo conlleva mayor riesgo de cambios de pigmentación en los tipos de piel más oscuros. La Dra. Olivo evalúa el tipo de piel en la consulta y puede recomendar en su lugar el microneedling con radiofrecuencia Exion o un ajuste más ligero de Opus Plasma." },
      { q: "¿En qué se diferencia del Erbium?", a: "El CO2 actúa a mayor profundidad y aporta más calor, lo que significa más remodelación del colágeno y más tiempo de recuperación. El Erbium elimina tejido con mayor precisión y menos calor, por lo que la recuperación es más corta y el cambio es más moderado." },
    ],
    seo: { title: "Láser fraccionado CO2 en Logan Square | Olivo Med Spa", description: "Láser fraccionado CO2 en Olivo Med Spa, Logan Square, Chicago. El resurfacing más profundo de la clínica para cicatrices, líneas y textura." },
  },
  "erbium-resurfacing": {
    name: "Resurfacing con láser Erbium",
    tag: "Rostro · Pocos días",
    headline: "Resurfacing ablativo con un toque más ligero y una recuperación más corta que la del CO2.",
    summary: "El resurfacing con láser Erbium elimina las capas externas de la piel con menos calor que el CO2, por lo que la recuperación es más corta. Es adecuado para líneas finas, textura leve y daño solar. Dirigido por una médica en Olivo Med Spa, Logan Square.",
    intro: [
      "Los láseres Erbium son absorbidos por el agua de la piel con mayor eficiencia que el CO2, de modo que eliminan tejido con menos calor circundante. Eso significa una ablación más precisa y una recuperación más rápida, normalmente unos días de enrojecimiento y descamación en lugar de una semana completa. También significa menos remodelación del colágeno que con el CO2, y esa es la contrapartida.",
      "La Dra. Olivo recurre al Erbium cuando el objetivo es una textura superficial más lisa, líneas finas alrededor de los ojos y la boca, o piel dañada por el sol, y cuando una semana de recuperación no es una opción. El tratamiento puede ser ligero o de campo completo según lo que necesite.",
      "Que la herramienta adecuada sea Erbium, Opus Plasma o CO2 depende de su piel, sus objetivos y su agenda. La Dra. Olivo lo define en su consulta, junto con la profundidad del tratamiento, cuántas sesiones planificar y qué recuperación esperar según su tipo de piel.",
    ],
    benefits: ["Recuperación más corta que con el CO2", "Líneas finas, textura leve, daño solar", "Preciso, con menos calor hacia la piel circundante", "Profundidad ajustada por área", "Una sola sesión o una serie corta"],
    session: { duration: "De 30 a 45 minutos aproximadamente, con anestesia tópica", sessions: "Una sesión, que se repite si es necesario", downtime: "Pocos días", feels: "Calor y escozor bajo anestesia tópica", results: "Textura más lisa conforme la piel se descama y se asienta durante las dos primeras semanas" },
    goodFor: ["Adultos con líneas finas o textura leve que buscan una recuperación más corta", "Personas con daño solar en el rostro, el cuello o las manos", "Cualquier persona aprobada en la consulta, tras revisar el tipo de piel"],
    faqs: [
      { q: "¿Erbium o CO2? ¿Cuál necesito?", a: "Erbium para textura superficial, líneas finas y daño solar cuando necesita reincorporarse en pocos días. CO2 para cicatrices más profundas y líneas marcadas cuando puede tomarse una semana. La Dra. Olivo toma la decisión en la consulta después de examinar su piel." },
      { q: "¿Cuánto tiempo estaré con la piel roja?", a: "Normalmente de tres a cinco días de enrojecimiento y descamación, seguidos de un tono rosado que se desvanece en una o dos semanas y se cubre con facilidad. Las pasadas más profundas tardan un poco más." },
      { q: "¿Qué áreas se pueden tratar?", a: "El rostro completo es lo más habitual. El cuello, el escote y las manos pueden tratarse con parámetros ajustados, al igual que zonas más pequeñas como el labio superior o debajo de los ojos." },
      { q: "¿Cuándo puedo volver a maquillarme?", a: "Una vez que la piel ha terminado de descamarse y ha cerrado por completo, a menudo en unos días o hasta una semana. Sus cuidados posteriores por escrito indican el momento específico según la profundidad de su tratamiento." },
    ],
    seo: { title: "Resurfacing con láser Erbium en Chicago | Olivo Med Spa", description: "Resurfacing con láser Erbium en Olivo Med Spa, Logan Square, Chicago. Ablativo más ligero para líneas finas y textura, con menos recuperación que el CO2." },
  },
  "exion-rf-microneedling": {
    name: "Microneedling con radiofrecuencia Exion",
    tag: "Rostro y cuerpo · Pocos días",
    headline: "Microneedling con radiofrecuencia para textura, cicatrices, poros y firmeza, en rostro y cuerpo.",
    summary: "El microneedling con radiofrecuencia Exion combina agujas finas con energía de radiofrecuencia para tratar textura, cicatrices de acné, poros dilatados y flacidez de la piel. Parte de la plataforma BTL en Olivo Med Spa, Logan Square.",
    intro: [
      "Exion es la pieza de mano de microneedling con radiofrecuencia de BTL. Agujas aisladas penetran la piel hasta una profundidad definida y aplican energía de radiofrecuencia donde se produce el colágeno, sin ablacionar la superficie. Por eso es adecuado para quienes buscan cambios en textura y firmeza sin la descamación de un láser, y por eso se utiliza en una gama más amplia de tipos de piel.",
      "Un plan típico consta de tres sesiones, con unas cuatro semanas de separación. Espere enrojecimiento durante uno o dos días y una sensación áspera durante algunos días. Como la clínica cuenta con la plataforma BTL completa, la Dra. Olivo puede combinarlo con el tratamiento de firmeza Exion para rostro o cuerpo, o con Emface cuando esa sea la mejor respuesta.",
      "La candidatura, la profundidad de las agujas y el número de sesiones se definen en su consulta. La Dra. Olivo examina las áreas que desea tratar, su tipo de piel y cualquier acné activo o procedimiento reciente, y luego decide si el microneedling con radiofrecuencia Exion por sí solo es el plan adecuado o si conviene un tratamiento de resurfacing primero.",
    ],
    benefits: ["Textura, cicatrices de acné, poros y flacidez en un solo plan", "Rostro, cuello, escote y zonas del cuerpo", "Sin ablación de la superficie, por lo que la descamación es limitada", "Se utiliza en una amplia gama de tipos de piel", "Se combina con Exion y Emface en la plataforma BTL"],
    session: { duration: "Unos 45 minutos, con anestesia tópica", sessions: "Tres sesiones, con unas cuatro semanas de separación", downtime: "Pocos días", feels: "Presión y calor bajo anestesia tópica", results: "Cambios en textura y firmeza durante las semanas posteriores a cada sesión, con el cambio más completo unos meses después de la serie" },
    goodFor: ["Adultos con cicatrices de acné, poros dilatados o piel con aspecto de papel crepé", "Personas que buscan firmeza sin la recuperación de un láser", "Cualquier persona aprobada en la consulta, tras revisar el tipo de piel y el acné activo"],
    faqs: [
      { q: "¿En qué se diferencia el microneedling con radiofrecuencia del microneedling convencional?", a: "El microneedling convencional crea canales diminutos para activar la cicatrización. El microneedling con radiofrecuencia añade calor por radiofrecuencia a través de las puntas de las agujas, aplicado en profundidad, lo que aporta más firmeza y más remodelación de cicatrices en la misma sesión." },
      { q: "¿Funciona en pieles más oscuras?", a: "El microneedling con radiofrecuencia aplica la energía por debajo de la superficie y no en la capa de pigmento, por lo que se utiliza habitualmente en distintos tipos de piel. La Dra. Olivo confirma la idoneidad y los parámetros en la consulta." },
      { q: "¿Cuántas sesiones necesito?", a: "Tres es la serie habitual. Las cicatrices de acné más profundas pueden requerir más. Los resultados se construyen de forma gradual porque el colágeno se remodela a lo largo de meses, así que el cambio más completo se aprecia bastante después de la última sesión." },
      { q: "¿En qué partes del cuerpo se puede usar?", a: "El rostro, el cuello y el escote son las más habituales. También se usa en el abdomen, los brazos y los muslos para piel con aspecto de papel crepé o estrías, a menudo junto con el tratamiento de firmeza corporal Exion." },
    ],
    seo: { title: "Microneedling RF Exion en Chicago | Olivo Med Spa", description: "Microneedling con radiofrecuencia Exion en Olivo Med Spa, Logan Square, Chicago. Para textura, cicatrices de acné, poros y firmeza en rostro y cuerpo." },
  },
  "opus-colibri": {
    name: "Opus Colibri",
    tag: "Rostro · Pocos días",
    headline: "Plasma de precisión para áreas pequeñas: párpados, contorno de la boca y otros puntos que una pasada completa no alcanzaría.",
    summary: "Opus Colibri es la pieza de mano de plasma con punta fina de Alma para áreas pequeñas y detalladas, como los párpados y el contorno de la boca. Resurfacing de precisión dirigido por una médica en Olivo Med Spa, Logan Square.",
    intro: [
      "Opus Colibri es la punta de precisión de la plataforma Opus. Mientras Opus Plasma trata el rostro completo en una cuadrícula fraccionada, Colibri trabaja punto por punto en las áreas que requieren una mano cuidadosa: párpados superiores e inferiores con aspecto de papel crepé, líneas alrededor de la boca y cicatrices pequeñas. La energía de plasma tensa y renueva una zona diminuta a la vez.",
      "El tratamiento es breve, normalmente menos de treinta minutos para una sola área, con anestesia tópica. Espere pequeños puntos o costras durante varios días mientras la piel sana. Suele realizarse por sí solo o junto con una sesión de Opus Plasma de rostro completo.",
      "Si Colibri es adecuado para sus párpados o su boca, y si debe combinarse con Botox Cosmetic o rellenos, se decide en su consulta. La Dra. Olivo también revisa su historial ocular antes de cualquier trabajo en los párpados y establece expectativas sobre el aspecto de los pequeños puntos tratados mientras sanan.",
    ],
    benefits: ["Párpados, líneas del labio y cicatrices pequeñas", "Precisión punto por punto", "Tratamiento breve con anestesia tópica", "Se combina con una pasada de Opus Plasma de rostro completo", "Profundidad definida por la médica para piel delicada"],
    session: { duration: "De 20 a 30 minutos aproximadamente por área, con anestesia tópica", sessions: "De una a dos sesiones, con unas seis semanas de separación", downtime: "Pocos días", feels: "Calor punzante en cada punto bajo anestesia tópica", results: "Tensado y alisado conforme las pequeñas zonas tratadas sanan durante algunas semanas" },
    goodFor: ["Adultos con piel de los párpados con aspecto de papel crepé o líneas alrededor de la boca", "Personas que desean tratar un área pequeña en lugar del rostro completo", "Cualquier persona aprobada en la consulta, tras revisar el historial ocular para trabajos en los párpados"],
    faqs: [
      { q: "¿De verdad se puede usar plasma en los párpados?", a: "Sí, con la punta y los parámetros adecuados. Colibri está diseñado para áreas delicadas. La Dra. Olivo evalúa la piel y define la profundidad en consecuencia, y los ojos se protegen durante el tratamiento." },
      { q: "¿Cómo es la cicatrización?", a: "Pequeños puntos oscuros donde se trató cada punto, con una leve hinchazón alrededor de los ojos durante uno o dos días. Los puntos se desprenden en cinco a siete días. No los arranque." },
      { q: "¿En qué se diferencia de Opus Plasma?", a: "La misma energía, distinta punta. Opus Plasma cubre áreas más grandes con rapidez en un patrón fraccionado. Colibri es una punta fina para trabajo puntual, donde la precisión importa más que la cobertura." },
      { q: "¿Es esto un bolígrafo de plasma?", a: "No. Opus Colibri forma parte de la plataforma médica Opus de Alma, con una aplicación de energía controlada y bajo supervisión médica. Los bolígrafos de plasma portátiles son una categoría de dispositivo distinta." },
    ],
    seo: { title: "Opus Colibri para párpados en Chicago | Olivo Med Spa", description: "Plasma Opus Colibri en Olivo Med Spa, Logan Square, Chicago. Resurfacing de precisión para párpados, líneas del labio y cicatrices pequeñas." },
  },
  "laser-hair-removal": {
    name: "Depilación láser",
    tag: "Rostro y cuerpo · Sin tiempo de recuperación",
    headline: "Una serie de sesiones para reducir el vello no deseado, con parámetros ajustados a su tono de piel en la consulta.",
    summary: "La depilación láser en Olivo Med Spa trata rostro y cuerpo en una serie planificada. El tono de piel y el color del vello se evalúan en la consulta para utilizar los parámetros correctos. La membresía Laser Hair Reduction Club cubre sesiones continuas en Logan Square.",
    intro: [
      "La depilación láser actúa sobre el pigmento del folículo piloso con energía lumínica, desactivando el folículo a lo largo de una serie de sesiones. El vello crece en ciclos, así que en cada visita solo responden los folículos en fase activa. Por eso el plan es una serie, normalmente de seis a ocho sesiones separadas por varias semanas, y no una sola cita.",
      "El tono de piel y el color del vello determinan qué parámetros son apropiados. Todos los tonos de piel se evalúan en la consulta. Las áreas más habituales incluyen axilas, línea del bikini, piernas, espalda, pecho y rostro. Las sesiones van desde diez minutos para un área pequeña hasta cerca de una hora para las piernas completas.",
      "Para quienes desean mantener los resultados con el tiempo, la membresía Laser Hair Reduction Club distribuye las sesiones a lo largo del año. Las condiciones se explican en la consulta, junto con una estimación realista de cuántas sesiones necesitarán sus áreas y cómo preparar la piel antes de cada visita.",
    ],
    benefits: ["Áreas de rostro y cuerpo", "Parámetros ajustados al tono de piel y al color del vello", "Sesiones breves, sin tiempo de recuperación", "Membresía Laser Hair Reduction Club disponible", "Evaluado y planificado en la consulta"],
    session: { duration: "De 10 a 60 minutos según el área", sessions: "Una serie, normalmente de seis a ocho, con cuatro a ocho semanas de separación", downtime: "Ninguno", feels: "Un chasquido rápido de calor con cada pulso, con enfriamiento entre pulsos", results: "El vello vuelve a crecer más fino y escaso después de cada sesión, con la mayor reducción al terminar la serie" },
    goodFor: ["Adultos cansados de afeitarse, depilarse con cera o lidiar con vellos encarnados", "Personas con vello oscuro sobre piel clara u oscura, evaluadas en la consulta", "Cualquier persona aprobada en la consulta, tras revisar la exposición reciente al sol y los medicamentos"],
    faqs: [
      { q: "¿Volverá a crecer el vello?", a: "La mayoría de las personas observa una reducción duradera después de una serie completa. Las hormonas y los folículos que estaban inactivos durante el tratamiento pueden producir vello nuevo con el tiempo, por lo que las sesiones de mantenimiento ocasionales son habituales. Para eso existe el Laser Hair Reduction Club." },
      { q: "¿Funciona en pieles más oscuras?", a: "Los parámetros varían según el tono de piel, y la longitud de onda adecuada es importante para las pieles más oscuras. Todos los tonos de piel se evalúan en la consulta y se tratan solo cuando el dispositivo y los parámetros son apropiados para usted." },
      { q: "¿Cómo debo prepararme?", a: "Afeite el área el día anterior. Evite la cera, las pinzas y la exposición al sol durante varias semanas antes de cada sesión, ya que el láser necesita que el folículo esté en su lugar y que la piel no esté bronceada para funcionar bien." },
      { q: "¿Qué es el Laser Hair Reduction Club?", a: "Una membresía que distribuye las sesiones de depilación láser a lo largo del año para quienes tratan varias áreas o mantienen sus resultados. Las condiciones se explican en la consulta." },
    ],
    seo: { title: "Depilación láser en Logan Square | Olivo Med Spa", description: "Depilación láser en Olivo Med Spa, Logan Square, Chicago. Una serie planificada para rostro y cuerpo, con todos los tonos de piel evaluados en la consulta." },
  },
  "ipl-photofacial": {
    name: "Fotofacial IPL",
    tag: "Rostro · Mínimo",
    headline: "Luz pulsada intensa para manchas solares, rojeces y tono desigual, con poco tiempo fuera de su semana.",
    summary: "Un fotofacial IPL utiliza luz de amplio espectro para actuar sobre manchas marrones y rojeces visibles, de modo que el tono luce más uniforme. Una serie corta en Olivo Med Spa, Logan Square, planificada por una médica.",
    intro: [
      "La IPL no es un láser. Emite pulsos de luz filtrada en un rango de longitudes de onda, y tanto la melanina de las manchas solares como la hemoglobina de los vasos pequeños absorben esa luz. Las manchas se oscurecen y se desprenden en aproximadamente una semana. Las rojeces se atenúan conforme los vasos se cierran. El resultado es un tono más uniforme en rostro, cuello, escote o manos.",
      "Un plan típico consta de tres sesiones, con unas cuatro semanas de separación. Cada visita dura de veinte a treinta minutos. Puede lucir enrojecido durante algunas horas y las manchas se ven más oscuras antes de desprenderse. La mayoría de las personas retoma su día.",
      "La IPL actúa sobre el pigmento, así que el tono de piel y la exposición reciente al sol son importantes. La Dra. Olivo confirma en su consulta si la IPL o Laser Genesis es la herramienta adecuada, verifica que no haya nada que desaconseje el tratamiento y establece expectativas sobre el aspecto de las manchas en los días posteriores a cada sesión.",
    ],
    benefits: ["Manchas solares, rojeces y tono desigual", "Rostro, cuello, escote y manos", "De veinte a treinta minutos aproximadamente", "Tiempo de recuperación mínimo", "Se combina a menudo con Laser Genesis"],
    session: { duration: "De 20 a 30 minutos aproximadamente", sessions: "Tres sesiones, con unas cuatro semanas de separación", downtime: "Mínimo", feels: "Un chasquido de calor con cada pulso, como una liga elástica", results: "Las manchas se oscurecen y se desprenden en una o dos semanas, y el tono se uniformiza a lo largo de la serie" },
    goodFor: ["Adultos con manchas solares o pecas en el rostro, el escote o las manos", "Personas con rojeces difusas o rubor", "Cualquier persona aprobada en la consulta, tras revisar el tipo de piel y la exposición reciente al sol"],
    faqs: [
      { q: "¿IPL o Laser Genesis?", a: "IPL para manchas marrones definidas y vasos visibles. Laser Genesis para rojeces difusas, poros y líneas finas, sin tiempo de recuperación. Muchas personas hacen ambos. La Dra. Olivo decide el orden en la consulta." },
      { q: "¿Volverán a aparecer las manchas?", a: "Las manchas tratadas se desprenden, pero la nueva exposición al sol crea otras. El protector solar diario y una sesión de mantenimiento cada año son lo que mantiene el tono uniforme." },
      { q: "¿Puedo hacerme IPL con bronceado?", a: "No. La piel bronceada absorbe la luz destinada a las manchas y aumenta el riesgo de quemaduras y cambios de pigmentación. Manténgase fuera del sol y sin autobronceador durante algunas semanas antes de cada sesión." },
      { q: "¿Duele?", a: "Cada pulso se siente como el chasquido de una liga elástica con un destello de calor. El gel frío y una punta refrigerada lo hacen tolerable. La mayoría de las personas no necesita anestesia." },
    ],
    seo: { title: "Fotofacial IPL en Logan Square | Olivo Med Spa", description: "Fotofacial IPL en Olivo Med Spa, Logan Square, Chicago. Luz pulsada intensa para manchas solares, rojeces y tono desigual, con mínima recuperación." },
  },
  "laser-genesis": {
    name: "Laser Genesis",
    tag: "Rostro · Sin tiempo de recuperación",
    headline: "Un láser suave no ablativo para rojeces, poros y líneas finas. Nada que ocultar después.",
    summary: "Laser Genesis calienta la dermis superior con un láser no ablativo para reducir rojeces, refinar los poros y suavizar las líneas finas. Sin tiempo de recuperación, así que cabe en la hora del almuerzo. Disponible en Olivo Med Spa, Logan Square.",
    intro: [
      "Laser Genesis pasa un láser no ablativo sobre la piel con un movimiento constante y cálido. No rompe la superficie. El calor estimula el colágeno en la dermis superior y reduce los vasos diminutos que causan las rojeces difusas. Las personas con rubor de tipo rosácea, poros dilatados o líneas finas incipientes suelen apreciarlo porque no hay nada de lo que recuperarse.",
      "Las sesiones duran unos treinta minutos y se sienten cálidas, no punzantes. Lo típico es una serie de cuatro a seis, con algunas semanas de separación, y luego mantenimiento unas cuantas veces al año. Se combina bien con la IPL en personas que tienen tanto rojeces como manchas marrones.",
      "Si Laser Genesis por sí solo es suficiente, o si conviene combinarlo con un peeling o con IPL, se decide en su consulta. La Dra. Olivo examina qué está provocando las rojeces, revisa su tipo de piel y los productos que utiliza, y define una serie que se ajuste a sus objetivos y a su agenda.",
    ],
    benefits: ["Rojeces, poros y líneas finas", "Sin tiempo de recuperación, sin necesidad de anestesia", "Unos treinta minutos", "Suficientemente cómodo para la pausa del almuerzo", "Se combina con IPL o peelings"],
    session: { duration: "Unos 30 minutos", sessions: "De cuatro a seis sesiones, con algunas semanas de separación", downtime: "Ninguno", feels: "Un calor suave que se extiende", results: "Cambio gradual en rojeces y textura a lo largo de la serie, con el cambio más completo al terminarla" },
    goodFor: ["Adultos con rojeces difusas o rubor de tipo rosácea", "Personas que buscan cambios en la textura sin tiempo de recuperación", "Cualquier persona aprobada en la consulta, incluidas quienes no pueden tomarse días libres"],
    faqs: [
      { q: "¿Cómo se siente?", a: "Como luz solar cálida que se desplaza por la piel. No se necesita anestesia. Algunas personas lo encuentran relajante. La piel puede quedar ligeramente rosada durante una hora después." },
      { q: "¿Cuántas sesiones necesito?", a: "La serie habitual es de cuatro a seis sesiones, con algunas semanas de separación, porque el cambio es acumulativo. La Dra. Olivo define el número en la consulta y puede sugerir mantenimiento unas cuantas veces al año." },
      { q: "¿Puedo maquillarme después?", a: "Sí, de inmediato. No hay piel abierta ni descamación. La mayoría de las personas lo reserva en la pausa del almuerzo y vuelve al trabajo." },
      { q: "¿En qué se diferencia de la IPL?", a: "La IPL es luz filtrada que actúa sobre manchas y vasos definidos y los deja más oscuros durante una semana. Laser Genesis es un láser de una sola longitud de onda que calienta la piel de manera uniforme para rojeces difusas y textura, sin secuelas visibles." },
    ],
    seo: { title: "Laser Genesis en Logan Square, Chicago | Olivo Med Spa", description: "Laser Genesis en Olivo Med Spa, Logan Square, Chicago. Un láser suave no ablativo para rojeces, poros y líneas finas, sin tiempo de recuperación." },
  },
  "tattoo-removal": {
    name: "Eliminación de tatuajes con láser",
    tag: "Rostro y cuerpo · Mínimo",
    headline: "Eliminación de tatuajes con láser en una serie de sesiones separadas por semanas, para que el cuerpo pueda eliminar la tinta.",
    summary: "La eliminación de tatuajes con láser fragmenta la tinta en partículas que el cuerpo elimina con el tiempo. Requiere varias sesiones separadas por varias semanas, y el número depende del color, la profundidad y la antigüedad de la tinta. Dirigido por una médica en Olivo Med Spa, Logan Square.",
    intro: [
      "El láser emite pulsos muy cortos que fragmentan las partículas de tinta sin cortar la piel. Su sistema inmunitario se encarga después de retirar los fragmentos durante las semanas siguientes. Cada sesión descompone otra capa, y por eso las sesiones se separan de seis a ocho semanas y una eliminación completa requiere una serie. La tinta negra suele responder más rápido. Los verdes y los azules claros tardan más.",
      "Espere un aspecto escarchado en la piel durante el tratamiento, y después unos días de enrojecimiento y en ocasiones ampollas. Los cuidados posteriores son sencillos y se le entregan por escrito. Las sesiones son breves, a menudo de menos de veinte minutos para una pieza pequeña, y el área tratada se mantiene cubierta y fuera del sol mientras sana.",
      "Cuántas sesiones necesita su tatuaje, y si el objetivo es la eliminación completa o aclararlo para un cover-up, se define en su consulta. La Dra. Olivo examina los colores, la profundidad y la ubicación de la tinta, revisa su tipo de piel y le da un rango realista en lugar de una cifra única.",
    ],
    benefits: ["Eliminación completa o aclarado para un cover-up", "Sesiones a menudo de menos de veinte minutos", "Separadas de seis a ocho semanas", "Las tintas negras y oscuras responden con mayor facilidad", "Plan definido en la consulta"],
    session: { duration: "De 10 a 30 minutos según el tamaño", sessions: "Varias sesiones, normalmente con seis a ocho semanas de separación", downtime: "Mínimo", feels: "Chasquidos agudos de calor, como una liga elástica, aliviados con enfriamiento y anestesia", results: "Desvanecimiento gradual entre sesiones conforme el cuerpo elimina la tinta" },
    goodFor: ["Adultos que desean eliminar un tatuaje o aclararlo para un trabajo nuevo", "Personas que pueden comprometerse con una serie a lo largo de muchos meses", "Cualquier persona aprobada en la consulta, tras revisar el tipo de piel y el historial del tatuaje"],
    faqs: [
      { q: "¿Cuántas sesiones se necesitarán?", a: "Depende del color, la profundidad, la antigüedad y la ubicación de la tinta, y de su piel. Los tatuajes profesionales en negro suelen necesitar menos sesiones que los de colores o muy densos. La Dra. Olivo le da un rango realista en la consulta." },
      { q: "¿Dejará cicatriz?", a: "Las cicatrices son poco frecuentes cuando se siguen los cuidados posteriores y las sesiones se separan correctamente, pero cualquier tratamiento de la piel conlleva cierto riesgo. Las cicatrices que ya existían por el propio tatuaje permanecerán después de que la tinta desaparezca." },
      { q: "¿Por qué tanto tiempo entre sesiones?", a: "El láser solo fragmenta la tinta. Su cuerpo se encarga de eliminarla, y eso lleva semanas. Tratar demasiado pronto añade riesgo sin añadir beneficio." },
      { q: "¿Se pueden eliminar todos los colores de tinta?", a: "No todos los colores responden por igual. El negro y el azul oscuro se eliminan con mayor facilidad. Los verdes, los azules claros y los amarillos pueden ser persistentes y quizá no desaparezcan por completo. Esto se evalúa en la consulta." },
    ],
    seo: { title: "Eliminación de tatuajes láser en Chicago | Olivo Med Spa", description: "Eliminación de tatuajes con láser en Olivo Med Spa, Logan Square, Chicago. Una serie de sesiones separadas por semanas para desvanecer o eliminar la tinta." },
  },
  "vein-removal": {
    name: "Eliminación de arañas vasculares y venas faciales",
    tag: "Rostro y piernas · Mínimo",
    headline: "Arañas vasculares en las piernas y pequeños vasos faciales tratados con láser o inyección, según lo determine su médica.",
    summary: "La eliminación de arañas vasculares y venas faciales en Olivo Med Spa trata pequeños vasos rojos o azules en el rostro y las piernas. La Dra. Olivo elige láser o escleroterapia según el vaso. Tiempo de recuperación mínimo, en Logan Square.",
    intro: [
      "Los pequeños vasos superficiales en la nariz, las mejillas y las piernas son frecuentes y por lo general inofensivos, pero son difíciles de cubrir. La energía láser calienta el vaso para que se cierre y el cuerpo lo absorba durante las semanas siguientes. Para arañas vasculares más grandes en las piernas, la escleroterapia, una inyección que cierra la vena desde dentro, puede ser la mejor herramienta. La Dra. Olivo decide cuál en su visita.",
      "Los vasos faciales suelen desaparecer en una o dos sesiones. Las venas de las piernas normalmente requieren de dos a tres sesiones, con un mes o más de separación. Espere un enrojecimiento leve o pequeños moretones durante algunos días. Para las piernas puede recomendarse compresión.",
      "El tratamiento de venas comienza con una evaluación médica. Si un patrón de vasos sugiere algo que deba evaluarse con más detalle, la Dra. Olivo se lo indicará antes de tratar. La candidatura, la elección entre láser e inyección y el número de sesiones a esperar se definen en esa consulta.",
    ],
    benefits: ["Vasos faciales y arañas vasculares en las piernas", "Láser o escleroterapia, elegidos según cada vaso", "Sesiones breves, tiempo de recuperación mínimo", "Evaluación médica antes del tratamiento", "Se combina con IPL para rojeces difusas"],
    session: { duration: "De 15 a 30 minutos aproximadamente", sessions: "De una a tres sesiones, con cuatro a seis semanas de separación", downtime: "Mínimo", feels: "Pinchazos rápidos de calor o el escozor de una pequeña inyección", results: "Los vasos se desvanecen durante varias semanas conforme el cuerpo los absorbe" },
    goodFor: ["Adultos con vasos visibles en la nariz o las mejillas", "Personas con arañas vasculares en los muslos, las pantorrillas o los tobillos", "Cualquier persona aprobada en la consulta, tras revisar el historial circulatorio"],
    faqs: [
      { q: "¿Láser o inyección?", a: "Los vasos faciales pequeños se tratan casi siempre con láser. Las arañas vasculares de las piernas pueden tratarse de cualquiera de las dos formas. Las más grandes o profundas suelen responder mejor a la escleroterapia. La Dra. Olivo elige según el tamaño, la profundidad y la ubicación del vaso." },
      { q: "¿Volverán a aparecer las venas?", a: "Los vasos tratados se cierran y se desvanecen. Con el tiempo pueden formarse vasos nuevos, sobre todo con el sol, las hormonas o un trabajo de pie. Las sesiones de retoque ocasionales son habituales." },
      { q: "¿Hay tiempo de recuperación?", a: "Muy poco. El tratamiento facial puede dejar un tono rosado durante un día. El tratamiento en las piernas puede dejar pequeños moretones durante aproximadamente una semana, y es posible que se le pida usar compresión y evitar el ejercicio intenso durante algunos días." },
      { q: "¿Se pueden tratar aquí las venas varicosas?", a: "No. Las venas varicosas más grandes requieren un especialista vascular. Si eso es lo que la Dra. Olivo observa en su evaluación, la derivará en lugar de tratarla." },
    ],
    seo: { title: "Eliminación de arañas vasculares en Chicago | Olivo Med Spa", description: "Eliminación de arañas vasculares y venas faciales en Olivo Med Spa, Logan Square, Chicago. Láser o escleroterapia, según lo determine una médica." },
  },
  "mole-removal": {
    name: "Eliminación de lunares y acrocordones",
    tag: "Rostro y cuerpo · Mínimo",
    headline: "Lunares y acrocordones eliminados en consultorio tras una evaluación médica. Cualquier lesión sospechosa se envía primero a patología.",
    summary: "La eliminación de lunares y acrocordones en Olivo Med Spa comienza con una evaluación de la Dra. Olivo. Las lesiones benignas se eliminan en una visita breve en el consultorio. Cualquier lesión sospechosa se deriva a patología antes de cualquier paso estético. Logan Square, Chicago.",
    intro: [
      "Toda eliminación de lunares aquí comienza con una médica examinando la lesión. La Dra. Olivo ejerce la medicina desde 2007 y evalúa los lunares con esa trayectoria. Si un lunar parece benigno y usted desea eliminarlo por comodidad o apariencia, normalmente puede retirarse el mismo día. Si algo en él plantea alguna duda, se envía a patología o se le deriva primero a dermatología.",
      "Los acrocordones, los angiomas rojos y los lunares benignos pequeños se eliminan con técnica de afeitado, cauterización o radiofrecuencia según la lesión. El área se anestesia primero. La cicatrización consiste en una pequeña costra que se resuelve en una o dos semanas, y la marca continúa desvaneciéndose durante los meses siguientes.",
      "Si una lesión es candidata a una eliminación estética es una decisión médica que se toma en su evaluación, no un artículo de menú. La Dra. Olivo también establece expectativas sobre la marca que deja la eliminación, que depende de la lesión, su ubicación y cómo cicatriza su piel.",
    ],
    benefits: ["Evaluación médica antes de cualquier eliminación", "Lesiones sospechosas derivadas a patología", "Acrocordones, angiomas rojos, lunares benignos", "Con anestesia, rápido, tiempo de recuperación mínimo", "Rostro, cuello y cuerpo"],
    session: { duration: "De 15 a 30 minutos aproximadamente, incluida la anestesia", sessions: "Normalmente una sola visita por lesión", downtime: "Mínimo", feels: "Un pequeño pinchazo por la anestesia, y luego presión", results: "Una pequeña costra que se resuelve en una o dos semanas, con la marca desvaneciéndose durante meses" },
    goodFor: ["Adultos con acrocordones que se enganchan en la ropa o las joyas", "Personas con un lunar benigno que desean eliminar por apariencia", "Cualquier persona evaluada en la consulta, con cualquier lesión cambiante o irregular examinada primero"],
    faqs: [
      { q: "¿Dejará cicatriz?", a: "Toda eliminación deja alguna marca. El objetivo es una marca plana y tenue que se desvanezca. La técnica, la ubicación y su propia cicatrización influyen. La Dra. Olivo conversa sobre las expectativas antes de eliminar cualquier lesión." },
      { q: "¿Qué pasa si el lunar parece sospechoso?", a: "Entonces no se elimina de forma estética. Se toma una biopsia y se envía a patología, o se le deriva a dermatología, y los resultados guían el siguiente paso. Ese orden es fijo." },
      { q: "¿Se pueden tratar varios lunares o acrocordones en una sola visita?", a: "Normalmente sí. Es habitual tratar varios acrocordones o lesiones benignas pequeñas en la misma cita una vez que cada una ha sido evaluada." },
      { q: "¿Lo cubre el seguro?", a: "La eliminación estética de lesiones benignas normalmente no está cubierta por el seguro. Si una lesión requiere evaluación médica o patología, esa es una conversación aparte y es posible que se le derive a dermatología." },
    ],
    seo: { title: "Eliminación de lunares en Chicago | Olivo Med Spa", description: "Eliminación de lunares y acrocordones en Olivo Med Spa, Logan Square, Chicago. Evaluación médica primero; las lesiones sospechosas se envían a patología." },
  },
};

export const servicesEs2: Record<string, ServiceEs> = { ...a, ...b };
