// Spanish (Latin American) translations: facials, peels, and add-ons. Facts mirror the English sources. See docs/CONTENT-RULES.md.
import type { ServiceEs } from "./types";

export const servicesEs2b: Record<string, ServiceEs> = {
  "hydrafacial": {
    name: "Hydrafacial",
    tag: "Rostro · Sin tiempo de recuperación",
    headline: "Limpia, extrae e hidrata en una sola visita de 30 a 45 minutos. La piel luce fresca el mismo día.",
    summary: "Hydrafacial utiliza una punta de vórtice para limpiar, exfoliar, extraer e infundir sérums en una sola pasada. De 30 a 45 minutos aproximadamente, sin tiempo de recuperación, en Olivo Med Spa, Logan Square.",
    intro: [
      "Hydrafacial desliza una punta en espiral sobre la piel que exfolia, afloja los residuos de los poros, los aspira y aplica sérums hidratantes, todo en un mismo movimiento. No hay extracción manual ni descamación posterior. Es el facial que las personas reservan antes de un evento porque la piel luce limpia e hidratada al salir.",
      "Una sesión estándar dura entre treinta y cuarenta y cinco minutos. Se pueden añadir boosters para iluminar, reafirmar o calmar, y funciona como tratamiento de mantenimiento mensual entre procedimientos más intensos. Qué boosters, con qué frecuencia y si Hydrafacial o Diamondglow se adapta mejor a su piel se define en su consulta.",
    ],
    benefits: ["Limpia, exfolia, extrae, hidrata", "De 30 a 45 minutos aproximadamente", "Sin tiempo de recuperación, sin descamación", "Boosters para preocupaciones específicas", "Opción de mantenimiento mensual"],
    session: { duration: "De 30 a 45 minutos aproximadamente", sessions: "Una sola sesión, mensual como mantenimiento", downtime: "Ninguno", feels: "Succión fresca que se desplaza por la piel", results: "Piel más limpia y más hidratada el mismo día" },
    goodFor: ["Adultos que desean una frescura visible antes de un evento", "Personas con poros congestionados o piel apagada", "Cualquier persona aprobada en la consulta, incluida la mayoría de los tipos de piel"],
    faqs: [
      { q: "¿Es Hydrafacial adecuado para la piel propensa al acné?", a: "A menudo, sí. El paso de extracción despeja la congestión sin apretar, y se puede añadir un booster purificante. Los brotes activos e inflamados se evalúan primero y es posible que se trabaje alrededor de ellos." },
      { q: "¿Con qué frecuencia debo hacerlo?", a: "Mensual es el ritmo habitual para el mantenimiento. Antes de un evento, resérvelo con dos o tres días de anticipación para que cualquier tono rosado se haya asentado." },
      { q: "¿Puedo añadirlo a otro tratamiento?", a: "Sí. Se combina bien con dermaplaning, una mascarilla Hydrojelly o un peeling ligero. También es un buen paso de mantenimiento entre sesiones de láser o plasma una vez que la piel ha sanado." },
    ],
    seo: { title: "Hydrafacial en Logan Square, Chicago | Olivo Med Spa", description: "Hydrafacial en Olivo Med Spa, Logan Square, Chicago. Limpia, extrae e hidrata en una sola visita de 30 a 45 minutos, sin tiempo de recuperación." },
  },
  "glass-skin-facial": {
    name: "Facial Glass Skin",
    tag: "Rostro · Sin tiempo de recuperación",
    headline: "Un facial de iluminación e hidratación en capas para el acabado liso y luminoso que se conoce como glass skin.",
    summary: "El facial Glass Skin combina en capas una exfoliación suave, activos iluminadores e hidratación profunda para dejar la piel lisa y luminosa. Sin tiempo de recuperación, en Olivo Med Spa, Logan Square.",
    intro: [
      "Glass skin es un acabado, no un producto: tono uniforme, poros cerrados y una superficie tan lisa que refleja la luz. Este facial lo construye por capas. Una exfoliación suave con enzimas o ácidos retira las células apagadas de la superficie, los sérums iluminadores tratan el tono desigual y un paso de hidratación rellena la piel para que la luz rebote de manera uniforme.",
      "Dura cerca de una hora y no hay nada de lo que recuperarse. Se adapta bien a la piel normal a seca y funciona la semana previa a un evento. El protocolo exacto y la línea de productos se ajustan a su piel en la consulta, y su especialista le dirá si un peeling o Hydrafacial le convendría más.",
    ],
    benefits: ["Iluminación e hidratación en capas", "Acabado liso que refleja la luz", "Cerca de una hora, sin tiempo de recuperación", "Conveniente antes de un evento", "Protocolo ajustado a su piel"],
    session: { duration: "Unos 60 minutos", sessions: "Una sola sesión, cada cuatro a seis semanas", downtime: "Ninguno", feels: "Productos frescos en capas con un masaje ligero", results: "Una superficie visiblemente más luminosa y más hidratada el mismo día" },
    goodFor: ["Adultos con piel apagada o deshidratada", "Personas que se preparan para fotos o un evento", "Cualquier persona aprobada en la consulta"],
    faqs: [
      { q: "¿Qué productos se utilizan?", a: "Líneas profesionales que la clínica maneja, incluidas Alastin, ZO Skin Health y Skinbetter Science, elegidas para su piel ese día." },
      { q: "¿Es lo mismo que un Hydrafacial?", a: "No. Hydrafacial se basa en un dispositivo y se centra en la extracción y la hidratación. El facial Glass Skin es manual y aplica activos iluminadores en capas para el tono y la luminosidad. Algunas personas alternan los dos." },
      { q: "¿Cuánto dura el efecto luminoso?", a: "La hidratación y la luminosidad son más visibles durante varios días hasta una semana. Repetirlo cada cuatro a seis semanas, junto con el cuidado en casa, lo mantiene." },
    ],
    seo: { title: "Facial Glass Skin en Logan Square | Olivo Med Spa", description: "Facial Glass Skin en Olivo Med Spa, Logan Square, Chicago. Iluminación e hidratación en capas para un acabado liso y luminoso, sin recuperación." },
  },
  "red-out-facial": {
    name: "Facial Red Out",
    tag: "Rostro · Sin tiempo de recuperación",
    headline: "Un facial calmante para la piel que se enrojece, escuece o permanece roja.",
    summary: "El facial Red Out está diseñado para la piel reactiva y propensa a rojeces. Pasos refrescantes que apoyan la barrera cutánea calman la superficie sin ácidos ni fricción. Sin tiempo de recuperación, en Olivo Med Spa, Logan Square.",
    intro: [
      "La mayoría de los faciales resulta excesiva para la piel reactiva. El facial Red Out elimina los desencadenantes: sin ácidos fuertes, sin vapor, sin extracciones agresivas. En su lugar utiliza una limpieza suave, mascarillas refrescantes y activos calmantes que apoyan la barrera cutánea. Las personas con rubor de tipo rosácea o piel que escuece con productos nuevos suelen salir más calmadas de lo que llegaron.",
      "Dura entre cuarenta y cinco minutos y una hora y puede repetirse cada mes. Para rojeces persistentes, la Dra. Olivo puede combinarlo con Laser Genesis o IPL. Lo que su piel puede tolerar, y si un brote activo debe calmarse primero, se confirma en la consulta antes de reservar cualquier cita.",
    ],
    benefits: ["Sin ácidos, vapor ni extracciones agresivas", "Pasos refrescantes que apoyan la barrera cutánea", "De 45 a 60 minutos aproximadamente", "Sin tiempo de recuperación", "Se combina con Laser Genesis para rojeces persistentes"],
    session: { duration: "De 45 a 60 minutos aproximadamente", sessions: "Una sola sesión, mensual si lo desea", downtime: "Ninguno", feels: "Fresco y calmante de principio a fin", results: "Piel más calmada y menos enrojecida el mismo día" },
    goodFor: ["Adultos con rubor de tipo rosácea o piel sensible", "Personas cuya piel reacciona a la mayoría de los faciales", "Cualquier persona aprobada en la consulta, con los brotes activos evaluados primero"],
    faqs: [
      { q: "¿Puedo hacerlo durante un brote?", a: "A veces. Los pasos se eligen para calmar y no para provocar, pero un brote activo se evalúa primero. Si la piel está demasiado inflamada, es posible que se le pida esperar una o dos semanas." },
      { q: "¿Cuánto dura el efecto calmante?", a: "La superficie permanece más calmada desde varios días hasta un par de semanas, según sus desencadenantes. Los vasos persistentes necesitan Laser Genesis o IPL para cambiar de forma duradera. El cuidado en casa importa tanto como el facial." },
      { q: "¿Qué debo evitar antes y después?", a: "Suspenda los retinoides, los ácidos y los exfoliantes durante algunos días antes y después. Evite el calor, el alcohol y el ejercicio intenso ese mismo día. Use protector solar." },
    ],
    seo: { title: "Facial Red Out para rojeces en Chicago | Olivo Med Spa", description: "Facial Red Out en Olivo Med Spa, Logan Square, Chicago. Un facial calmante que apoya la barrera cutánea, para piel reactiva y propensa a rojeces." },
  },
  "pca-chemical-peels": {
    name: "Peelings químicos PCA",
    tag: "Rostro y cuerpo · De mínimo a pocos días",
    headline: "Peelings profesionales PCA en intensidades graduadas, desde un refresco sin descamación hasta una corrección más profunda.",
    summary: "Los peelings químicos PCA en Olivo Med Spa se eligen por intensidad y fórmula según su preocupación: opacidad, brotes, pigmentación o líneas finas. La profundidad del peeling y el tiempo de recuperación se definen en la consulta. Logan Square, Chicago.",
    intro: [
      "PCA Skin fabrica una gama de peelings profesionales, desde fórmulas suaves que puede hacerse a la hora del almuerzo con poca descamación visible hasta fórmulas más fuertes que se descaman durante varios días y hacen más por la pigmentación y la textura. Los ácidos varían: láctico y mandélico para piel sensible o seca, salicílico para brotes, y mezclas de TCA y retinoides para pigmentación y líneas.",
      "Los peelings funcionan bien en serie, normalmente de tres a seis, con dos a cuatro semanas de separación, seguidos de cuidado en casa con las líneas de la clínica. Qué peeling, a qué intensidad y con qué frecuencia es una decisión médica que se toma en su consulta según su tipo de piel y su historial.",
    ],
    benefits: ["Intensidades desde sin descamación hasta varios días de exfoliación", "Opacidad, brotes, pigmentación, líneas finas", "Rostro, cuello, escote, espalda y manos", "Series de tres a seis", "Peeling elegido mediante una evaluación dirigida por una médica"],
    session: { duration: "De 30 a 45 minutos aproximadamente", sessions: "De tres a seis, con dos a cuatro semanas de separación", downtime: "De mínimo a pocos días, según la intensidad", feels: "Hormigueo y calor durante algunos minutos", results: "Piel más luminosa en una semana, con cambios en pigmentación y textura a lo largo de la serie" },
    goodFor: ["Adultos con piel apagada, brotes o pigmentación desigual", "Personas que buscan una opción graduada antes de un láser", "Cualquier persona aprobada en la consulta, tras revisar el tipo de piel, los medicamentos y la exposición reciente al sol"],
    faqs: [
      { q: "¿Realmente se me descamará la piel?", a: "Depende del peeling. Las fórmulas más ligeras causan poca o ninguna descamación visible. Los peelings de intensidad media se descaman durante tres a cinco días. Sabrá cuál va a recibir antes de que se aplique." },
      { q: "¿Se pueden usar peelings en pieles más oscuras?", a: "Sí, con el ácido y la intensidad adecuados. Algunas fórmulas se adaptan mejor a los tipos de piel más oscuros que otras, y la fórmula equivocada puede causar cambios de pigmentación. La Dra. Olivo la selecciona en consecuencia en la consulta." },
      { q: "¿Cómo me preparo?", a: "Suspenda los retinoides y los ácidos exfoliantes varios días antes, evite el sol y la cera, e infórmenos sobre cualquier medicamento. Una preparación en casa con las líneas de la clínica durante un par de semanas mejora la uniformidad con la que actúa el peeling." },
    ],
    seo: { title: "Peelings químicos PCA en Logan Square | Olivo Med Spa", description: "Peelings químicos PCA en Olivo Med Spa, Logan Square, Chicago. Intensidades graduadas para opacidad, brotes, pigmentación y líneas finas." },
  },
  "diamondglow": {
    name: "Diamondglow",
    tag: "Rostro · Sin tiempo de recuperación",
    headline: "Exfoliación con punta de diamante, extracción e infusión de sérum en una sola pasada.",
    summary: "Diamondglow utiliza una varilla con punta de diamante para exfoliar, extraer e infundir sérums profesionales al mismo tiempo. De 30 a 45 minutos aproximadamente, sin tiempo de recuperación, en Olivo Med Spa, Logan Square.",
    intro: [
      "Diamondglow es un facial tres en uno. Una varilla con punta de diamante exfolia físicamente la superficie mientras la succión extrae los residuos de los poros y se infunde un sérum en la piel recién despejada. La exfoliación física lo convierte en un paso de renovación más intenso que Hydrafacial, lo que conviene a personas con textura más áspera o mayor congestión.",
      "Las sesiones duran entre treinta y cuarenta y cinco minutos. La piel puede lucir rosada durante una hora. Los sérums se eligen para hidratar, iluminar o purificar. Si Diamondglow o Hydrafacial se adapta mejor a su piel, y con qué frecuencia repetirlo, se decide en su consulta después de examinar su textura y sensibilidad.",
    ],
    benefits: ["Exfolia, extrae e infunde en una sola pasada", "Punta de diamante para una renovación física", "Sérum elegido según su preocupación", "De 30 a 45 minutos aproximadamente", "Sin tiempo de recuperación"],
    session: { duration: "De 30 a 45 minutos aproximadamente", sessions: "Una sola sesión, cada cuatro a seis semanas", downtime: "Ninguno", feels: "Un deslizamiento firme y granulado con succión ligera", results: "Piel más lisa y luminosa el mismo día" },
    goodFor: ["Adultos con textura áspera o poros congestionados", "Personas que buscan más exfoliación que con un Hydrafacial", "Cualquier persona aprobada en la consulta, con los brotes activos evaluados primero"],
    faqs: [
      { q: "¿Diamondglow o Hydrafacial?", a: "Diamondglow exfolia más, por lo que conviene a la piel más gruesa o áspera. Hydrafacial es más suave y más hidratante, por lo que conviene a la piel sensible o seca. Su especialista le recomienda uno en la consulta." },
      { q: "¿Duele?", a: "No. Se siente como un deslizamiento firme y granulado con succión ligera. La piel puede quedar rosada durante una hora después y ligeramente sensible esa noche." },
      { q: "¿Con qué frecuencia debo reservarlo?", a: "Cada cuatro a seis semanas es lo habitual. Antes de un evento, deje uno o dos días para que cualquier tono rosado se asiente." },
    ],
    seo: { title: "Facial Diamondglow en Logan Square | Olivo Med Spa", description: "Diamondglow en Olivo Med Spa, Logan Square, Chicago. Exfoliación con punta de diamante, extracción e infusión de sérum en 30 a 45 minutos, sin recuperación." },
  },
  "glo2facial": {
    name: "Glo2Facial de Geneo",
    tag: "Rostro · Sin tiempo de recuperación",
    headline: "Un facial de oxigenación que aprovecha la propia respuesta de la piel para llevar oxígeno a la superficie.",
    summary: "Glo2Facial de Geneo combina un pod exfoliante suave, oxigenación desde el interior y masaje linfático con infusión por ultrasonido. Unos 45 minutos, sin tiempo de recuperación, en Olivo Med Spa, Logan Square.",
    intro: [
      "Glo2Facial comienza con un Oxypod que reacciona con un gel sobre la piel para crear una exfoliación burbujeante. Esa reacción hace que el cuerpo envíe sangre rica en oxígeno a la superficie, y a eso se refiere la gente cuando habla de un facial de oxigenación. Siguen un paso de masaje linfático y una infusión por ultrasonido de ingredientes activos.",
      "La sesión completa dura unos cuarenta y cinco minutos. Después, la piel luce rellena y uniforme, sin tiempo de recuperación. Los pods se eligen para hidratar, iluminar o equilibrar. Qué pod se adapta a su piel, y si Glo2Facial u otro facial es la mejor opción para su preocupación, se confirma en la consulta.",
    ],
    benefits: ["Exfoliación, oxigenación, infusión", "Masaje linfático incluido", "Unos 45 minutos", "Sin tiempo de recuperación", "Pods ajustados a su preocupación"],
    session: { duration: "Unos 45 minutos", sessions: "Una sola sesión, mensual como mantenimiento", downtime: "Ninguno", feels: "Un burbujeo cálido, y luego un masaje relajante", results: "Piel más rellena y uniforme el mismo día" },
    goodFor: ["Adultos con piel apagada o de aspecto cansado", "Personas que buscan un facial que se sienta como un tratamiento y como un descanso", "Cualquier persona aprobada en la consulta"],
    faqs: [
      { q: "¿En qué se diferencia de un facial de oxígeno?", a: "Los faciales de oxígeno rocían oxígeno sobre la piel. Glo2Facial utiliza una reacción en la superficie para hacer que el cuerpo aporte oxígeno desde el interior, y luego infunde activos con ultrasonido." },
      { q: "¿Es adecuado para la piel sensible?", a: "A menudo, sí. No contiene ácidos fuertes y la exfoliación es suave. La sensibilidad y cualquier afección activa se revisan en la consulta antes de reservar." },
      { q: "¿Con qué frecuencia debo hacerlo?", a: "Mensual es lo habitual para el mantenimiento. Una sola sesión antes de un evento también funciona bien, porque la piel luce rellena y uniforme de inmediato." },
    ],
    seo: { title: "Glo2Facial de Geneo en Chicago | Olivo Med Spa", description: "Glo2Facial en Olivo Med Spa, Logan Square, Chicago. Facial de oxigenación con exfoliación, masaje linfático e infusión en 45 minutos, sin recuperación." },
  },
  "dermaplaning": {
    name: "Dermaplaning",
    tag: "Rostro · Sin tiempo de recuperación",
    headline: "Exfoliación manual que retira las células muertas de la superficie y el vello fino en una sola pasada.",
    summary: "El dermaplaning utiliza una hoja estéril para retirar las células muertas y el vello fino del rostro. La piel se siente lisa, el maquillaje se asienta mejor y los productos se absorben de manera más uniforme. Unos 30 minutos, sin tiempo de recuperación, en Olivo Med Spa, Logan Square.",
    intro: [
      "Un profesional capacitado mantiene la piel tensa y desliza una hoja estéril en un ángulo poco profundo por el rostro. Retira la capa superior de células muertas junto con el vello fino, esa pelusa que atrapa la luz y la base de maquillaje. No hay químicos, ni calor, ni tiempo de recuperación. La piel luce más luminosa de inmediato.",
      "El dermaplaning dura unos treinta minutos por sí solo y a menudo se añade antes de un peeling o un facial para que los activos lleguen a la piel de manera más uniforme. Es adecuado para la mayoría de los tipos de piel, salvo en casos de acné activo. La idoneidad se confirma en la consulta, y su especialista revisará si hay brotes o irritación antes de comenzar.",
    ],
    benefits: ["Células muertas y vello fino retirados a la vez", "Suavidad inmediata", "El maquillaje y los productos se aplican de manera más uniforme", "Unos 30 minutos", "Se añade a un peeling o un facial"],
    session: { duration: "Unos 30 minutos", sessions: "Una sola sesión, cada cuatro a seis semanas", downtime: "Ninguno", feels: "Una ligera sensación de raspado, no punzante", results: "Piel más lisa y luminosa de inmediato" },
    goodFor: ["Adultos con piel apagada o vello fino visible", "Personas que se preparan para un evento o un peeling", "Cualquier persona aprobada en la consulta, con el acné activo evaluado primero"],
    faqs: [
      { q: "¿El vello volverá a crecer más grueso?", a: "No. El vello fino no cambia al cortarlo. Vuelve a crecer con la misma finura y al mismo ritmo, y por lo general se nota de nuevo después de tres a cuatro semanas." },
      { q: "¿Puedo hacerlo con acné?", a: "No sobre brotes activos, ya que la hoja puede propagar bacterias e irritar la piel inflamada. Una vez que la piel está calmada puede hacerse, y puede ayudar a que los productos funcionen mejor después." },
      { q: "¿Con qué frecuencia debo reservarlo?", a: "Cada cuatro a seis semanas coincide con la renovación natural de la piel y con el nuevo crecimiento del vello fino. Muchas personas lo combinan con un facial mensual." },
    ],
    seo: { title: "Dermaplaning en Logan Square, Chicago | Olivo Med Spa", description: "Dermaplaning en Olivo Med Spa, Logan Square, Chicago. Exfoliación manual que retira células muertas y vello fino en unos 30 minutos, sin recuperación." },
  },
  "lash-lift-and-tint": {
    name: "Lifting y tinte de pestañas",
    tag: "Ojos · Sin tiempo de recuperación",
    headline: "Pestañas naturales rizadas y oscurecidas que duran semanas, sin extensiones ni rímel diario.",
    summary: "Un lifting de pestañas riza sus pestañas naturales desde la base y un tinte las oscurece. Cerca de una hora, sin tiempo de recuperación, con resultados durante varias semanas. Disponible en Olivo Med Spa, Logan Square.",
    intro: [
      "Un lifting de pestañas fija sus pestañas naturales sobre un molde de silicona con una solución suave, de modo que se curvan hacia arriba desde la raíz y lucen más largas sin extensiones. Después se aplica un tinte para oscurecerlas, lo que importa sobre todo a quienes tienen pestañas claras o finas. Sale con pestañas que parecen llevar rímel, y sin nada que retirar por la noche.",
      "La cita dura cerca de una hora con los ojos cerrados. Los resultados suelen durar de seis a ocho semanas, que es un ciclo natural de las pestañas. Mantenga las pestañas secas durante el primer día. Puede recomendarse una prueba de sensibilidad para el tinte, y la idoneidad se confirma en la consulta.",
    ],
    benefits: ["Pestañas naturales, sin extensiones", "Rizado y color en una sola visita", "Cerca de una hora", "Sin tiempo de recuperación", "Suele durar de seis a ocho semanas"],
    session: { duration: "Unos 60 minutos", sessions: "Una sola sesión, cada seis a ocho semanas", downtime: "Ninguno", feels: "Ojos cerrados, presión ligera sobre los párpados", results: "Pestañas levantadas y más oscuras de inmediato" },
    goodFor: ["Adultos con pestañas rectas o claras", "Personas que desean prescindir del rímel o del rizador diario", "Cualquier persona aprobada en la consulta, tras revisar las sensibilidades oculares"],
    faqs: [
      { q: "¿Daña las pestañas?", a: "No cuando se realiza con el intervalo adecuado y no se repite con demasiada frecuencia. Esperar las seis a ocho semanas completas entre liftings protege la pestaña. El exceso de procesamiento es lo que causa la rotura." },
      { q: "¿Puedo usar rímel después?", a: "Sí, pasadas las primeras veinticuatro horas. Muchas personas descubren que ya no lo necesitan. Evite las fórmulas a prueba de agua y los desmaquillantes a base de aceite, que aflojan el lifting." },
      { q: "¿Y si uso lentes de contacto?", a: "Retírelos antes de la cita y traiga su estuche. Puede volver a ponérselos una vez terminado el tratamiento." },
    ],
    seo: { title: "Lifting y tinte de pestañas en Logan Square | Olivo Med Spa", description: "Lifting y tinte de pestañas en Olivo Med Spa, Logan Square, Chicago. Pestañas naturales rizadas y oscurecidas en cerca de una hora, sin extensiones." },
  },
  "hydrojelly-mask": {
    name: "Mascarilla Hydrojelly (complemento)",
    tag: "Rostro · Complemento",
    headline: "Una mascarilla de gel refrescante que se retira en una pieza, añadida a cualquier facial para sellar la hidratación.",
    summary: "La mascarilla Hydrojelly es un complemento para cualquier facial en Olivo Med Spa. Mezclada al momento y aplicada como una capa refrescante, retiene los sérums de su tratamiento y calma la piel. Unos 15 minutos adicionales, en Logan Square.",
    intro: [
      "Las mascarillas Hydrojelly se mezclan al momento a partir de un polvo y agua, se aplican como una capa gruesa y fresca que se convierte en gel, y luego se retiran en una sola pieza. La capa mantiene la humedad y los sérums activos de su facial en contacto con la piel mientras se asienta. Las fórmulas varían: hialurónico para hidratación, pepino o aloe para calmar, y mezclas iluminadoras para el tono.",
      "Añade unos quince minutos a un facial y puede reservarse con Hydrafacial, Diamondglow, Glo2Facial o dermaplaning. Qué fórmula añadir se elige con su especialista ese día, según cómo responda su piel al facial, y la idoneidad se confirma en la consulta.",
    ],
    benefits: ["Sella los sérums de su facial", "Refrescante y calmante", "Unos 15 minutos adicionales", "Fórmulas para hidratación, calma o tono", "Se añade a la mayoría de los faciales"],
    session: { duration: "Unos 15 minutos añadidos a un facial", sessions: "Complemento para cualquier facial", downtime: "Ninguno", feels: "Fría y pesada, y luego se retira limpiamente", results: "Piel más rellena y calmada al salir" },
    goodFor: ["Cualquier persona que reserve un facial y desee hidratación adicional", "Personas cuya piel se enrojece después de la exfoliación", "Cualquier persona aprobada en la consulta"],
    faqs: [
      { q: "¿A qué faciales se puede añadir?", a: "A la mayoría. Es un cierre natural para Hydrafacial, Diamondglow, Glo2Facial, dermaplaning y el facial Glass Skin. Solicítela al reservar y se añade a la cita." },
      { q: "¿Puedo reservarla por sí sola?", a: "Está diseñada como complemento. Pregunte al reservar si hay disponible una cita de mascarilla independiente." },
      { q: "¿Es adecuada para la piel sensible?", a: "Normalmente, sí. Las fórmulas calmantes se eligen precisamente para eso. Los ingredientes se revisan con usted antes de aplicarla si tiene sensibilidades conocidas." },
    ],
    seo: { title: "Mascarilla Hydrojelly en Chicago | Olivo Med Spa", description: "Mascarilla Hydrojelly en Olivo Med Spa, Logan Square, Chicago. Complemento de gel refrescante que sella la hidratación después de cualquier facial." },
  },
};
