// Every interface string on the public site, English. content/ui/es.ts mirrors this shape.
export const en = {
  lang: "en",
  nav: { treatments: "Treatments", concerns: "Concerns", memberships: "Memberships", specials: "Specials", about: "About", visit: "Visit", quiz: "Treatment quiz", byGoal: "By goal", byDevice: "By device", allTreatments: "All treatments", notSure: "Not sure where to start?", quizLine: "Take the two-minute treatment quiz.", menu: "Menu", close: "Close", openMenu: "Open menu", book: "Book", bookConsult: "Book a consultation", textUs: "Text us", call: "Call", callOrText: "call or text", switchLang: "ES", switchLangLabel: "ES, cambiar a español" },
  footer: { blurb: "Physician owned and led since 2013. The full BTL and Alma platforms under one roof in Logan Square, Chicago.", treatments: "Treatments", byConcern: "By concern", technology: "Technology", clinic: "Clinic", team: "Team", bookAndPay: "Book and pay", bookOnline: "Book online", financing: "Financing through Cherry", portal: "Member portal", serving: "Serving", a11y: "We want everyone to be able to use this site. If something is hard to reach, call us and we will help.", privacy: "Privacy", terms: "Terms", accessibility: "Accessibility", siteMap: "Site map", director: "Medical director: Jacqueline Olivo, MD.", trademarks: "All product names are trademarks of their respective owners.", results: "Individual results vary. Candidacy and expectations are set at consultation.", closed: "Closed", to: "to", links: [["/about", "About"], ["/team", "Team"], ["/for-patients", "For patients"], ["/memberships", "Memberships"], ["/specials", "Specials"], ["/gift-cards", "Gift cards"], ["/financing", "Financing"], ["/skincare", "Skincare"], ["/treatments/for-men", "For men"], ["/results", "Results"], ["/reviews", "Reviews"], ["/blog", "Journal"], ["/visit", "Visit and contact"]] as [string, string][] },
  textNow: { label: "Contact shortcuts", text: "Text us", textShort: "Text", call: "Call", book: "Book", body: "Hi Olivo, I would like to book a consultation." },
  blocks: { home: "Home", learnMore: "Learn more", explore: "Explore", seeAll: "See all", goodToKnow: "Good to know", ready: "Ready when you are.", readyLine: "Book online any time, text us, or call the clinic during hours.", financingNote: "Financing available through Cherry. Terms are set by Cherry at application.", whatToExpect: "What to expect", resultsVary: "Individual results vary.", consult: "Consultation", consultLine: "A conversation with the clinical team about what you want to change, a candidacy check, and a written plan.", treatment: "Treatment", treatmentLine: (n: string) => `A ${n} session in the clinic, on the schedule the plan sets.`, aftercare: "Aftercare", aftercareLine: "Plain-language instructions and a number to call or text.", followUp: "Follow-up", followUpLine: "A check on the result and what, if anything, comes next." },
  photo: { soon: "Photography coming soon", gallerySoon: "Before and after gallery coming soon", portraitSoon: "Portrait coming soon" },
  hero: { kicker: "Logan Square, Chicago", title: "Come as you are. Leave as you intend.", sub: "Physician owned and led by Jacqueline Olivo, MD, with the full BTL and Alma platforms in one calm clinic on West Fullerton.", book: "Book a consultation", quiz: "Find my treatment", clinic: "Clinic", hours: "Hours", hoursLine: "Mon to Fri 10 to 7, Sat 10 to 5", reach: "Reach us", reachLine: "Text or call 872-315-3481", scroll: "Scroll" },
  home: {
    proofKicker: "The clinic", proofTitle: "Physician owned. Physician led. One calm clinic on Fullerton.",
    stats: [["Physician owned and led since", "Jacqueline Olivo, MD, founder and medical director"], ["Device platforms on site", "The full BTL and Alma platforms under one roof"], ["Days a week", "Mon to Fri 10 to 7, Sat 10 to 5, in Logan Square"]] as [string, string][],
    treatKicker: "Treatments", treatTitle: "What can we help you with?", treatSub: "Nine ways in. Every plan begins with a consultation, and every treatment is matched to you, not to a menu.", concernPrompt: "Prefer to start from a concern?", browseConcern: "Browse by concern",
    quizKicker: "Two-minute quiz", quizTitle: "Not sure where to start? Tell us what you would change.", quizSub: "Five questions. You get up to three treatments to read about and a text you can send us with one tap. No email required.", quizOpen: "Open the full quiz",
    techKicker: "Technology", techTitle: "The full BTL and Alma platforms, under one roof", techSub: "Nine device platforms, named by brand. If it is here, it is because Dr. Olivo chose it, trained on it, and uses it.", techCta: "Ask which is right for you",
    doctorKicker: "Physician owned and led", doctorTitle: "Meet Dr. Olivo", doctorRole: "Founder, CEO, and medical director", quote: "Aging is optional.", doctorBio: "Dr. Olivo trained in family medicine and has practiced since 2007. She opened Olivo Med Spa in 2013 and remains its medical director, which is why the equipment list reads the way it does: chosen by a physician, for patients she sees herself.", doctorCta: "Read her story", teamCta: "Meet the team",
    resultsKicker: "Results", resultsTitle: "Results belong to the person who earned them.", resultsSub: "Real before and after images are shown only with written patient authorization and are labelled with treatment and session count.", resultsPolicy: "About our results policy",
    reviewsKicker: "In their words", reviewsTitle: "What patients have said", reviewsNote: "Testimonials as published by patients on olivomedspa.com. Individual experiences vary.", reviewsGoogle: "Read reviews on Google", via: "via",
    memKicker: "Memberships and financing", memTitle: "Keep a rhythm instead of starting over.", memSub: "Three clubs, one for skin, one for body, one for laser hair reduction. Financing available through Cherry.", memCta: "See the details", memNote: "Terms are shown at the clinic and in the member portal.",
    visitKicker: "Logan Square", visitTitle: "Visit us on Fullerton", hours: "Hours", parking: "Parking and transit", directions: "Get directions", bookVisit: "Book a visit", alsoServing: "Also serving", mapLabel: "Open directions to 2550 W. Fullerton Ave in Google Maps",
    finalTitle: "We would love to see you.", finalLine: "Book a consultation online any time, text us, or call the clinic during hours.",
  },
};


