// Page-level interface strings, Latin American Spanish. Mirrors content/ui/en-pages.ts.
// Register: formal usted. No exclamation marks, no em dashes, no prices.
import type { enPages } from "./en-pages";

export const esPages: typeof enPages = {
  treatments: { crumb: "Tratamientos", kicker: "Todos los tratamientos", title: (n: number) => `${n} tratamientos. Nueve plataformas. Un plan dirigido por una médica.`, lede1: "Explore por objetivo a continuación, por", lede2: "inquietud", lede3: ", o", lede4: "responda el cuestionario de dos minutos", overview: "Resumen", countIn: (n: number, c: string) => `${n} ${n === 1 ? "tratamiento" : "tratamientos"} en ${c}`, categoryKicker: "Tratamientos", categoryLede: "Cada plan comienza con una consulta con el equipo dirigido por una médica.", findMine: "Encontrar mi tratamiento", seeOptions: "Ver las opciones", relatedConcerns: "Inquietudes relacionadas", talk: (c: string) => `Hablemos sobre ${c}.` },
  service: { aboutKicker: "Sobre el tratamiento", oftenChosen: "Se elige a menudo para", feels: "Qué se siente", notice: "Cuándo se nota el cambio", goodFor: "Buenos candidatos", bookThis: (n: string) => `Reservar ${n}`, textAbout: "Escríbanos al respecto", session: "Sesión", plan: "Plan", downtime: "Recuperación", where: "Dónde", whereValue: "Logan Square", facts: "Los datos describen un plan típico. La candidatura y las expectativas se definen en la consulta.", pairedWith: "Se combina a menudo con", all: (c: string) => `Todo en ${c}`, answered: (n: string) => `${n}: preguntas frecuentes`, askAbout: (n: string) => `Pregunte sobre ${n}.`, askLine: "Reserve en línea en cualquier momento, o escríbanos y el equipo le responderá en horario de atención.", sms: (n: string) => `Hola Olivo, me interesa ${n}. ¿Podemos agendar una consulta?`, notSure: "¿Tiene dudas de que sea el indicado?", quizLine: "Responda el cuestionario de dos minutos." },
  concerns: { crumb: "Inquietudes", kicker: "Por inquietud", title: "Empiece por lo que le gustaría cambiar.", lede: "Dieciséis razones comunes por las que las personas nos visitan, cada una con los tratamientos que la clínica elige y por qué. O bien", quiz: "responda el cuestionario", seeTreatments: "Ver tratamientos", concernKicker: "Inquietud", howWeThink: "Cómo lo abordamos", reachFor: "Tratamientos que elegimos", order: "En el orden en que la clínica suele considerarlos. El adecuado para usted se decide en la consulta.", together: "Veámoslo juntos.", sms: (n: string) => `Hola Olivo, me gustaría ayuda con ${n}. ¿Podemos agendar una consulta?` },
  area: { kicker: (n: string) => `Med spa cerca de ${n}`, title: (n: string, t: string) => `De ${n} a Olivo Med Spa: ${t}.`, directions: "Cómo llegar", gettingHere: (n: string) => `Cómo llegar desde ${n}`, hoursLine: "Lun a vie de 10 AM a 7 PM, sáb de 10 AM a 5 PM, domingo cerrado.", bookMost: (n: string) => `Lo que más reservan los pacientes de ${n}`, popular: "Puntos de partida populares. Cada plan se define en la consulta.", allTreatments: "Todos los tratamientos", seeYou: "Le esperamos en Fullerton.", seeYouLine: (t: string, n: string) => `Reserve en línea, escríbanos o llame. Estamos a ${t} de ${n}.`, visitCrumb: "Visítenos" },
  blog: { crumb: "Revista", kicker: "Revista", title: "Notas de la clínica, en palabras sencillas.", read: "Leer", minRead: "min de lectura", min: "min", reviewed: "Revisado por el equipo clínico de Olivo Med Spa. Contenido educativo, no asesoramiento médico. La candidatura y las expectativas se definen en la consulta.", related: "Tratamientos relacionados", all: "Todas las publicaciones" },
  about: { crumb: "Nosotros", kicker: "Sobre la clínica", title: "La clínica de una médica, no una franquicia.", lede: "Olivo Med Spa abrió en West Fullerton en 2013. La Dra. Jacqueline Olivo sigue escribiendo los planes, eligiendo la tecnología y atendiendo a los pacientes personalmente. Esa es toda la idea.", howKicker: "Cómo trabajamos", howTitle: "Adaptar el tratamiento a la persona, no la persona a un menú.", how: ["La mayoría de las clínicas cuentan con dos o tres dispositivos y orientan a todos hacia ellos. Olivo cuenta con las plataformas completas de BTL y Alma, además de CO2, Miradry y Hydrafacial, de modo que el plan puede partir de lo que usted quiere cambiar y no de lo que hay en la sala.", "Cada plan comienza con una consulta. Usted se va con un plan por escrito en palabras sencillas: qué recomendamos, en qué consiste, qué puede y qué no puede hacer, y cuánto cuesta. No se reserva nada hasta que usted lo haya leído.", "Los tratamientos los realizan la Dra. Olivo y su equipo con licencia, bajo su dirección como directora médica."], firstVisit: "Su primera visita", teamKicker: "El equipo", teamTitle: "Pequeño por diseño.", teamSub: "Una médica, una esteticista principal y un equipo con licencia que sabrá su nombre en la segunda visita.", profile: "Perfil", cta: "Venga a conocer la clínica.", ctaLine: "Reserve una consulta o escríbanos primero con una pregunta." },
  team: { crumb: "Equipo", kicker: "El equipo", title: "Las personas que realmente le atenderán.", focus: "Enfoque", bookWith: "Reservar con el equipo", all: "Todo el equipo" },
  memberships: { crumb: "Membresías", kicker: "Membresías", title: "Mantenga un ritmo en lugar de empezar de nuevo.", lede: "Piel, cuerpo y reducción de vello con láser, cada uno como programa mensual con un crédito, precios para miembros y un lugar fijo en el calendario.", portal: "Abrir el portal de miembros", text: "Escríbanos al respecto", tiers: "Niveles", builtAround: "Basado en", join: "Únase en el portal", note: "Los términos mensuales, los precios y la cancelación se muestran en el portal de miembros y en la clínica.", finKicker: "Financiamiento", apply: "Solicitar a través de Cherry", how: "Cómo funciona", finAnswered: "Financiamiento: preguntas frecuentes", cta: "Pregunte qué membresía le conviene.", sms: "Hola Olivo, me gustaría conocer las membresías." },
  financing: { crumb: "Financiamiento", kicker: "Financiamiento", callUs: "Llamar", disclaimer: "Olivo Med Spa no establece los términos de financiamiento. Las tasas, la aprobación y la duración de los planes las determina Cherry.", how: "Cómo funciona", steps: [["Solicite", "Use el enlace de Cherry antes de su visita o en la recepción. Toma unos minutos."], ["Vea sus opciones", "Cherry le muestra los planes para los que califica."], ["Elija al pagar", "Seleccione un plan cuando pague un tratamiento o paquete."], ["Pague a Cherry a plazos", "Los pagos van a Cherry según el calendario que usted eligió."]] as [string, string][], answered: "Financiamiento: preguntas frecuentes" },
  specials: { crumb: "Promociones", kicker: "Este mes", title: "Promociones, actualizadas cada mes.", text: "Escríbanos por las ofertas de este mes", portal: "Portal de miembros", offer: "Oferta", book: "Reservar", standing: "¿Prefiere un descuento fijo?", standingLine: (n: string) => `${n} incluyen precios para miembros cada mes.`, seeMem: "Ver membresías", cta: "Pregunte qué hay este mes.", sms: "Hola Olivo, ¿cuáles son las promociones de este mes?" },
  skincare: { crumb: "Cuidado de la piel", kicker: "Cuidado de la piel", title: "Tres líneas. Dispensadas, no vendidas.", text: "Escríbanos para una consulta de piel", cta: "Empiece con una consulta de piel.", sms: "Hola Olivo, me gustaría una consulta de cuidado de la piel." },
  results: { crumb: "Resultados", kicker: "Resultados", title: "Los resultados pertenecen a la persona que los logró.", body: ["Mostramos imágenes de antes y después únicamente con autorización escrita del paciente, etiquetadas con el tratamiento y el número de sesiones y nada más: sin edades, sin iniciales, sin afirmaciones sobre lo que usted debería esperar.", "Los resultados varían de una persona a otra. Lo que un tratamiento puede y no puede hacer por usted se define con la médica en su consulta, donde también podemos mostrarle casos autorizados en la clínica."], cta: "Vea resultados autorizados en persona.", ctaLine: "Reserve una consulta y pida ver casos del tratamiento que está considerando." },
  reviews: { crumb: "Reseñas", title: "Reseñas", lede1: "Algunas en sus propias palabras a continuación. Cada reseña pública vive en", lede2: ", donde no podemos editarlas.", cta: "Venga y forme su propia opinión." },
  visit: { crumb: "Visítenos", title: "Visítenos y contacto" },
  contact: { crumb: "Contacto", title: "Escríbanos. Es la forma más rápida de comunicarse con la clínica.", lede: "Envíe un mensaje de texto con lo que tiene en mente y el equipo le responderá en horario de atención. O reserve directamente en el calendario.", textNow: "Escribir ahora", textLine: "Abre sus mensajes con una nota ya redactada.", call: "Llamar", callLine: "Lun a vie de 10 a 7, sáb de 10 a 5.", bookOnline: "Reservar en línea", bookTitle: "En cualquier momento", bookLine: "Elija una consulta o un tratamiento y la hora que le convenga.", sms: "Hola Olivo, tengo una pregunta sobre un tratamiento." },
  composer: { kicker: "Redacte su mensaje", title: "Cuéntenos qué tiene en mente.", name: "Su nombre", optional: "Opcional", time: "Mejor horario", noPref: "Sin preferencia", times: ["Mañanas entre semana", "Tardes entre semana", "Noches entre semana", "Sábado"], interest: "Le interesa", notSure: "Aún no lo sé", consultOnly: "Solo una consulta", anything: "Algo más", placeholder: "Una pregunta, un tratamiento que ya se haya hecho, cualquier dato útil", send: "Enviarnos este mensaje", copy: "Copiar el mensaje", copied: "Copiado", callInstead: "Prefiero llamar", note: "Abre su aplicación de mensajes con la nota redactada. Nada se guarda en este sitio. El equipo responde en horario de atención.", hi: "Hola Olivo", thisIs: (n: string) => `, le escribe ${n}`, interested: (i: string) => `Me interesa ${i}.`, works: (t: string) => `El horario que mejor me conviene: ${t}.`, ask: "¿Podemos agendar una consulta?" },
  book: { crumb: "Reservar", kicker: "Reservar en línea", title: "Elija una hora. Nosotros nos encargamos del resto.", lede: "¿Primera vez con nosotros? Elija una consulta. ¿Ya tiene un plan? Reserve el tratamiento directamente. El calendario está en vivo y confirma por mensaje de texto o correo electrónico.", facts: ["Lun a vie de 10 AM a 7 PM, sáb de 10 AM a 5 PM", "2550 W. Fullerton Ave, Logan Square", "Financiamiento disponible a través de Cherry. Los términos los establece Cherry al momento de la solicitud."], preferText: "¿Prefiere escribir? Escríbanos", call: "Llamar", vagaro: "O abra la página de reservas en Vagaro", notSure: "¿No sabe qué reservar?", quiz: "Responda el cuestionario de dos minutos", first: "primero.", widgetKicker: "Calendario en vivo", widgetTitle: "Vea los horarios disponibles y reserve en aproximadamente un minuto.", widgetLine: "El calendario lo gestiona Vagaro, el sistema de reservas de la clínica. Se abre aquí mismo.", open: "Abrir el calendario", newTab: "O ábralo en una pestaña nueva", fallback1: "Si el calendario no carga,", fallback2: "ábralo en Vagaro", fallback3: "o escríbanos." },
  quiz: { crumb: "Cuestionario de tratamientos", kicker: "Dos minutos", title: "Cuéntenos qué cambiaría. Le orientaremos hacia algo útil.", lede: "Cinco preguntas, sin necesidad de correo electrónico. Recibe hasta tres tratamientos para leer y un mensaje de texto que puede enviarnos con un solo toque." },
  patients: { crumb: "Para pacientes", kicker: "Para pacientes", title: "Su primera visita, en palabras sencillas.", aftercare: "Cuidados posteriores", howTitle: "Cómo es una primera visita", plansVary: "Los planes individuales varían.", bring: "Qué traer", late: "¿Va con retraso o necesita cambiar una visita?", lateLine: (p: string) => `Escriba o llame al ${p} lo antes posible y el equipo lo resolverá.`, policiesKicker: "Políticas", policiesTitle: "Políticas de la clínica", aftercareKicker: "Cuidados posteriores", aftercareTitle: "Después de su tratamiento", inCategory: "Tratamientos en esta categoría", faqTitle: "Preguntas frecuentes", cta: "¿Preguntas antes de reservar?", ctaLine: "Escríbanos y una persona le responderá en horario de atención.", sms: "Hola Olivo, tengo una pregunta antes de reservar." },
  gift: { crumb: "Tarjetas de regalo", kicker: "Tarjetas de regalo", title: "Regale la visita, no las conjeturas.", buy: "Comprar a través del sitio de reservas", text: "Escríbanos para gestionar una", how: "Cómo funciona", know: "Conviene saber", notSure: "¿No sabe qué le gustaría a esa persona? Indíquele el", quiz: "cuestionario de dos minutos", or: "o una", page: "página de tratamiento", cta: "Pídanos que le preparemos una.", sms: "Hola Olivo, me gustaría comprar una tarjeta de regalo." },
  siteMap: { crumb: "Mapa del sitio", title: "Todas las páginas, en una lista.", lede: (s: number, c: number, a: number, p: number) => `${s} tratamientos, ${c} inquietudes, ${a} vecindarios, ${p} publicaciones de la revista y las páginas de la clínica.`, clinic: "Clínica", concerns: "Inquietudes", allConcerns: "Todas las inquietudes", neighborhoods: "Vecindarios", journal: "Revista", allPosts: "Todas las publicaciones", all: (c: string) => `Todo en ${c}` },
  legal: { updated: (d: string) => `Última actualización: ${d}.` },
  notFound: { title: "Esa página se movió o nunca existió.", line: "Pruebe con la lista de tratamientos, o escriba a la clínica y le orientaremos.", all: "Todos los tratamientos", home: "Inicio" },
};
