// Every interface string on the public site, Latin American Spanish. Mirrors content/ui/en.ts.
// Register: formal usted. No exclamation marks, no em dashes, no prices.
import type { en } from "./en";

export const es: typeof en = {
  lang: "es",
  nav: { treatments: "Tratamientos", concerns: "Inquietudes", memberships: "Membresías", specials: "Promociones", about: "Nosotros", visit: "Visítenos", quiz: "Cuestionario de tratamientos", byGoal: "Por objetivo", byDevice: "Por dispositivo", allTreatments: "Todos los tratamientos", notSure: "¿No sabe por dónde empezar?", quizLine: "Responda el cuestionario de dos minutos.", menu: "Menú", close: "Cerrar", openMenu: "Abrir el menú", book: "Reservar", bookConsult: "Reservar una consulta", textUs: "Escríbanos", call: "Llamar", callOrText: "llame o escríbanos", switchLang: "EN", switchLangLabel: "EN, switch to English" },
  footer: { blurb: "Clínica de propiedad y dirección médica desde 2013. Las plataformas completas de BTL y Alma bajo un mismo techo en Logan Square, Chicago.", treatments: "Tratamientos", byConcern: "Por inquietud", technology: "Tecnología", clinic: "Clínica", team: "Equipo", bookAndPay: "Reservar y pagar", bookOnline: "Reservar en línea", financing: "Financiamiento a través de Cherry", portal: "Portal de miembros", serving: "Atendemos a", a11y: "Queremos que todas las personas puedan usar este sitio. Si algo le resulta difícil de acceder, llámenos y le ayudaremos.", privacy: "Privacidad", terms: "Términos", accessibility: "Accesibilidad", siteMap: "Mapa del sitio", director: "Directora médica: Jacqueline Olivo, MD.", trademarks: "Todos los nombres de productos son marcas registradas de sus respectivos propietarios.", results: "Los resultados individuales varían. La candidatura y las expectativas se definen en la consulta.", closed: "Cerrado", to: "a", links: [["/about", "Nosotros"], ["/team", "Equipo"], ["/for-patients", "Para pacientes"], ["/memberships", "Membresías"], ["/specials", "Promociones"], ["/gift-cards", "Tarjetas de regalo"], ["/financing", "Financiamiento"], ["/skincare", "Cuidado de la piel"], ["/treatments/for-men", "Para hombres"], ["/results", "Resultados"], ["/reviews", "Reseñas"], ["/blog", "Revista"], ["/visit", "Visítenos y contacto"]] as [string, string][] },
  textNow: { label: "Accesos directos de contacto", text: "Escríbanos", textShort: "Mensaje", call: "Llamar", book: "Reservar", body: "Hola Olivo, me gustaría reservar una consulta." },
  blocks: { home: "Inicio", learnMore: "Más información", explore: "Explorar", seeAll: "Ver todo", goodToKnow: "Conviene saber", ready: "Cuando usted lo decida.", readyLine: "Reserve en línea en cualquier momento, escríbanos o llame a la clínica en horario de atención.", financingNote: "Financiamiento disponible a través de Cherry. Los términos los establece Cherry al momento de la solicitud.", whatToExpect: "Qué esperar", resultsVary: "Los resultados individuales varían.", consult: "Consulta", consultLine: "Una conversación con el equipo clínico sobre lo que usted quiere cambiar, una evaluación de candidatura y un plan por escrito.", treatment: "Tratamiento", treatmentLine: (n: string) => `Una sesión de ${n} en la clínica, según el calendario que establece el plan.`, aftercare: "Cuidados posteriores", aftercareLine: "Instrucciones en lenguaje claro y un número al que puede llamar o escribir.", followUp: "Seguimiento", followUpLine: "Una revisión del resultado y de lo que sigue, si es que hay algo más." },
  photo: { soon: "Fotografías próximamente", gallerySoon: "Galería de antes y después próximamente", portraitSoon: "Retrato próximamente" },
  hero: { kicker: "Logan Square, Chicago", title: "Llegue tal como es. Salga tal como lo desea.", sub: "Clínica de propiedad y dirección médica de Jacqueline Olivo, MD, con las plataformas completas de BTL y Alma en una clínica tranquila en West Fullerton.", book: "Reservar una consulta", quiz: "Encontrar mi tratamiento", clinic: "Clínica", hours: "Horario", hoursLine: "Lun a vie de 10 a 7, sáb de 10 a 5", reach: "Contáctenos", reachLine: "Escriba o llame al 872-315-3481", scroll: "Desplazar" },
  home: {
    proofKicker: "La clínica", proofTitle: "Propiedad de una médica. Dirigida por una médica. Una clínica tranquila en Fullerton.",
    stats: [["Propiedad y dirección médica desde", "Jacqueline Olivo, MD, fundadora y directora médica"], ["Plataformas de dispositivos en la clínica", "Las plataformas completas de BTL y Alma bajo un mismo techo"], ["Días a la semana", "Lun a vie de 10 a 7, sáb de 10 a 5, en Logan Square"]] as [string, string][],
    treatKicker: "Tratamientos", treatTitle: "¿En qué podemos ayudarle?", treatSub: "Nueve puntos de partida. Cada plan comienza con una consulta y cada tratamiento se elige para usted, no según un menú.", concernPrompt: "¿Prefiere empezar por una inquietud?", browseConcern: "Explorar por inquietud",
    quizKicker: "Cuestionario de dos minutos", quizTitle: "¿No sabe por dónde empezar? Cuéntenos qué cambiaría.", quizSub: "Cinco preguntas. Recibe hasta tres tratamientos para leer y un mensaje de texto que puede enviarnos con un solo toque. No se requiere correo electrónico.", quizOpen: "Abrir el cuestionario completo",
    techKicker: "Tecnología", techTitle: "Las plataformas completas de BTL y Alma, bajo un mismo techo", techSub: "Nueve plataformas de dispositivos, identificadas por marca. Si está aquí, es porque la Dra. Olivo la eligió, se capacitó en ella y la utiliza.", techCta: "Pregunte cuál es la adecuada para usted",
    doctorKicker: "Propiedad y dirección médica", doctorTitle: "Conozca a la Dra. Olivo", doctorRole: "Fundadora, directora general y directora médica", quote: "Envejecer es opcional.", doctorBio: "La Dra. Olivo se formó en medicina familiar y ejerce desde 2007. Abrió Olivo Med Spa en 2013 y sigue siendo su directora médica, lo que explica la lista de equipos: elegidos por una médica, para los pacientes que ella misma atiende.", doctorCta: "Lea su historia", teamCta: "Conozca al equipo",
    resultsKicker: "Resultados", resultsTitle: "Los resultados pertenecen a la persona que los logró.", resultsSub: "Las imágenes reales de antes y después se muestran únicamente con autorización escrita del paciente y se etiquetan con el tratamiento y el número de sesiones.", resultsPolicy: "Sobre nuestra política de resultados",
    reviewsKicker: "En sus palabras", reviewsTitle: "Lo que han dicho los pacientes", reviewsNote: "Testimonios publicados por pacientes en olivomedspa.com. Las experiencias individuales varían.", reviewsGoogle: "Lea las reseñas en Google", via: "vía",
    memKicker: "Membresías y financiamiento", memTitle: "Mantenga un ritmo en lugar de empezar de nuevo.", memSub: "Tres clubes: uno para la piel, uno para el cuerpo y uno para la reducción de vello con láser. Financiamiento disponible a través de Cherry.", memCta: "Ver los detalles", memNote: "Los términos se muestran en la clínica y en el portal de miembros.",
    visitKicker: "Logan Square", visitTitle: "Visítenos en Fullerton", hours: "Horario", parking: "Estacionamiento y transporte", directions: "Cómo llegar", bookVisit: "Reservar una visita", alsoServing: "También atendemos a", mapLabel: "Abrir indicaciones a 2550 W. Fullerton Ave en Google Maps",
    finalTitle: "Nos encantaría verle.", finalLine: "Reserve una consulta en línea en cualquier momento, escríbanos o llame a la clínica en horario de atención.",
  },
};
